-- 领域：07-预约挂号·排班·分诊·叫号
-- 库：hn_biz_his    表数：8
-- 说明：DDL 快照（由线上库 SHOW CREATE TABLE 导出，无 DROP / 无数据）。建表语句彼此独立，不含外键约束。

-- ----------------------------
-- biz_appoint_info  挂号信息
-- ----------------------------
CREATE TABLE `biz_appoint_info` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `regist_no` varchar(32) NOT NULL COMMENT '挂号单号（唯一）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别（1-男 2-女 3-未知）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号码',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `room_id` bigint DEFAULT NULL COMMENT '诊室ID',
  `room_name` varchar(100) DEFAULT NULL COMMENT '诊室名称',
  `doctor_id` bigint DEFAULT NULL COMMENT '医生ID',
  `doctor_name` varchar(50) DEFAULT NULL COMMENT '医生姓名',
  `schedule_id` bigint DEFAULT NULL COMMENT '排班ID',
  `slot_id` bigint DEFAULT NULL COMMENT '排班时间片段ID',
  `slot_start` char(5) DEFAULT NULL COMMENT '就诊时段开始快照（HH:mm）',
  `slot_end` char(5) DEFAULT NULL COMMENT '就诊时段结束快照（HH:mm）',
  `regist_type` tinyint DEFAULT '1' COMMENT '挂号类型（1-普通号 2-专家号 3-急诊号 4-免费号）',
  `regist_source` tinyint DEFAULT '1' COMMENT '挂号来源（1-窗口挂号 2-自助机挂号 3-网上挂号 4-预约挂号）',
  `regist_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '挂号时间',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `arrive_time` datetime DEFAULT NULL COMMENT '到达时间',
  `schedule_type` tinyint DEFAULT NULL COMMENT '时间段（1-上午 2-下午 3-全天 4-凌晨）',
  `slot_time` varchar(8) DEFAULT NULL COMMENT '就诊时段',
  `visit_type` tinyint NOT NULL COMMENT '就诊类型（号别）（1-初诊 2-复诊）',
  `revisit_source` tinyint DEFAULT NULL COMMENT '复诊来源（1-当日回诊 2-医嘱复诊预约 3-患者自助复诊 4-随访计划复诊）',
  `settlement_type` tinyint DEFAULT '1' COMMENT '结算方式（1-自费 2-城镇职工医保 3-城乡居民医保 4-公费 5-商业保险）',
  `medical_insurance_type` varchar(50) DEFAULT NULL COMMENT '医保类型（如：在职职工、退休职工、城乡居民等）',
  `medical_insurance_no` varchar(50) DEFAULT NULL COMMENT '医保卡号',
  `regist_status` tinyint DEFAULT '1' COMMENT '挂号状态（1-已挂号 2-已签到 3-已接诊 4-已就诊 5-已退号 6-已过号 7-爽约 8-未就诊）',
  `revisit_type` tinyint DEFAULT NULL COMMENT '【已废置】改用 visit_type',
  `revisit_record_id` bigint DEFAULT NULL COMMENT '复诊关联的病历ID',
  `refund_time` datetime DEFAULT NULL COMMENT '退号时间',
  `refund_reason` varchar(200) DEFAULT NULL COMMENT '退号原因',
  `bill_id` bigint DEFAULT NULL COMMENT '挂号费结算账单ID',
  `bill_no` varchar(32) DEFAULT NULL COMMENT '账单号',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_by_id` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_by_id` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_regist_no` (`regist_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_patient_no` (`patient_no`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_doctor_id` (`doctor_id`),
  KEY `idx_visit_date` (`visit_date`),
  KEY `idx_regist_status` (`regist_status`),
  KEY `idx_slot_id` (`slot_id`),
  KEY `idx_revisit_record_id` (`revisit_record_id`),
  KEY `idx_appoint_bill` (`bill_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='挂号信息';

-- ----------------------------
-- biz_schedule_template  排班周模板
-- ----------------------------
CREATE TABLE `biz_schedule_template` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '科室名称',
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `doctor_name` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '医生姓名',
  `staff_type` tinyint NOT NULL DEFAULT '1' COMMENT '排班对象岗位类别（2-护理 3-医技 4-药学 5-收费 6-行政其他）',
  `week_day` tinyint NOT NULL COMMENT '星期几（1-周一 7-周日）',
  `week_parity` tinyint NOT NULL DEFAULT '0' COMMENT '单双周（0-每周 1-单周 2-双周）',
  `valid_from` date DEFAULT NULL COMMENT '生效起始日期(空=不限)',
  `valid_until` date DEFAULT NULL COMMENT '生效截止日期(空=不限)',
  `schedule_type` tinyint DEFAULT NULL COMMENT '班次（1-上午 2-下午 3-全天 4-凌晨）',
  `start_time` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '08:00' COMMENT '开始时间（HH:mm）',
  `end_time` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '12:00' COMMENT '结束时间（HH:mm）',
  `shift_id` bigint DEFAULT NULL COMMENT '标准班次ID',
  `total_source` int NOT NULL DEFAULT '20' COMMENT '号源总数',
  `room_id` bigint DEFAULT NULL COMMENT '诊室ID',
  `room_name` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '诊室名称',
  `regist_fee` decimal(10,2) DEFAULT '0.00' COMMENT '挂号费',
  `diagnosis_fee` decimal(10,2) DEFAULT '0.00' COMMENT '诊疗费',
  `is_expert` tinyint DEFAULT '0' COMMENT '是否专家（0-否 1-是）',
  `expert_fee` decimal(10,2) DEFAULT '0.00' COMMENT '专家费',
  `is_appointment` tinyint DEFAULT '1' COMMENT '是否开放预约（0-否 1-是）',
  `appointment_source` int DEFAULT '0' COMMENT '预约号源数',
  `status` tinyint DEFAULT '1' COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tpl_dept_doctor` (`dept_id`,`doctor_id`),
  KEY `idx_tpl_week` (`week_day`),
  KEY `idx_template_shift` (`shift_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='排班周模板';

-- ----------------------------
-- biz_schedule_slot_template  排班模板时段
-- ----------------------------
CREATE TABLE `biz_schedule_slot_template` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_id` bigint NOT NULL COMMENT '排班模板ID',
  `seq` int NOT NULL COMMENT '段序',
  `start_time` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '段开始时间（HH:mm）',
  `end_time` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '段结束时间（HH:mm）',
  `total_source` int NOT NULL DEFAULT '0' COMMENT '段号源总数',
  `appointment_source` int NOT NULL DEFAULT '0' COMMENT '段内线上预约预留',
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tpl_slot` (`template_id`,`start_time`),
  KEY `idx_tpl_slot_template` (`template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='排班模板时段';

-- ----------------------------
-- biz_schedule  排班信息
-- ----------------------------
CREATE TABLE `biz_schedule` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `schedule_date` date NOT NULL COMMENT '排班日期',
  `week_day` tinyint NOT NULL COMMENT '星期（1-周日 2-周一 3-周二 4-周三 5-周四 6-周五 7-周六）',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `room_id` bigint DEFAULT NULL COMMENT '诊室ID',
  `room_name` varchar(100) DEFAULT NULL COMMENT '诊室名称',
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '医生姓名',
  `staff_type` tinyint NOT NULL DEFAULT '1' COMMENT '排班对象岗位类别（2-护理 3-医技 4-药学 5-收费 6-行政其他）',
  `schedule_type` tinyint DEFAULT NULL COMMENT '排班类型（1-上午 2-下午 3-全天 4-凌晨）',
  `start_time` varchar(10) NOT NULL COMMENT '开始时间',
  `end_time` varchar(10) NOT NULL COMMENT '结束时间',
  `shift_id` bigint DEFAULT NULL COMMENT '标准班次ID',
  `total_source` int DEFAULT '0' COMMENT '总号源数',
  `used_source` int DEFAULT '0' COMMENT '已挂号数',
  `available_source` int DEFAULT '0' COMMENT '剩余号源数',
  `used_appointment_source` int NOT NULL DEFAULT '0' COMMENT '预约池已用号源',
  `regist_fee` decimal(10,2) DEFAULT '0.00' COMMENT '挂号费',
  `diagnosis_fee` decimal(10,2) DEFAULT '0.00' COMMENT '诊查费',
  `is_expert` tinyint DEFAULT '0' COMMENT '是否专家号（0-否 1-是）',
  `expert_fee` decimal(10,2) DEFAULT '0.00' COMMENT '专家号费用',
  `is_appointment` tinyint DEFAULT '1' COMMENT '是否可预约（0-否 1-是）',
  `appointment_source` int DEFAULT '0' COMMENT '预约号源数',
  `added_source` int NOT NULL DEFAULT '0' COMMENT '累计加号数',
  `status` tinyint DEFAULT '1' COMMENT '状态（0-停诊 1-正常 2-已满 3-已过期）',
  `consult_status` tinyint DEFAULT '0' COMMENT '就诊状态（0-待开始 1-接诊中 2-暂停）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_schedule_window` (`dept_id`,`doctor_id`,`schedule_date`,`start_time`,`end_time`),
  KEY `idx_schedule_date` (`schedule_date`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_doctor_id` (`doctor_id`),
  KEY `idx_week_day` (`week_day`),
  KEY `idx_room_id` (`room_id`),
  KEY `idx_schedule_shift` (`shift_id`),
  KEY `idx_schedule_dept_date_staff` (`dept_id`,`schedule_date`,`staff_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='排班信息';

-- ----------------------------
-- biz_schedule_slot  排班时段号源
-- ----------------------------
CREATE TABLE `biz_schedule_slot` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `schedule_id` bigint NOT NULL COMMENT '排班ID',
  `seq` int NOT NULL COMMENT '段序',
  `start_time` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '段开始时间（HH:mm）',
  `end_time` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '段结束时间（HH:mm）',
  `total_source` int NOT NULL DEFAULT '0' COMMENT '段号源总数',
  `used_source` int NOT NULL DEFAULT '0' COMMENT '段已挂号数（现场+线上）',
  `available_source` int NOT NULL DEFAULT '0' COMMENT '段剩余号源',
  `added_source` int NOT NULL DEFAULT '0' COMMENT '段累计加号数',
  `appointment_source` int NOT NULL DEFAULT '0' COMMENT '段内线上预约预留',
  `used_appointment_source` int NOT NULL DEFAULT '0' COMMENT '段内线上预约已用',
  `status` tinyint DEFAULT '1' COMMENT '段状态（0-停用 1-正常）',
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_slot` (`schedule_id`,`start_time`),
  KEY `idx_slot_schedule` (`schedule_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='排班时段号源';

-- ----------------------------
-- biz_triage_record  门诊分诊记录
-- ----------------------------
CREATE TABLE `biz_triage_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `queue_id` bigint NOT NULL COMMENT '队列ID',
  `regist_id` bigint DEFAULT NULL COMMENT '挂号ID',
  `patient_id` bigint DEFAULT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `temperature` decimal(4,1) DEFAULT NULL COMMENT '体温(℃)',
  `pulse` int DEFAULT NULL COMMENT '脉搏(次/分)',
  `respiration` int DEFAULT NULL COMMENT '呼吸(次/分)',
  `systolic_bp` int DEFAULT NULL COMMENT '收缩压(mmHg)',
  `diastolic_bp` int DEFAULT NULL COMMENT '舒张压(mmHg)',
  `spo2` int DEFAULT NULL COMMENT '血氧饱和度(%)',
  `height` decimal(5,1) DEFAULT NULL COMMENT '身高(cm)',
  `weight` decimal(5,1) DEFAULT NULL COMMENT '体重(kg)',
  `bmi` decimal(4,1) DEFAULT NULL COMMENT 'BMI',
  `pain_score` tinyint DEFAULT NULL COMMENT '疼痛评分',
  `chief_complaint` varchar(500) DEFAULT NULL COMMENT '主诉',
  `triage_level` tinyint DEFAULT NULL COMMENT '分诊等级（1-危重 2-急症 3-亚急 4-非急）',
  `room_id` bigint DEFAULT NULL COMMENT '分配诊室ID',
  `room_name` varchar(64) DEFAULT NULL COMMENT '分配诊室名称',
  `triage_nurse_id` bigint DEFAULT NULL COMMENT '分诊护士员工ID',
  `triage_nurse_name` varchar(50) DEFAULT NULL COMMENT '分诊护士姓名',
  `triage_time` datetime DEFAULT NULL COMMENT '分诊时刻',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  KEY `idx_triage_queue` (`queue_id`),
  KEY `idx_triage_regist` (`regist_id`),
  KEY `idx_triage_time` (`triage_time`),
  KEY `idx_triage_nurse_time` (`triage_nurse_id`,`triage_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='门诊分诊记录';

-- ----------------------------
-- biz_queue  候诊队列
-- ----------------------------
CREATE TABLE `biz_queue` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `queue_no` varchar(20) NOT NULL COMMENT '排队序号',
  `regist_id` bigint NOT NULL COMMENT '挂号ID',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `doctor_id` bigint DEFAULT NULL COMMENT '医生ID',
  `doctor_name` varchar(50) DEFAULT NULL COMMENT '医生姓名',
  `queue_type` tinyint DEFAULT '1' COMMENT '队列类型（1-普通队列 2-优先队列 3-过号队列）',
  `regist_type` tinyint DEFAULT '1' COMMENT '挂号类型（1-普通号 2-专家号 3-急诊号 4-免费号）',
  `queue_status` tinyint DEFAULT '2' COMMENT '排队状态（2-候诊中 3-就诊中 4-已就诊 5-已退号 6-已过号 7-已失效）',
  `triage_status` tinyint NOT NULL DEFAULT '0' COMMENT '分诊状态（0-未分诊 1-已分诊）',
  `triage_level` tinyint DEFAULT NULL COMMENT '分诊等级（1-危重 2-急症 3-亚急 4-非急）',
  `room_id` bigint DEFAULT NULL COMMENT '诊室ID',
  `room_name` varchar(64) DEFAULT NULL COMMENT '诊室名称',
  `sequence_no` int NOT NULL COMMENT '顺序号',
  `call_time` datetime DEFAULT NULL COMMENT '叫号时间',
  `call_count` int DEFAULT '0' COMMENT '叫号次数',
  `arrive_time` datetime DEFAULT NULL COMMENT '到达时间',
  `start_time` datetime DEFAULT NULL COMMENT '开始就诊时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束就诊时间',
  `wait_duration` int DEFAULT '0' COMMENT '等待时长（分钟）',
  `is_overdue` tinyint DEFAULT '0' COMMENT '是否过号（0-否 1-是）',
  `overdue_time` datetime DEFAULT NULL COMMENT '过号时间',
  `overdue_reason` varchar(200) DEFAULT NULL COMMENT '过号原因',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_regist_id` (`regist_id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_doctor_id` (`doctor_id`),
  KEY `idx_queue_status` (`queue_status`),
  KEY `idx_queue_triage_order` (`visit_date`,`queue_status`,`triage_level`,`sequence_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='候诊队列';

-- ----------------------------
-- biz_revisit_fee_policy  复诊收费策略
-- ----------------------------
CREATE TABLE `biz_revisit_fee_policy` (
  `id` bigint NOT NULL COMMENT '主键',
  `policy_name` varchar(100) NOT NULL COMMENT '策略名称',
  `revisit_source` tinyint NOT NULL COMMENT '复诊来源（1-当日回诊 2-医嘱复诊预约 3-患者自助复诊 4-随访计划复诊 0-不限）',
  `same_doctor` tinyint NOT NULL DEFAULT '0' COMMENT '与原就诊医生（0-不限 1-要求同一医生 2-要求不同医生）',
  `same_dept` tinyint NOT NULL DEFAULT '0' COMMENT '与原就诊科室（0-不限 1-要求同一科室 2-要求不同科室）',
  `within_days` int DEFAULT NULL COMMENT '与原就诊日最大间隔天数',
  `charge_mode` tinyint NOT NULL COMMENT '收费方式（1-全额收费 2-免挂号费 3-免挂号费+诊查费）',
  `priority` int NOT NULL DEFAULT '100' COMMENT '匹配优先级',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `del_flag` tinyint NOT NULL DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_revisit_source` (`revisit_source`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='复诊收费策略';
