-- 领域：09-住院与医嘱（入出转·会诊·床位调度）
-- 库：hn_biz_his    表数：14
-- 说明：DDL 快照（由线上库 SHOW CREATE TABLE 导出，无 DROP / 无数据）。建表语句彼此独立，不含外键约束。

-- ----------------------------
-- biz_admission  入院记录
-- ----------------------------
CREATE TABLE `biz_admission` (
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `admission_no` varchar(32) NOT NULL COMMENT '入院记录号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `visit_id` bigint DEFAULT NULL COMMENT '就诊次ID',
  `regist_id` bigint DEFAULT NULL COMMENT '来源挂号ID',
  `regist_no` varchar(32) DEFAULT NULL COMMENT '来源挂号号（快照）',
  `admission_order_id` bigint DEFAULT NULL COMMENT '来源住院证ID',
  `admit_dept_id` bigint DEFAULT NULL COMMENT '入院科室ID',
  `dept_id` bigint DEFAULT NULL COMMENT '入院科室ID',
  `ward_id` bigint NOT NULL COMMENT '病区ID',
  `bed_id` bigint NOT NULL COMMENT '床位ID',
  `admit_doctor_id` bigint NOT NULL COMMENT '入院医生ID',
  `admit_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入院时间',
  `admit_way` tinyint DEFAULT NULL COMMENT '入院途径（1-门诊 2-急诊 3-转院 4-其他）',
  `diagnosis` varchar(500) DEFAULT NULL COMMENT '入院诊断',
  `admit_diagnosis_code` varchar(32) DEFAULT NULL COMMENT '入院诊断ICD编码',
  `admit_diagnosis_name` varchar(200) DEFAULT NULL COMMENT '入院诊断名称',
  `discharge_time` datetime DEFAULT NULL COMMENT '出院时间',
  `admit_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（0-已出院 1-在院）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`admission_id`),
  UNIQUE KEY `uk_admission_no` (`admission_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_bed_id` (`bed_id`),
  KEY `idx_admit_time` (`admit_time`),
  KEY `idx_adm_status` (`admit_status`),
  KEY `idx_adm_patient` (`patient_id`),
  KEY `idx_adm_bed` (`bed_id`),
  KEY `idx_adm_regist` (`regist_id`),
  KEY `idx_adm_admit_order` (`admission_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='入院记录';

-- ----------------------------
-- biz_admission_order  入院通知单
-- ----------------------------
CREATE TABLE `biz_admission_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_no` varchar(32) NOT NULL COMMENT '住院证号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话（快照）',
  `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号（快照）',
  `regist_id` bigint DEFAULT NULL COMMENT '来源挂号ID',
  `regist_no` varchar(32) DEFAULT NULL COMMENT '来源挂号号',
  `visit_id` bigint DEFAULT NULL COMMENT '来源就诊次ID',
  `source_dept_id` bigint DEFAULT NULL COMMENT '开证科室ID',
  `source_dept_name` varchar(100) DEFAULT NULL COMMENT '开证科室名称（快照）',
  `source_doctor_id` bigint DEFAULT NULL COMMENT '开证医生ID',
  `source_doctor_name` varchar(50) DEFAULT NULL COMMENT '开证医生姓名（快照）',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '拟收治科室ID',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '拟收治科室名称（快照）',
  `diagnosis_code` varchar(32) DEFAULT NULL COMMENT '拟诊ICD编码',
  `diagnosis_name` varchar(200) DEFAULT NULL COMMENT '拟诊名称',
  `diagnosis_note` varchar(500) DEFAULT NULL COMMENT '病情与收治说明',
  `insurance_type` varchar(50) DEFAULT NULL COMMENT '医保类型',
  `medical_insurance_no` varchar(50) DEFAULT NULL COMMENT '医保卡号',
  `order_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-待收治 2-已收治 3-已作废 4-已过期）',
  `expect_admit_time` datetime DEFAULT NULL COMMENT '预计入院时间',
  `order_time` datetime NOT NULL COMMENT '开证时间',
  `valid_until` datetime DEFAULT NULL COMMENT '有效期至',
  `admission_id` bigint DEFAULT NULL COMMENT '收治后回填的入院ID',
  `admit_time` datetime DEFAULT NULL COMMENT '实际收治时间',
  `admit_dept_id` bigint DEFAULT NULL COMMENT '实际收治科室ID',
  `cancel_reason` varchar(200) DEFAULT NULL COMMENT '作废原因',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ao_order_no` (`order_no`),
  KEY `idx_ao_status` (`order_status`),
  KEY `idx_ao_patient` (`patient_id`),
  KEY `idx_ao_regist` (`regist_id`),
  KEY `idx_ao_admission` (`admission_id`),
  KEY `idx_ao_dept` (`apply_dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='入院通知单';

-- ----------------------------
-- biz_inpatient_order  住院医嘱主表
-- ----------------------------
CREATE TABLE `biz_inpatient_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_no` varchar(32) NOT NULL COMMENT '医嘱号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `dept_id` bigint DEFAULT NULL COMMENT '开立科室ID',
  `dept_name` varchar(64) DEFAULT NULL COMMENT '开立科室名称（快照）',
  `ward_id` bigint DEFAULT NULL COMMENT '病区ID',
  `ward_name` varchar(64) DEFAULT NULL COMMENT '病区名称（快照）',
  `bed_no` varchar(32) DEFAULT NULL COMMENT '床号（快照）',
  `order_type` tinyint NOT NULL COMMENT '医嘱类型（1-长期 2-临时）',
  `order_group` varchar(32) DEFAULT NULL COMMENT '组套号',
  `order_class` tinyint NOT NULL COMMENT '医嘱类别',
  `item_code` varchar(64) DEFAULT NULL COMMENT '项目编码（药品/检查/检验字典码）',
  `item_name` varchar(200) NOT NULL COMMENT '项目名称',
  `spec` varchar(100) DEFAULT NULL COMMENT '规格',
  `unit` varchar(20) DEFAULT NULL COMMENT '单位',
  `dosage` decimal(12,3) DEFAULT NULL COMMENT '单次剂量',
  `dosage_unit` varchar(20) DEFAULT NULL COMMENT '剂量单位',
  `route` varchar(64) DEFAULT NULL COMMENT '给药途径（口服/静滴/肌注…）',
  `frequency` varchar(32) DEFAULT NULL COMMENT '频次（qd/bid/tid/q8h…）',
  `quantity` decimal(10,2) NOT NULL DEFAULT '1.00' COMMENT '本次执行数量',
  `price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '单价',
  `amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '本次执行金额（元）',
  `start_time` datetime NOT NULL COMMENT '医嘱开始时间',
  `plan_end_time` datetime DEFAULT NULL COMMENT '计划结束时间',
  `stop_time` datetime DEFAULT NULL COMMENT '实际停止时间',
  `order_time` datetime NOT NULL COMMENT '开立时间',
  `doctor_id` bigint DEFAULT NULL COMMENT '开立医生ID（员工ID）',
  `doctor_name` varchar(64) DEFAULT NULL COMMENT '开立医生姓名',
  `doctor_sign_id` bigint DEFAULT NULL COMMENT '开立医生签名ID',
  `doctor_signed_time` datetime DEFAULT NULL COMMENT '开立签名时刻',
  `verify_nurse_id` bigint DEFAULT NULL COMMENT '校对护士ID（员工ID）',
  `verify_nurse_name` varchar(64) DEFAULT NULL COMMENT '校对护士姓名',
  `verify_time` datetime DEFAULT NULL COMMENT '校对时间',
  `nurse_sign_id` bigint DEFAULT NULL COMMENT '校对护士签名ID',
  `nurse_signed_time` datetime DEFAULT NULL COMMENT '校对签名时刻',
  `stop_doctor_id` bigint DEFAULT NULL COMMENT '停止医嘱的医生ID',
  `stop_doctor_name` varchar(64) DEFAULT NULL COMMENT '停止医嘱的医生姓名',
  `stop_reason` varchar(200) DEFAULT NULL COMMENT '停止原因',
  `order_status` tinyint NOT NULL DEFAULT '1' COMMENT '医嘱状态（1-待校对 2-已校对 3-执行中 4-已完成 5-已停止 6-已作废 7-已退回）',
  `is_urgent` tinyint NOT NULL DEFAULT '0' COMMENT '是否加急（0-否 1-是）',
  `source` tinyint NOT NULL DEFAULT '1' COMMENT '医嘱来源（1-医生 2-模板 3-组套）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_io_admission` (`admission_id`,`order_status`),
  KEY `idx_io_group` (`order_group`),
  KEY `idx_io_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='住院医嘱主表';

-- ----------------------------
-- biz_inpatient_order_exec  医嘱执行记录
-- ----------------------------
CREATE TABLE `biz_inpatient_order_exec` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '医嘱ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint DEFAULT NULL COMMENT '患者ID（冗余）',
  `exec_seq` int NOT NULL DEFAULT '1' COMMENT '本条医嘱的第几次执行',
  `plan_date` date NOT NULL COMMENT '计划日期',
  `plan_time` datetime NOT NULL COMMENT '计划执行时间',
  `exec_time` datetime DEFAULT NULL COMMENT '实际执行时间',
  `exec_nurse_id` bigint DEFAULT NULL COMMENT '执行护士ID（员工ID）',
  `exec_nurse_name` varchar(64) DEFAULT NULL COMMENT '执行护士姓名',
  `exec_status` tinyint NOT NULL DEFAULT '1' COMMENT '执行状态（1-待执行 2-已执行 3-已跳过 4-已退回）',
  `exec_note` varchar(255) DEFAULT NULL COMMENT '执行备注 / 跳过原因',
  `infusion_start_time` datetime DEFAULT NULL COMMENT '输液开始时间',
  `drip_rate` int DEFAULT NULL COMMENT '开始滴速（滴/分）',
  `infusion_end_time` datetime DEFAULT NULL COMMENT '输液结束时间',
  `adverse_flag` tinyint NOT NULL DEFAULT '0' COMMENT '输液不良反应（0-无 1-有）',
  `adverse_note` varchar(255) DEFAULT NULL COMMENT '不良反应描述',
  `fee_record_id` bigint DEFAULT NULL COMMENT '本次执行生成的记账行ID',
  `fee_no` varchar(32) DEFAULT NULL COMMENT '本次执行生成的记账单号',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ioe_order_plan_date` (`order_id`,`plan_date`),
  KEY `idx_ioe_admission` (`admission_id`,`exec_status`),
  KEY `idx_ioe_pending` (`exec_status`,`plan_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='医嘱执行记录';

-- ----------------------------
-- biz_inpatient_order_template  医嘱模板
-- ----------------------------
CREATE TABLE `biz_inpatient_order_template` (
  `id` bigint NOT NULL COMMENT '模板ID',
  `doctor_id` bigint DEFAULT NULL COMMENT '归属医生',
  `doctor_name` varchar(64) DEFAULT NULL COMMENT '医生姓名（快照）',
  `dept_id` bigint DEFAULT NULL COMMENT '创建时科室ID',
  `scope` tinyint NOT NULL DEFAULT '1' COMMENT '共享范围（1-个人 2-科室 3-全院）',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `order_type` tinyint NOT NULL DEFAULT '2' COMMENT '默认医嘱类型（1-长期 2-临时）',
  `item_count` int NOT NULL DEFAULT '0' COMMENT '明细条数',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注/适用场景说明',
  PRIMARY KEY (`id`),
  KEY `idx_biot_doctor` (`doctor_id`),
  KEY `idx_biot_name` (`template_name`),
  KEY `idx_scope_dept` (`scope`,`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='医嘱模板';

-- ----------------------------
-- biz_inpatient_order_template_item  医嘱模板明细
-- ----------------------------
CREATE TABLE `biz_inpatient_order_template_item` (
  `id` bigint NOT NULL COMMENT '明细ID',
  `template_id` bigint NOT NULL COMMENT '模板主表ID',
  `sort_no` int NOT NULL DEFAULT '0' COMMENT '排序',
  `order_class` tinyint NOT NULL COMMENT '医嘱类别',
  `item_code` varchar(64) DEFAULT NULL COMMENT '项目编码（药品/检查/检验字典码，套用时按它回查现价与下拉选中态）',
  `item_name` varchar(200) NOT NULL COMMENT '项目名称',
  `spec` varchar(100) DEFAULT NULL COMMENT '规格',
  `unit` varchar(32) DEFAULT NULL COMMENT '单位',
  `dosage` decimal(12,4) DEFAULT NULL COMMENT '单次剂量',
  `dosage_unit` varchar(32) DEFAULT NULL COMMENT '剂量单位',
  `route` varchar(64) DEFAULT NULL COMMENT '给药途径',
  `frequency` varchar(32) DEFAULT NULL COMMENT '频次',
  `quantity` decimal(12,2) NOT NULL DEFAULT '1.00' COMMENT '数量',
  `price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '录入时单价',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_bioti_tpl` (`template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='医嘱模板明细';

-- ----------------------------
-- biz_inpatient_transfer  住院转科轨迹
-- ----------------------------
CREATE TABLE `biz_inpatient_transfer` (
  `id` bigint NOT NULL COMMENT '转科记录ID',
  `transfer_no` varchar(32) NOT NULL COMMENT '转科单号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `admission_no` varchar(32) DEFAULT NULL COMMENT '入院号（快照）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `from_dept_id` bigint DEFAULT NULL COMMENT '转出科室ID',
  `from_dept_name` varchar(64) DEFAULT NULL COMMENT '转出科室名称（快照）',
  `from_ward_id` bigint DEFAULT NULL COMMENT '转出病区ID',
  `from_ward_name` varchar(64) DEFAULT NULL COMMENT '转出病区名称（快照）',
  `from_bed_id` bigint DEFAULT NULL COMMENT '转出床位ID',
  `from_bed_no` varchar(32) DEFAULT NULL COMMENT '转出床位号（快照）',
  `to_dept_id` bigint NOT NULL COMMENT '转入科室ID',
  `to_dept_name` varchar(64) DEFAULT NULL COMMENT '转入科室名称（快照）',
  `to_ward_id` bigint NOT NULL COMMENT '转入病区ID',
  `to_ward_name` varchar(64) DEFAULT NULL COMMENT '转入病区名称（快照）',
  `to_bed_id` bigint NOT NULL COMMENT '转入床位ID',
  `to_bed_no` varchar(32) DEFAULT NULL COMMENT '转入床位号（快照）',
  `transfer_type` tinyint NOT NULL DEFAULT '1' COMMENT '转科类型（1-普通转科 2-急诊转科 3-转入ICU 4-ICU转出）',
  `transfer_reason` varchar(500) NOT NULL COMMENT '转科原因',
  `hospital_days` int DEFAULT NULL COMMENT '发起转科时该次住院的已住院天数',
  `stop_orders_count` int NOT NULL DEFAULT '0' COMMENT '接收时随之停止的长期医嘱条数',
  `order_remark` varchar(500) DEFAULT NULL COMMENT '医嘱处置说明',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '转出方发起医生ID',
  `apply_doctor_name` varchar(64) DEFAULT NULL COMMENT '转出方发起医生姓名（快照）',
  `receive_doctor_id` bigint DEFAULT NULL COMMENT '转入方接收医生ID（员工ID）',
  `receive_doctor_name` varchar(64) DEFAULT NULL COMMENT '转入方接收医生姓名（快照）',
  `record_id` bigint DEFAULT NULL COMMENT '回写的住院病历ID',
  `apply_time` datetime DEFAULT NULL COMMENT '发起时间',
  `receive_time` datetime DEFAULT NULL COMMENT '接收时间',
  `transfer_status` tinyint NOT NULL DEFAULT '0' COMMENT '转科状态（0-待接收 1-已完成 2-已取消）',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  KEY `idx_transfer_admission` (`admission_id`),
  KEY `idx_transfer_status` (`transfer_status`),
  KEY `idx_transfer_time` (`receive_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='住院转科轨迹';

-- ----------------------------
-- biz_inpatient_leave  住院请假登记
-- ----------------------------
CREATE TABLE `biz_inpatient_leave` (
  `id` bigint NOT NULL COMMENT '主键（雪花ID）',
  `leave_no` varchar(32) NOT NULL COMMENT '请假单号',
  `admission_id` bigint NOT NULL COMMENT '住院记录ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名（快照）',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者编号（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `dept_id` bigint DEFAULT NULL COMMENT '申请时点所在科室ID',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '科室名称（快照）',
  `ward_name` varchar(64) DEFAULT NULL COMMENT '病区名称（快照）',
  `bed_no` varchar(16) DEFAULT NULL COMMENT '床位号（快照）',
  `admission_no` varchar(32) DEFAULT NULL COMMENT '住院号（快照）',
  `leave_type` tinyint NOT NULL COMMENT '请假类别（1-临时外出当日往返 2-离院过夜 9-其他）',
  `reason` varchar(500) NOT NULL COMMENT '请假事由（必填）',
  `destination` varchar(200) NOT NULL COMMENT '去向',
  `companion_name` varchar(50) NOT NULL COMMENT '随行/联系人姓名（必填）',
  `companion_relation` tinyint DEFAULT NULL COMMENT '随行人与患者关系',
  `companion_phone` varchar(20) NOT NULL COMMENT '随行人联系电话（必填）',
  `expected_leave_time` datetime NOT NULL COMMENT '预计离院时间',
  `expected_return_time` datetime NOT NULL COMMENT '预计返回时间',
  `apply_time` datetime NOT NULL COMMENT '申请时间',
  `apply_by` varchar(64) DEFAULT NULL COMMENT '申请人',
  `doctor_advice` varchar(1000) DEFAULT NULL COMMENT '医师意见',
  `approve_time` datetime DEFAULT NULL COMMENT '审批时间',
  `doctor_id` bigint DEFAULT NULL COMMENT '审批医师ID',
  `doctor_name` varchar(50) DEFAULT NULL COMMENT '审批医师姓名',
  `reject_reason` varchar(500) DEFAULT NULL COMMENT '拒绝理由',
  `confirm_name` varchar(50) DEFAULT NULL COMMENT '患方确认人姓名',
  `confirm_relation` tinyint DEFAULT NULL COMMENT '确认人与患者关系',
  `confirm_phone` varchar(20) DEFAULT NULL COMMENT '确认人联系电话',
  `confirm_signature` mediumtext COMMENT '患方手写签名',
  `confirm_time` datetime DEFAULT NULL COMMENT '患方签署时间',
  `actual_leave_time` datetime DEFAULT NULL COMMENT '实际离院时间',
  `actual_return_time` datetime DEFAULT NULL COMMENT '实际返回时间',
  `return_note` varchar(500) DEFAULT NULL COMMENT '返回情况备注',
  `return_by` varchar(64) DEFAULT NULL COMMENT '销假经办人',
  `leave_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-待审批 2-已批准 3-已离院 4-已返回 5-已拒绝 6-已取消）',
  `overdue_contact_result` tinyint DEFAULT NULL COMMENT '超期联系结果（1-联系上并约定返回 2-联系不上 3-家属）',
  `overdue_contact_note` varchar(500) DEFAULT NULL COMMENT '超期处置备注',
  `overdue_contact_time` datetime DEFAULT NULL COMMENT '超期处置时间',
  `overdue_contact_by` varchar(64) DEFAULT NULL COMMENT '超期处置人',
  `report_to` tinyint DEFAULT NULL COMMENT '上报对象（1-主管医师 2-病区护士长 3-医务科）',
  `printer_name` varchar(64) DEFAULT NULL COMMENT '最后打印人',
  `print_count` int NOT NULL DEFAULT '0' COMMENT '承诺书打印次数',
  `last_print_time` datetime DEFAULT NULL COMMENT '最后打印时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `cancel_by` varchar(64) DEFAULT NULL COMMENT '取消经办人',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `sign_status` tinyint NOT NULL DEFAULT '0' COMMENT '电子签名状态（0-未签名 1-已签名 2-签名已作废）',
  `sign_id` bigint DEFAULT NULL COMMENT '当前有效签名ID',
  `signed_time` datetime DEFAULT NULL COMMENT '签名时刻',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_leave_no` (`leave_no`) COMMENT '单号一经生成不复用，软删行不会与新单撞号',
  KEY `idx_leave_admission` (`admission_id`,`leave_status`) COMMENT '按住院回看该患者的全部请假史与在途单',
  KEY `idx_leave_status_time` (`leave_status`,`expected_return_time`) COMMENT '在途榜（已离院未归）+ 超期榜一次索引扫',
  KEY `idx_leave_dept` (`dept_id`,`apply_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='住院请假登记';

-- ----------------------------
-- biz_critical_notice  病危重通知回执
-- ----------------------------
CREATE TABLE `biz_critical_notice` (
  `id` bigint NOT NULL COMMENT '主键（雪花ID）',
  `notice_no` varchar(32) NOT NULL COMMENT '通知单号',
  `admission_id` bigint NOT NULL COMMENT '住院记录ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名（快照）',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者编号（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 3-未知）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `dept_id` bigint DEFAULT NULL COMMENT '开单科室ID',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '开单科室名称（快照）',
  `ward_name` varchar(64) DEFAULT NULL COMMENT '病区名称（快照）',
  `bed_no` varchar(16) DEFAULT NULL COMMENT '床位号（快照）',
  `admission_no` varchar(32) DEFAULT NULL COMMENT '住院号（快照）',
  `notice_type` tinyint NOT NULL COMMENT '通知类别（1-病危 2-病重）',
  `consciousness_status` tinyint NOT NULL DEFAULT '1' COMMENT '患者神志（1-清醒 2-嗜睡 3-意识模糊 4-昏迷 9-其他）',
  `clinical_diagnosis` varchar(500) NOT NULL COMMENT '目前诊断',
  `condition_desc` varchar(1000) NOT NULL COMMENT '病情及危险因素',
  `warning_matters` varchar(1000) NOT NULL COMMENT '可能的病情变化与预警事项',
  `doctor_measures` varchar(1000) DEFAULT NULL COMMENT '医方已采取/拟采取的诊治措施与配合要求',
  `notify_time` datetime NOT NULL COMMENT '告知时间',
  `doctor_id` bigint DEFAULT NULL COMMENT '告知医师ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '告知医师姓名',
  `witness_doctor_id` bigint DEFAULT NULL COMMENT '见证医师ID',
  `witness_doctor_name` varchar(50) DEFAULT NULL COMMENT '见证医师姓名（可空）',
  `signer_name` varchar(50) DEFAULT NULL COMMENT '签收人姓名',
  `signer_relation` tinyint DEFAULT NULL COMMENT '签收人与患者关系',
  `signer_id_card` varchar(20) DEFAULT NULL COMMENT '签收人证件号',
  `signer_phone` varchar(20) DEFAULT NULL COMMENT '签收人联系电话',
  `signer_signature` mediumtext COMMENT '签收人手写签名',
  `acknowledge_time` datetime DEFAULT NULL COMMENT '签收时间',
  `notice_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-草稿 2-已签发 3-已签收 4-已作废）',
  `issue_time` datetime DEFAULT NULL COMMENT '签发',
  `printer_name` varchar(64) DEFAULT NULL COMMENT '最后打印人',
  `print_count` int NOT NULL DEFAULT '0' COMMENT '回执打印次数',
  `last_print_time` datetime DEFAULT NULL COMMENT '最后打印时间',
  `void_reason` varchar(500) DEFAULT NULL COMMENT '作废原因',
  `void_by` varchar(64) DEFAULT NULL COMMENT '作废经办人',
  `void_time` datetime DEFAULT NULL COMMENT '作废时间',
  `sign_status` tinyint NOT NULL DEFAULT '0' COMMENT '电子签名状态（0-未签名 1-已签名 2-签名已作废）',
  `sign_id` bigint DEFAULT NULL COMMENT '当前有效签名ID',
  `signed_time` datetime DEFAULT NULL COMMENT '签名时刻',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_notice_no` (`notice_no`) COMMENT '单号一经生成不复用，软删行不会与新单撞号',
  KEY `idx_notice_admission` (`admission_id`,`notice_status`) COMMENT '按住院回看该患者的全部危重告知',
  KEY `idx_notice_status_time` (`notice_status`,`notify_time`) COMMENT '待签收榜（已签发未签收）一次索引扫',
  KEY `idx_notice_dept` (`dept_id`,`notify_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病危重通知回执';

-- ----------------------------
-- biz_discharge  出院记录
-- ----------------------------
CREATE TABLE `biz_discharge` (
  `discharge_id` bigint NOT NULL COMMENT '出院ID',
  `discharge_no` varchar(32) NOT NULL COMMENT '出院记录号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `discharge_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '出院时间',
  `discharge_doctor_id` bigint DEFAULT NULL COMMENT '出院医生ID',
  `discharge_diagnosis` varchar(500) DEFAULT NULL COMMENT '出院诊断',
  `discharge_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-正常 2-转科 3-自动出院）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `discharge_way` tinyint DEFAULT NULL COMMENT '离院方式（1-医嘱离院 2-医嘱转院 3-医嘱转社区 4-非医嘱离院 5-死亡 9-其他）',
  `discharge_diagnosis_code` varchar(32) DEFAULT NULL COMMENT '出院诊断ICD编码',
  `death_flag` tinyint DEFAULT '0' COMMENT '死亡标志（0-否 1-是）',
  `discharge_summary` varchar(1000) DEFAULT NULL COMMENT '出院小结 / 出院带药医嘱',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`discharge_id`),
  UNIQUE KEY `uk_discharge_no` (`discharge_no`),
  KEY `idx_admission_id` (`admission_id`),
  KEY `idx_discharge_time` (`discharge_time`),
  KEY `idx_dis_admission` (`admission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='出院记录';

-- ----------------------------
-- biz_discharge_drug  出院带药单
-- ----------------------------
CREATE TABLE `biz_discharge_drug` (
  `id` bigint NOT NULL COMMENT '带药单ID',
  `order_no` varchar(32) NOT NULL COMMENT '带药单号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名',
  `drug_id` bigint DEFAULT NULL COMMENT '药品ID',
  `drug_name` varchar(128) NOT NULL COMMENT '药品名称',
  `spec` varchar(64) DEFAULT NULL COMMENT '规格',
  `dosage` varchar(64) DEFAULT NULL COMMENT '每次剂量/用法用量描述',
  `unit` varchar(32) DEFAULT NULL COMMENT '单位',
  `quantity` decimal(10,2) NOT NULL COMMENT '带药数量',
  `usage_text` varchar(200) DEFAULT NULL COMMENT '用药医嘱',
  `days` int DEFAULT NULL COMMENT '用药天数',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `dispense_status` tinyint NOT NULL DEFAULT '1' COMMENT '发药状态（1-待发药 2-已发药）',
  `dispense_by` bigint DEFAULT NULL COMMENT '发药人（员工ID）',
  `dispense_name` varchar(50) DEFAULT NULL COMMENT '发药人姓名',
  `dispense_time` datetime DEFAULT NULL COMMENT '发药时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_discharge_drug_no` (`order_no`),
  KEY `idx_bdd_admission` (`admission_id`),
  KEY `idx_bdd_patient` (`patient_id`),
  KEY `idx_bdd_dispense` (`dispense_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='出院带药单';

-- ----------------------------
-- biz_consultation  会诊申请记录
-- ----------------------------
CREATE TABLE `biz_consultation` (
  `consultation_id` bigint NOT NULL COMMENT '会诊ID',
  `consultation_no` varchar(32) NOT NULL COMMENT '会诊编号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `visit_id` bigint DEFAULT NULL COMMENT '就诊次ID',
  `admission_id` bigint DEFAULT NULL COMMENT '入院ID',
  `from_dept_id` bigint NOT NULL COMMENT '申请科室ID',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `apply_doctor_name` varchar(64) DEFAULT NULL COMMENT '申请医生姓名（快照）',
  `to_dept_id` bigint NOT NULL COMMENT '会诊科室ID',
  `consult_type` tinyint NOT NULL DEFAULT '2' COMMENT '会诊范围（1-科内 2-科间 3-全院）',
  `consult_category` tinyint NOT NULL DEFAULT '1' COMMENT '会诊类别（1-普通科间 2-营养 3-药学 4-其他）',
  `is_urgent` tinyint NOT NULL DEFAULT '0' COMMENT '是否急会诊（0-普通 1-急会诊）',
  `reason` varchar(500) DEFAULT NULL COMMENT '会诊理由',
  `doctor_id` bigint NOT NULL COMMENT '会诊医生ID',
  `apply_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  `consult_time` datetime DEFAULT NULL COMMENT '会诊时间',
  `consult_status` tinyint NOT NULL COMMENT '会诊状态（0-待应答 1-已完成 2-已取消 3-已应答）',
  `accept_time` datetime DEFAULT NULL COMMENT '会诊方接诊时间',
  `accept_doctor_id` bigint DEFAULT NULL COMMENT '接诊医生ID（员工ID）',
  `accept_doctor_name` varchar(64) DEFAULT NULL COMMENT '接诊医生姓名（快照）',
  `finish_time` datetime DEFAULT NULL COMMENT '会诊完成时间',
  `record_id` bigint DEFAULT NULL COMMENT '回写的住院病历ID',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `conclusion` varchar(1000) DEFAULT NULL COMMENT '会诊结论',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`consultation_id`),
  UNIQUE KEY `uk_consultation_no` (`consultation_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_apply_time` (`apply_time`),
  KEY `idx_consult_admission` (`admission_id`,`consult_status`),
  KEY `idx_consult_status` (`consult_status`,`to_dept_id`),
  KEY `idx_consult_category` (`consult_category`,`consult_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='会诊申请记录';

-- ----------------------------
-- biz_bed_wait  等床队列
-- ----------------------------
CREATE TABLE `biz_bed_wait` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `wait_no` varchar(32) NOT NULL COMMENT '等待号',
  `admission_order_id` bigint DEFAULT NULL COMMENT '来源住院证ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `phone` varchar(20) DEFAULT NULL COMMENT '联系电话（快照）',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '拟收治科室ID',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '拟收治科室名称（快照）',
  `expect_ward_id` bigint DEFAULT NULL COMMENT '期望病区ID',
  `bed_type` varchar(32) NOT NULL DEFAULT 'normal' COMMENT '需求床型',
  `priority` tinyint NOT NULL DEFAULT '1' COMMENT '优先级（1-普通 2-急 3-危重）',
  `gender_limit` tinyint NOT NULL DEFAULT '0' COMMENT '性别限制（0-不限 1-限男床 2-限女床）',
  `isolation_flag` tinyint NOT NULL DEFAULT '0' COMMENT '隔离需求（0-否 1-是）',
  `expect_admit_date` date DEFAULT NULL COMMENT '预计入院日期',
  `diagnosis_name` varchar(200) DEFAULT NULL COMMENT '拟诊名称（快照）',
  `wait_status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0-等待中 1-已安排床位 2-已收治 3-已取消）',
  `register_time` datetime NOT NULL COMMENT '登记排队时间',
  `assigned_bed_id` bigint DEFAULT NULL COMMENT '已安排的床位ID',
  `assigned_bed_no` varchar(16) DEFAULT NULL COMMENT '已安排床位号（快照）',
  `assigned_ward_id` bigint DEFAULT NULL COMMENT '已安排床位所在病区ID',
  `assigned_ward_name` varchar(64) DEFAULT NULL COMMENT '已安排病区名称（快照）',
  `assigned_dept_id` bigint DEFAULT NULL COMMENT '已安排床位所属科室ID',
  `assigned_dept_name` varchar(100) DEFAULT NULL COMMENT '已安排床位所属科室名称（快照）',
  `assigned_time` datetime DEFAULT NULL COMMENT '安排床位时间',
  `assigned_by` varchar(64) DEFAULT NULL COMMENT '安排人',
  `admission_id` bigint DEFAULT NULL COMMENT '收治后回填的入院ID',
  `admit_time` datetime DEFAULT NULL COMMENT '实际收治时间',
  `cancel_reason` varchar(200) DEFAULT NULL COMMENT '取消原因',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bed_wait_no` (`wait_no`),
  UNIQUE KEY `uk_bed_wait_order` (`admission_order_id`),
  KEY `idx_bed_wait_status` (`wait_status`,`priority`,`register_time`),
  KEY `idx_bed_wait_patient` (`patient_id`,`wait_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='等床队列';

-- ----------------------------
-- biz_bed_allocate  床位调配台账
-- ----------------------------
CREATE TABLE `biz_bed_allocate` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `allocate_no` varchar(32) NOT NULL COMMENT '调配单号',
  `bed_id` bigint NOT NULL COMMENT '床位ID',
  `bed_no` varchar(16) DEFAULT NULL COMMENT '床位号（快照）',
  `ward_id` bigint DEFAULT NULL COMMENT '病区ID（快照）',
  `ward_name` varchar(64) DEFAULT NULL COMMENT '病区名称（快照）',
  `own_dept_id` bigint DEFAULT NULL COMMENT '床位归属科室ID',
  `own_dept_name` varchar(100) DEFAULT NULL COMMENT '床位归属科室名称（快照）',
  `use_dept_id` bigint DEFAULT NULL COMMENT '实际使用科室ID',
  `use_dept_name` varchar(100) DEFAULT NULL COMMENT '实际使用科室名称（快照）',
  `wait_id` bigint DEFAULT NULL COMMENT '来源等床记录ID',
  `patient_id` bigint DEFAULT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `alloc_type` tinyint NOT NULL DEFAULT '1' COMMENT '调配类型（1-本科室预留 2-跨科调配 3-急诊占床）',
  `alloc_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-已预留 2-已转入院 3-已释放 4-已作废）',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(50) DEFAULT NULL COMMENT '操作人姓名（快照）',
  `operate_time` datetime NOT NULL COMMENT '操作时间',
  `release_time` datetime DEFAULT NULL COMMENT '释放时间',
  `release_reason` varchar(200) DEFAULT NULL COMMENT '释放/作废原因',
  `admission_id` bigint DEFAULT NULL COMMENT '转入院后的入院ID',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bed_allocate_no` (`allocate_no`),
  KEY `idx_bed_allocate_bed` (`bed_id`,`alloc_status`),
  KEY `idx_bed_allocate_wait` (`wait_id`,`alloc_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='床位调配台账';
