-- 领域：11-病历质控与病案（归档·首页·编码·签名）
-- 库：hn_biz_his    表数：15
-- 说明：DDL 快照（由线上库 SHOW CREATE TABLE 导出，无 DROP / 无数据）。建表语句彼此独立，不含外键约束。

-- ----------------------------
-- biz_inpatient_record  住院病历文书
-- ----------------------------
CREATE TABLE `biz_inpatient_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '病历文书号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（快照）（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `age_unit` tinyint DEFAULT NULL COMMENT '年龄单位（快照）（1-岁 2-月 3-天）',
  `dept_id` bigint DEFAULT NULL COMMENT '科室ID',
  `dept_name` varchar(64) DEFAULT NULL COMMENT '科室名称（快照）',
  `ward_id` bigint DEFAULT NULL COMMENT '病区ID',
  `ward_name` varchar(64) DEFAULT NULL COMMENT '病区名称（快照）',
  `bed_no` varchar(32) DEFAULT NULL COMMENT '床号（快照）',
  `record_type` tinyint NOT NULL COMMENT '文书类型',
  `record_title` varchar(200) DEFAULT NULL COMMENT '文书标题',
  `record_time` datetime NOT NULL COMMENT '记录时间',
  `chief_complaint` varchar(500) DEFAULT NULL COMMENT '主诉',
  `present_illness` text COMMENT '现病史',
  `past_history` text COMMENT '既往史',
  `personal_history` text COMMENT '个人史（含婚育、烟酒、职业）',
  `family_history` text COMMENT '家族史',
  `allergy_history` varchar(500) DEFAULT NULL COMMENT '过敏史',
  `temperature` decimal(4,1) DEFAULT NULL COMMENT '体温（℃）',
  `pulse` int DEFAULT NULL COMMENT '脉搏（次/分）',
  `respiration` int DEFAULT NULL COMMENT '呼吸（次/分）',
  `systolic_pressure` int DEFAULT NULL COMMENT '收缩压（mmHg）',
  `diastolic_pressure` int DEFAULT NULL COMMENT '舒张压（mmHg）',
  `height` decimal(5,1) DEFAULT NULL COMMENT '身高（cm）',
  `weight` decimal(5,1) DEFAULT NULL COMMENT '体重（kg）',
  `general_condition` varchar(500) DEFAULT NULL COMMENT '一般情况（神志/发育/营养/体位/面容）',
  `skin_mucosa` varchar(500) DEFAULT NULL COMMENT '皮肤黏膜',
  `head_neck` varchar(500) DEFAULT NULL COMMENT '头颈部',
  `chest_lung` varchar(500) DEFAULT NULL COMMENT '胸部及肺',
  `heart` varchar(500) DEFAULT NULL COMMENT '心脏',
  `abdomen` varchar(500) DEFAULT NULL COMMENT '腹部',
  `spine_limbs` varchar(500) DEFAULT NULL COMMENT '脊柱四肢',
  `nervous_system` varchar(500) DEFAULT NULL COMMENT '神经系统',
  `specialist_exam` text COMMENT '专科检查',
  `auxiliary_exam` text COMMENT '辅助检查',
  `diagnosis_name` varchar(500) DEFAULT NULL COMMENT '诊断名称',
  `diagnosis_code` varchar(100) DEFAULT NULL COMMENT '诊断编码',
  `treatment_plan` text COMMENT '诊疗计划 / 处理意见',
  `course_note` text COMMENT '病程记录正文',
  `record_status` tinyint NOT NULL DEFAULT '1' COMMENT '文书状态（1-草稿 2-已提交 3-已归档）',
  `doctor_id` bigint DEFAULT NULL COMMENT '书写医生ID',
  `doctor_name` varchar(64) DEFAULT NULL COMMENT '书写医生姓名',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `archive_time` datetime DEFAULT NULL COMMENT '归档时间',
  `archive_by` bigint DEFAULT NULL COMMENT '归档人ID（员工ID）',
  `archive_by_name` varchar(64) DEFAULT NULL COMMENT '归档人姓名',
  `sign_status` tinyint NOT NULL DEFAULT '0' COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint DEFAULT NULL COMMENT '当前有效签名ID',
  `signed_time` datetime DEFAULT NULL COMMENT '最近一次签名时刻',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_ir_admission` (`admission_id`,`record_type`,`record_status`),
  KEY `idx_ir_no` (`record_no`),
  KEY `idx_ir_patient` (`patient_id`,`record_time`),
  KEY `idx_ipr_sign` (`sign_status`,`record_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='住院病历文书';

-- ----------------------------
-- biz_inpatient_record_log  住院文书修改日志
-- ----------------------------
CREATE TABLE `biz_inpatient_record_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `doc_type` tinyint NOT NULL COMMENT '单据类型（1-住院病历文书 2-护理文书）',
  `record_id` bigint NOT NULL COMMENT '单据ID',
  `record_no` varchar(50) DEFAULT NULL COMMENT '单据号',
  `record_type` tinyint DEFAULT NULL COMMENT '文书类型码',
  `user_id` bigint DEFAULT NULL COMMENT '操作人ID（员工ID）',
  `user_name` varchar(64) DEFAULT NULL COMMENT '操作人姓名',
  `operation` varchar(50) DEFAULT NULL COMMENT '操作',
  `field_name` varchar(100) DEFAULT NULL COMMENT '变更字段',
  `old_value` text COMMENT '变更前值',
  `new_value` text COMMENT '变更后值',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_irl_record` (`doc_type`,`record_id`),
  KEY `idx_irl_no` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='住院文书修改日志';

-- ----------------------------
-- biz_medical_record_archive  病历归档
-- ----------------------------
CREATE TABLE `biz_medical_record_archive` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `archive_no` varchar(32) NOT NULL COMMENT '归档编号',
  `record_id` bigint NOT NULL COMMENT '病历ID',
  `record_no` varchar(32) DEFAULT NULL COMMENT '病历号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名',
  `regist_id` bigint DEFAULT NULL COMMENT '挂号ID',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期',
  `dept_id` bigint DEFAULT NULL COMMENT '科室ID',
  `dept_name` varchar(50) DEFAULT NULL COMMENT '科室名称',
  `doctor_id` bigint DEFAULT NULL COMMENT '医生ID',
  `doctor_name` varchar(50) DEFAULT NULL COMMENT '医生姓名',
  `diagnosis` varchar(500) DEFAULT NULL COMMENT '诊断',
  `archive_status` tinyint NOT NULL DEFAULT '1' COMMENT '归档状态（1-待归档 2-已归档 3-已封存）',
  `archive_time` datetime DEFAULT NULL COMMENT '归档时间',
  `seal_time` datetime DEFAULT NULL COMMENT '封存时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_archive_no` (`archive_no`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_archive_status` (`archive_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病历归档';

-- ----------------------------
-- biz_record_qc_flow  病历三级质控流转单
-- ----------------------------
CREATE TABLE `biz_record_qc_flow` (
  `id` bigint NOT NULL COMMENT '主键',
  `flow_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '流转单号',
  `record_id` bigint NOT NULL COMMENT '病历ID',
  `record_source` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OUTPATIENT' COMMENT '病历来源',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '患者姓名',
  `dept_id` bigint DEFAULT NULL COMMENT '病历所属科室ID',
  `dept_name` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '病历所属科室名称',
  `flow_status` tinyint NOT NULL DEFAULT '1' COMMENT '流转状态（1-科级待审 2-病案室待审 3-医务处待审 4-终审通过 5-整改中）',
  `current_level` tinyint NOT NULL DEFAULT '1' COMMENT '当前停留级（1-科级 2-病案室 3-医务处）',
  `return_level` tinyint DEFAULT NULL COMMENT '最近一次退回发生级',
  `return_reason` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '最近一次退回的缺陷明细',
  `return_requirement` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '最近一次退回的整改要求',
  `return_deadline` date DEFAULT NULL COMMENT '整改期限',
  `grade` tinyint DEFAULT NULL COMMENT '终审定级（1-甲级 2-乙级 3-丙级）',
  `final_score` int DEFAULT NULL COMMENT '终审评分',
  `final_opinion` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '终审意见',
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` tinyint NOT NULL DEFAULT '0',
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_qc_flow_no` (`flow_no`),
  KEY `idx_qc_flow_record` (`record_id`),
  KEY `idx_qc_flow_status` (`flow_status`,`current_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='病历三级质控流转单';

-- ----------------------------
-- biz_record_qc_flow_action  质控流转动作时间线
-- ----------------------------
CREATE TABLE `biz_record_qc_flow_action` (
  `id` bigint NOT NULL COMMENT '主键',
  `flow_id` bigint NOT NULL COMMENT '流转单ID',
  `level` tinyint NOT NULL COMMENT '动作发生级（1-科级 2-病案室 3-医务处）',
  `action` tinyint NOT NULL COMMENT '动作（1-发起送审 2-审核通过 3-退回整改 4-整改提交 5-终审通过）',
  `opinion` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '审核意见',
  `defect_detail` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '缺陷明细',
  `requirement` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '整改要求',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人员工ID',
  `operator_name` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '操作人姓名',
  `action_time` datetime NOT NULL COMMENT '动作时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `del_flag` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_qc_flow_action_flow` (`flow_id`,`action_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='质控流转动作时间线';

-- ----------------------------
-- biz_quality_control  质控检查记录
-- ----------------------------
CREATE TABLE `biz_quality_control` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `qc_no` varchar(32) NOT NULL COMMENT '质控编号',
  `record_id` bigint NOT NULL COMMENT '病历ID',
  `record_source` varchar(16) NOT NULL DEFAULT 'OUTPATIENT' COMMENT '质控对象来源',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `qc_type` tinyint NOT NULL COMMENT '质控类型（0-综合 1-完整性检查 2-规范性检查 3-逻辑性检查 4-AI内涵质控）',
  `qc_content` varchar(500) NOT NULL COMMENT '检查内容',
  `qc_result` tinyint NOT NULL COMMENT '检查结果（0-不通过 1-通过）',
  `error_count` int DEFAULT '0' COMMENT '错误数量',
  `error_detail` varchar(1000) DEFAULT NULL COMMENT '错误详情',
  `score` int DEFAULT NULL COMMENT '质控得分',
  `severity_max` tinyint DEFAULT NULL COMMENT '最高问题严重度（0-无问题 1-提示 2-重要 3-否决项）',
  `qc_status` tinyint NOT NULL DEFAULT '1' COMMENT '质控状态（1-待处理 2-已处理 3-已忽略）',
  `qc_by` varchar(64) DEFAULT NULL COMMENT '质控人',
  `qc_time` datetime DEFAULT NULL COMMENT '质控时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_qc_no` (`qc_no`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_qc_type` (`qc_type`),
  KEY `idx_qc_status` (`qc_status`),
  KEY `idx_record_source` (`record_source`,`qc_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='质控检查记录';

-- ----------------------------
-- biz_quality_control_issue  质控问题明细
-- ----------------------------
CREATE TABLE `biz_quality_control_issue` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `qc_id` bigint NOT NULL COMMENT '质控单ID',
  `qc_no` varchar(32) NOT NULL COMMENT '质控单号',
  `record_source` varchar(16) NOT NULL COMMENT '病历来源',
  `record_id` bigint NOT NULL COMMENT '病历ID',
  `patient_id` bigint DEFAULT NULL COMMENT '患者ID',
  `rule_code` varchar(16) NOT NULL COMMENT '规则编码',
  `rule_name` varchar(64) NOT NULL COMMENT '规则名称',
  `dimension` tinyint NOT NULL COMMENT '维度（1-完整性 2-规范性 3-逻辑性）',
  `severity` tinyint NOT NULL COMMENT '严重度（1-提示 2-重要 3-否决）',
  `deduct` int NOT NULL DEFAULT '0' COMMENT '扣分',
  `field_name` varchar(64) DEFAULT NULL COMMENT '问题字段',
  `error_detail` varchar(500) DEFAULT NULL COMMENT '问题描述',
  `suggestion` varchar(500) DEFAULT NULL COMMENT '整改建议',
  `evidence` varchar(200) DEFAULT NULL COMMENT '病历原文证据（截断）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_qci_qc_id` (`qc_id`),
  KEY `idx_qci_rule` (`rule_code`),
  KEY `idx_qci_dimension` (`dimension`),
  KEY `idx_qci_record` (`record_source`,`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='质控问题明细';

-- ----------------------------
-- biz_inpatient_summary  住院病案首页
-- ----------------------------
CREATE TABLE `biz_inpatient_summary` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `age_unit` tinyint DEFAULT NULL COMMENT '年龄单位（1-岁 2-月 3-天）',
  `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `admit_dept_id` bigint DEFAULT NULL COMMENT '入院科别ID',
  `admit_dept_name` varchar(64) DEFAULT NULL COMMENT '入院科别名称（快照）',
  `medical_insurance_no` varchar(32) DEFAULT NULL COMMENT '医保卡号',
  `dept_id` bigint DEFAULT NULL COMMENT '科室ID',
  `dept_name` varchar(50) DEFAULT NULL COMMENT '科室名称',
  `ward_id` bigint DEFAULT NULL COMMENT '病区ID',
  `ward_name` varchar(64) DEFAULT NULL COMMENT '病区名称',
  `bed_no` varchar(16) DEFAULT NULL COMMENT '床位号',
  `admit_time` datetime DEFAULT NULL COMMENT '入院时间',
  `discharge_time` datetime DEFAULT NULL COMMENT '出院时间',
  `inpatient_days` int DEFAULT NULL COMMENT '实际住院天数',
  `admit_way` tinyint DEFAULT NULL COMMENT '入院途径（1-门诊 2-急诊 3-转院 4-其他）',
  `discharge_way` tinyint DEFAULT NULL COMMENT '离院方式（1-医嘱离院 2-医嘱转院 3-医嘱转社区 4-非医嘱离院 5-死亡 9-其他）',
  `death_flag` tinyint DEFAULT '0' COMMENT '死亡标志（0-否 1-是）',
  `autopsy_flag` tinyint DEFAULT '0' COMMENT '死亡患者尸检（0-否 1-是）',
  `readmit_31d` tinyint DEFAULT NULL COMMENT '31日内再入院（0-否 1-是）',
  `is_surgery` tinyint DEFAULT '0' COMMENT '是否手术（0-否 1-是）',
  `is_transfusion` tinyint DEFAULT '0' COMMENT '是否输血（0-否 1-是）',
  `is_rescue` tinyint DEFAULT '0' COMMENT '是否抢救（0-否 1-是）',
  `is_critical` tinyint DEFAULT '0' COMMENT '是否危重（0-否 1-是）',
  `main_diagnosis_code` varchar(32) DEFAULT NULL COMMENT '主要诊断编码',
  `main_diagnosis_name` varchar(200) DEFAULT NULL COMMENT '主要诊断名称',
  `total_amount` decimal(12,2) DEFAULT NULL COMMENT '住院总费用',
  `western_drug_amount` decimal(12,2) DEFAULT NULL COMMENT '西药费',
  `chinese_drug_amount` decimal(12,2) DEFAULT NULL COMMENT '中成药费',
  `herbal_amount` decimal(12,2) DEFAULT NULL COMMENT '中药饮片费',
  `exam_amount` decimal(12,2) DEFAULT NULL COMMENT '检查费',
  `lab_amount` decimal(12,2) DEFAULT NULL COMMENT '检验费',
  `treatment_amount` decimal(12,2) DEFAULT NULL COMMENT '治疗费',
  `operation_amount` decimal(12,2) DEFAULT NULL COMMENT '手术费',
  `material_amount` decimal(12,2) DEFAULT NULL COMMENT '耗材费',
  `bed_amount` decimal(12,2) DEFAULT NULL COMMENT '床位费',
  `nursing_amount` decimal(12,2) DEFAULT NULL COMMENT '护理费',
  `other_amount` decimal(12,2) DEFAULT NULL COMMENT '其他费用',
  `summary_status` tinyint NOT NULL DEFAULT '1' COMMENT '首页状态（1-草稿 2-已提交 3-已归档）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_summary_admission` (`admission_id`),
  KEY `idx_summary_patient` (`patient_id`),
  KEY `idx_summary_dept` (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='住院病案首页';

-- ----------------------------
-- biz_inpatient_diagnosis  病案首页诊断明细
-- ----------------------------
CREATE TABLE `biz_inpatient_diagnosis` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `seq_no` int NOT NULL DEFAULT '1' COMMENT '序号',
  `diag_type` tinyint NOT NULL DEFAULT '2' COMMENT '诊断类型（1-主要诊断 2-其他诊断）',
  `icd_code` varchar(32) DEFAULT NULL COMMENT 'ICD-10 编码',
  `icd_name` varchar(200) DEFAULT NULL COMMENT '诊断名称',
  `admit_condition` tinyint DEFAULT NULL COMMENT '入院病情（1-有 2-临床未确定 3-情况不明 4-无）',
  `cc_level` varchar(8) DEFAULT NULL COMMENT '并发症合并症级别',
  `diagnosis_basis` varchar(500) DEFAULT NULL COMMENT '诊断依据',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_ipdiag_admission` (`admission_id`),
  KEY `idx_ipdiag_code` (`icd_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病案首页诊断明细';

-- ----------------------------
-- biz_inpatient_operation  病案首页手术明细
-- ----------------------------
CREATE TABLE `biz_inpatient_operation` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `apply_id` bigint DEFAULT NULL COMMENT '来源手术申请单ID',
  `seq_no` int NOT NULL DEFAULT '1' COMMENT '序号',
  `is_main` tinyint DEFAULT '0' COMMENT '是否主要手术（0-否 1-是）',
  `operation_code` varchar(32) DEFAULT NULL COMMENT '手术操作编码',
  `operation_name` varchar(200) DEFAULT NULL COMMENT '手术操作名称',
  `operation_date` datetime DEFAULT NULL COMMENT '手术日期',
  `operation_level` tinyint DEFAULT NULL COMMENT '手术级别（1-一级 2-二级 3-三级 4-四级）',
  `incision_level` tinyint DEFAULT NULL COMMENT '切口等级（0-0类 1-Ⅰ类 2-Ⅱ类 3-Ⅲ类）',
  `anesthesia_type` tinyint DEFAULT NULL COMMENT '麻醉方式（1-全麻 2-椎管内 3-神经阻滞 4-局麻 5-其他）',
  `surgeon_id` bigint DEFAULT NULL COMMENT '主刀医师ID',
  `surgeon_name` varchar(50) DEFAULT NULL COMMENT '主刀医师姓名',
  `assistant_name` varchar(200) DEFAULT NULL COMMENT '助手姓名',
  `operation_basis` varchar(500) DEFAULT NULL COMMENT '手术依据',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_ipop_admission` (`admission_id`),
  KEY `idx_ipop_code` (`operation_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病案首页手术明细';

-- ----------------------------
-- biz_archive_borrow  病案借阅复印
-- ----------------------------
CREATE TABLE `biz_archive_borrow` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `borrow_no` varchar(32) NOT NULL COMMENT '单号 BR+yyyyMMdd+4位',
  `borrow_type` tinyint NOT NULL COMMENT '类型（1-借阅 2-复印）',
  `archive_id` bigint NOT NULL COMMENT '归档记录 biz_medical_record_archive.id',
  `record_no` varchar(64) DEFAULT NULL COMMENT '病历号（快照）',
  `patient_name` varchar(64) DEFAULT NULL COMMENT '患者姓名（快照）',
  `dept_name` varchar(64) DEFAULT NULL COMMENT '病历所属科室（快照）',
  `applicant_id` bigint NOT NULL COMMENT '申请人员工ID',
  `applicant_name` varchar(64) DEFAULT NULL COMMENT '申请人姓名（快照）',
  `purpose` varchar(500) NOT NULL COMMENT '借阅/复印用途（病历讨论/医保核查/司法取证/科研等）',
  `expect_return_date` date DEFAULT NULL COMMENT '应归还日期',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-待审核 2-已借出 3-已归还 4-已拒绝 5-已复印）',
  `audit_by_id` bigint DEFAULT NULL COMMENT '审核人员工ID',
  `audit_by_name` varchar(64) DEFAULT NULL COMMENT '审核人姓名（快照）',
  `audit_remark` varchar(500) DEFAULT NULL COMMENT '审核意见',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `lend_time` datetime DEFAULT NULL COMMENT '借出时间',
  `return_time` datetime DEFAULT NULL COMMENT '归还时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_borrow_no` (`borrow_no`),
  KEY `idx_status` (`status`),
  KEY `idx_archive` (`archive_id`),
  KEY `idx_applicant` (`applicant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病案借阅复印';

-- ----------------------------
-- biz_archive_code_task  病案编码任务池
-- ----------------------------
CREATE TABLE `biz_archive_code_task` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `task_no` varchar(32) NOT NULL COMMENT '任务号 CT+yyyyMMdd+4位',
  `archive_id` bigint NOT NULL COMMENT '归档记录 biz_medical_record_archive.id',
  `record_no` varchar(64) DEFAULT NULL COMMENT '病历号（快照）',
  `patient_name` varchar(64) DEFAULT NULL COMMENT '患者姓名（快照）',
  `dept_name` varchar(64) DEFAULT NULL COMMENT '病历所属科室（快照）',
  `diagnosis` varchar(500) DEFAULT NULL COMMENT '病历诊断',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-待编码 2-已提交 3-已完成 4-已退修）',
  `coder_id` bigint DEFAULT NULL COMMENT '编码人员工ID',
  `coder_name` varchar(64) DEFAULT NULL COMMENT '编码员姓名（快照）',
  `assign_time` datetime DEFAULT NULL COMMENT '分配时间',
  `main_icd_code` varchar(20) DEFAULT NULL COMMENT '主诊断 ICD-10 编码',
  `main_icd_name` varchar(200) DEFAULT NULL COMMENT '主诊断名称',
  `other_icd_text` varchar(500) DEFAULT NULL COMMENT '其他诊断/手术 ICD',
  `submit_time` datetime DEFAULT NULL COMMENT '提交编码时间',
  `audit_by_id` bigint DEFAULT NULL COMMENT '审核人员工ID',
  `audit_by_name` varchar(64) DEFAULT NULL COMMENT '审核人姓名（快照）',
  `audit_remark` varchar(500) DEFAULT NULL COMMENT '审核意见',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `return_count` int NOT NULL DEFAULT '0' COMMENT '累计退修次数',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`),
  KEY `idx_status` (`status`),
  KEY `idx_archive` (`archive_id`),
  KEY `idx_coder` (`coder_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病案编码任务池';

-- ----------------------------
-- biz_stat_report  病案统计上报台账
-- ----------------------------
CREATE TABLE `biz_stat_report` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `report_no` varchar(32) NOT NULL COMMENT '上报单号',
  `report_type` tinyint NOT NULL COMMENT '报表类型（1-卫统年报 2-出院患者统计月报 3-手术工作量专项报表）',
  `period_type` tinyint NOT NULL DEFAULT '2' COMMENT '期间类型（1-月报 2-年报）',
  `period_value` varchar(10) NOT NULL COMMENT '期间值',
  `dept_id` bigint DEFAULT NULL COMMENT '科室ID',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '科室名称',
  `title` varchar(200) NOT NULL COMMENT '报表标题',
  `discharge_count` int NOT NULL DEFAULT '0' COMMENT '摘要-出院患者例数',
  `death_count` int NOT NULL DEFAULT '0' COMMENT '摘要-死亡例数',
  `operation_count` int NOT NULL DEFAULT '0' COMMENT '摘要-手术台次',
  `level3up_count` int NOT NULL DEFAULT '0' COMMENT '摘要-三级及以上手术台次',
  `avg_los_days` decimal(6,1) NOT NULL DEFAULT '0.0' COMMENT '摘要-平均住院日',
  `total_amount` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '摘要-结算总金额',
  `payload` mediumtext NOT NULL COMMENT '上报报文',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0-草稿 1-已报出 2-已作废）',
  `generate_time` datetime DEFAULT NULL COMMENT '报文生成时间',
  `submit_time` datetime DEFAULT NULL COMMENT '报出时间',
  `void_time` datetime DEFAULT NULL COMMENT '作废时间',
  `void_reason` varchar(200) DEFAULT NULL COMMENT '作废原因',
  `operator_name` varchar(50) DEFAULT NULL COMMENT '生成人',
  `submit_by_name` varchar(50) DEFAULT NULL COMMENT '报出人',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stat_report_no` (`report_no`),
  KEY `idx_stat_report_type_period` (`report_type`,`period_value`),
  KEY `idx_stat_report_dept` (`dept_id`),
  KEY `idx_stat_report_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病案统计上报台账';

-- ----------------------------
-- biz_drg_sim_result  DRG 分组模拟结果
-- ----------------------------
CREATE TABLE `biz_drg_sim_result` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `summary_id` bigint NOT NULL COMMENT '病案首页ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `main_diag_code` varchar(32) DEFAULT NULL COMMENT '分组时使用的主诊断编码（快照）',
  `main_diag_name` varchar(200) DEFAULT NULL COMMENT '主诊断名称（快照）',
  `is_surgery` tinyint NOT NULL DEFAULT '0' COMMENT '是否手术',
  `inpatient_days` int DEFAULT NULL COMMENT '住院天数',
  `drg_code` varchar(32) NOT NULL COMMENT '入组编码',
  `drg_name` varchar(200) DEFAULT NULL COMMENT '组名称',
  `mdc_code` varchar(8) DEFAULT NULL COMMENT 'MDC 大类',
  `weight` decimal(10,4) DEFAULT NULL COMMENT '权重 RW',
  `pay_standard` decimal(10,2) DEFAULT NULL COMMENT '病组支付标准（元）',
  `actual_amount` decimal(10,2) DEFAULT NULL COMMENT '实际住院费用',
  `profit_amount` decimal(10,2) DEFAULT NULL COMMENT '盈亏 = 支付标准 - 实际费用',
  `sim_status` tinyint NOT NULL DEFAULT '1' COMMENT '结果（1-已入组 2-未入组）',
  `rule_note` varchar(300) DEFAULT NULL COMMENT '命中规则说明',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_summary` (`summary_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='DRG 分组模拟结果';

-- ----------------------------
-- biz_emr_signature  电子签名证据
-- ----------------------------
CREATE TABLE `biz_emr_signature` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `sign_no` varchar(32) NOT NULL COMMENT '签名流水号',
  `biz_type` tinyint NOT NULL COMMENT '签名对象类型',
  `biz_id` bigint NOT NULL COMMENT '签名对象ID',
  `biz_no` varchar(64) DEFAULT NULL COMMENT '对象单号（快照）',
  `patient_id` bigint DEFAULT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `dept_id` bigint DEFAULT NULL COMMENT '对象所属科室ID（快照）',
  `dept_name` varchar(64) DEFAULT NULL COMMENT '对象所属科室名称（快照）',
  `sign_scene` tinyint NOT NULL COMMENT '签名场景',
  `chain_no` int NOT NULL DEFAULT '1' COMMENT '同对象第几次签名',
  `prev_sign_id` bigint DEFAULT NULL COMMENT '前一次签名ID',
  `prev_digest` varchar(128) DEFAULT NULL COMMENT '前一次签名摘要',
  `signer_id` bigint NOT NULL COMMENT '签名人员工ID',
  `signer_name` varchar(64) NOT NULL COMMENT '签名人姓名（快照）',
  `signer_dept_id` bigint DEFAULT NULL COMMENT '签名人科室ID（快照）',
  `signer_dept_name` varchar(64) DEFAULT NULL COMMENT '签名人科室名称（快照）',
  `signer_title` varchar(64) DEFAULT NULL COMMENT '签名人职称',
  `cert_id` bigint NOT NULL COMMENT '所用证书ID',
  `cert_no` varchar(32) NOT NULL COMMENT '所用证书编号（快照）',
  `digest_algo` varchar(16) NOT NULL COMMENT '摘要算法',
  `sign_algo` varchar(32) NOT NULL COMMENT '签名算法',
  `content_digest` varchar(128) NOT NULL COMMENT '被签内容摘要',
  `sign_value` text NOT NULL COMMENT '签名值',
  `content_snapshot` mediumtext COMMENT '被签内容快照',
  `signed_time` datetime NOT NULL COMMENT '签名时刻',
  `time_source` tinyint NOT NULL DEFAULT '1' COMMENT '时间来源（1-本机时钟 2-院内授时服务器 3-第三方TSA）',
  `tsa_serial` varchar(64) DEFAULT NULL COMMENT '第三方时间戳序列号',
  `tsa_time` datetime DEFAULT NULL COMMENT 'TSA 授时时刻',
  `tsa_token` text COMMENT '时间戳令牌',
  `sign_status` tinyint NOT NULL DEFAULT '1' COMMENT '签名状态（1-有效 2-已作废）',
  `verify_status` tinyint NOT NULL DEFAULT '0' COMMENT '最近一次验签结果（0-未校验 1-通过 2-失败）',
  `verify_time` datetime DEFAULT NULL COMMENT '最近一次验签时间',
  `verify_count` int NOT NULL DEFAULT '0' COMMENT '累计验签次数',
  `invalid_reason` varchar(200) DEFAULT NULL COMMENT '作废原因',
  `invalid_time` datetime DEFAULT NULL COMMENT '作废时间',
  `invalid_by` bigint DEFAULT NULL COMMENT '作废操作人员工ID',
  `invalid_by_name` varchar(64) DEFAULT NULL COMMENT '作废操作人姓名',
  `client_ip` varchar(64) DEFAULT NULL COMMENT '签名来源 IP（留痕）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sign_no` (`sign_no`),
  KEY `idx_sig_biz` (`biz_type`,`biz_id`,`chain_no`),
  KEY `idx_sig_signer` (`signer_id`,`signed_time`),
  KEY `idx_sig_status` (`sign_status`,`verify_status`),
  KEY `idx_sig_time` (`signed_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='电子签名证据';
