-- 领域：12-检验LIS（申请·结果·质控·室间质评）
-- 库：hn_biz_his    表数：11
-- 说明：DDL 快照（由线上库 SHOW CREATE TABLE 导出，无 DROP / 无数据）。建表语句彼此独立，不含外键约束。

-- ----------------------------
-- biz_laboratory_template  检验申请模板
-- ----------------------------
CREATE TABLE `biz_laboratory_template` (
  `id` bigint NOT NULL,
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `laboratory_item_id` bigint NOT NULL COMMENT '检验项目ID',
  `laboratory_item_code` varchar(32) NOT NULL COMMENT '检验项目编码',
  `laboratory_item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `sample_type` varchar(50) DEFAULT NULL COMMENT '标本类型',
  `inspection_purpose` varchar(200) DEFAULT NULL COMMENT '检验目的',
  `is_emergency` tinyint DEFAULT '0' COMMENT '是否急诊（0-否 1-是）',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_id` (`doctor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检验申请模板';

-- ----------------------------
-- biz_laboratory_apply  检验申请单
-- ----------------------------
CREATE TABLE `biz_laboratory_apply` (
  `id` bigint NOT NULL,
  `apply_no` varchar(32) NOT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别',
  `age` int DEFAULT NULL COMMENT '年龄',
  `regist_id` bigint NOT NULL COMMENT '挂号ID',
  `record_id` bigint DEFAULT NULL COMMENT '病历ID',
  `record_no` varchar(32) DEFAULT NULL COMMENT '病历号',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `dept_id` bigint NOT NULL COMMENT '申请科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '申请科室名称',
  `doctor_id` bigint NOT NULL COMMENT '申请医生ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '申请医生姓名',
  `laboratory_item_id` bigint NOT NULL COMMENT '检验项目ID',
  `laboratory_item_code` varchar(32) NOT NULL COMMENT '检验项目编码',
  `laboratory_item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `laboratory_dept_id` bigint DEFAULT NULL COMMENT '检验科室ID',
  `laboratory_dept_name` varchar(100) DEFAULT NULL COMMENT '检验科室名称',
  `specimen_type` varchar(50) NOT NULL COMMENT '标本类型',
  `specimen_source` varchar(100) DEFAULT NULL COMMENT '标本来源',
  `laboratory_purpose` varchar(500) DEFAULT NULL COMMENT '检验目的',
  `clinical_diagnosis` varchar(500) DEFAULT NULL COMMENT '临床诊断',
  `disease_summary` text COMMENT '病史摘要',
  `is_fasting` tinyint DEFAULT '0' COMMENT '是否空腹（0-否 1-是）',
  `is_emergency` tinyint DEFAULT '0' COMMENT '是否急诊（0-否 1-是）',
  `price` decimal(10,2) DEFAULT '0.00' COMMENT '检验费用',
  `apply_status` tinyint DEFAULT '1' COMMENT '申请状态（1-已提交 2-已缴费 6-已取消）',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `sign_status` tinyint NOT NULL DEFAULT '0' COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint DEFAULT NULL COMMENT '当前有效签名ID',
  `signed_time` datetime DEFAULT NULL COMMENT '最近一次签名时刻',
  `pay_time` datetime DEFAULT NULL COMMENT '缴费时间',
  `sample_time` datetime DEFAULT NULL COMMENT '采样时间',
  `sample_by` varchar(64) DEFAULT NULL COMMENT '采样人',
  `complete_time` datetime DEFAULT NULL COMMENT '完成时间',
  `report_id` bigint DEFAULT NULL COMMENT '报告ID',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(200) DEFAULT NULL COMMENT '取消原因',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_no` (`apply_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_regist_id` (`regist_id`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_visit_date` (`visit_date`),
  KEY `idx_doctor_id` (`doctor_id`),
  KEY `idx_apply_status` (`apply_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检验申请单';

-- ----------------------------
-- biz_laboratory_record  检验记录
-- ----------------------------
CREATE TABLE `biz_laboratory_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '检验记录号（唯一）',
  `apply_id` bigint NOT NULL COMMENT '申请单ID',
  `apply_no` varchar(32) NOT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号码',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '申请科室',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) DEFAULT NULL COMMENT '申请医生',
  `laboratory_item_id` bigint NOT NULL COMMENT '检验项目ID',
  `laboratory_item_code` varchar(32) NOT NULL COMMENT '检验项目编码',
  `laboratory_item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `laboratory_dept_id` bigint DEFAULT NULL COMMENT '检验科室ID',
  `laboratory_dept_name` varchar(100) DEFAULT NULL COMMENT '检验科室名称',
  `specimen_type` varchar(50) NOT NULL COMMENT '标本类型（血液、尿液、粪便等）',
  `specimen_no` varchar(50) DEFAULT NULL COMMENT '标本编号',
  `specimen_status` tinyint DEFAULT '1' COMMENT '标本状态（1-待采集 2-已采集 3-已接收 4-检测中 5-已完成 6-已退回）',
  `sample_time` datetime DEFAULT NULL COMMENT '采样时间',
  `sample_by` varchar(64) DEFAULT NULL COMMENT '采样人',
  `receive_time` datetime DEFAULT NULL COMMENT '接收时间',
  `receive_by` varchar(64) DEFAULT NULL COMMENT '接收人',
  `execute_time` datetime DEFAULT NULL COMMENT '检测时间',
  `execute_by` varchar(64) DEFAULT NULL COMMENT '检测人',
  `price` decimal(10,2) DEFAULT '0.00' COMMENT '检验费用',
  `diagnosis` text COMMENT '检验结论/诊断',
  `report_sign_id` bigint DEFAULT NULL COMMENT '报告医师签名ID',
  `report_signed_time` datetime DEFAULT NULL COMMENT '报告签名时刻',
  `suggestions` text COMMENT '建议',
  `record_status` tinyint DEFAULT '1' COMMENT '记录状态（1-已登记 2-已采样 3-已接收 4-检测中 5-已出结果 6-已审核 7-已发布 8-已取消）',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核人（初审）',
  `audit_sign_id` bigint DEFAULT NULL COMMENT '审核医师签名ID',
  `audit_signed_time` datetime DEFAULT NULL COMMENT '审核签名时刻',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `audit2_by` varchar(64) DEFAULT NULL COMMENT '复审人',
  `audit2_time` datetime DEFAULT NULL COMMENT '复审时间',
  `report_time` datetime DEFAULT NULL COMMENT '报告发布时间',
  `report_by` varchar(64) DEFAULT NULL COMMENT '报告发布人',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(200) DEFAULT NULL COMMENT '取消原因',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`),
  KEY `idx_apply_id` (`apply_id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_laboratory_item_id` (`laboratory_item_id`),
  KEY `idx_laboratory_dept_id` (`laboratory_dept_id`),
  KEY `idx_record_status` (`record_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检验记录';

-- ----------------------------
-- biz_lab_result  检验结果
-- ----------------------------
CREATE TABLE `biz_lab_result` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_id` bigint NOT NULL COMMENT '检验记录ID',
  `record_no` varchar(32) NOT NULL COMMENT '检验记录号',
  `laboratory_item_id` bigint NOT NULL COMMENT '检验项目ID',
  `laboratory_item_code` varchar(32) NOT NULL COMMENT '检验项目编码',
  `laboratory_item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `result_value` varchar(200) DEFAULT NULL COMMENT '检验结果值',
  `result_unit` varchar(50) DEFAULT NULL COMMENT '结果单位',
  `reference_range` varchar(100) DEFAULT NULL COMMENT '参考范围',
  `abnormal_flag` tinyint DEFAULT '0' COMMENT '异常标志（0-正常 1-偏高 2-偏低 3-异常）',
  `abnormal_desc` varchar(200) DEFAULT NULL COMMENT '异常描述',
  `judge_note` varchar(200) DEFAULT NULL COMMENT '异常判定说明',
  `result_type` tinyint DEFAULT '1' COMMENT '结果类型（1-定量 2-定性 3-文字描述）',
  `sort_order` int DEFAULT '0' COMMENT '排序号',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_laboratory_item_id` (`laboratory_item_id`),
  KEY `idx_abnormal_flag` (`abnormal_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检验结果';

-- ----------------------------
-- biz_critical_value  检验危急值
-- ----------------------------
CREATE TABLE `biz_critical_value` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `critical_no` varchar(32) NOT NULL COMMENT '危急值号',
  `record_id` bigint DEFAULT NULL COMMENT '检验记录ID',
  `record_no` varchar(32) DEFAULT NULL COMMENT '检验记录号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `item_code` varchar(32) DEFAULT NULL COMMENT '检验项目编码',
  `item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `result_value` varchar(200) NOT NULL COMMENT '危急值结果值',
  `result_unit` varchar(50) DEFAULT NULL COMMENT '结果单位',
  `reference_range` varchar(100) DEFAULT NULL COMMENT '参考范围',
  `critical_type` tinyint NOT NULL COMMENT '危急值类型（1-偏低 2-偏高）',
  `threshold_text` varchar(100) DEFAULT NULL COMMENT '阈值说明',
  `critical_desc` varchar(300) NOT NULL COMMENT '危急值描述',
  `report_dept_id` bigint DEFAULT NULL COMMENT '报告科室ID',
  `report_dept_name` varchar(100) DEFAULT NULL COMMENT '报告科室',
  `report_by` varchar(64) DEFAULT NULL COMMENT '报告人',
  `report_time` datetime NOT NULL COMMENT '报告时间',
  `deadline_time` datetime DEFAULT NULL COMMENT '处置时限',
  `notify_status` tinyint NOT NULL DEFAULT '0' COMMENT '通知状态（0-未通知 1-已通知）',
  `notify_time` datetime DEFAULT NULL COMMENT '通知时间',
  `escalate_status` tinyint NOT NULL DEFAULT '0' COMMENT '超时升级状态（0-未升级 1-已升级）',
  `escalate_time` datetime DEFAULT NULL COMMENT '升级时间',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '闭环状态（1-待接收 2-已接收 3-已处置 4-已作废）',
  `receive_by` varchar(64) DEFAULT NULL COMMENT '接收人',
  `receive_time` datetime DEFAULT NULL COMMENT '接收时间',
  `handle_by` varchar(64) DEFAULT NULL COMMENT '处置人',
  `handle_time` datetime DEFAULT NULL COMMENT '处置时间',
  `handle_measure` varchar(500) DEFAULT NULL COMMENT '处置措施',
  `source` varchar(16) NOT NULL DEFAULT 'RULE' COMMENT '来源',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_critical_no` (`critical_no`),
  KEY `idx_patient` (`patient_id`,`report_time`),
  KEY `idx_status_time` (`status`,`report_time`),
  KEY `idx_record` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检验危急值';

-- ----------------------------
-- biz_lis_qc_plan  室内质控计划
-- ----------------------------
CREATE TABLE `biz_lis_qc_plan` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_no` varchar(32) NOT NULL COMMENT '质控计划编号',
  `item_id` bigint DEFAULT NULL COMMENT '检验项目ID',
  `item_code` varchar(32) DEFAULT NULL COMMENT '检验项目编码',
  `item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `instrument_no` varchar(50) DEFAULT NULL COMMENT '仪器编号',
  `instrument_name` varchar(100) DEFAULT NULL COMMENT '仪器名称',
  `qc_level` tinyint DEFAULT '2' COMMENT '质控水平（1-低值 2-中值 3-高值）',
  `control_name` varchar(200) DEFAULT NULL COMMENT '质控品名称',
  `control_lot_no` varchar(50) DEFAULT NULL COMMENT '质控品批号',
  `manufacturer` varchar(100) DEFAULT NULL COMMENT '生产厂家',
  `mean_value` decimal(18,4) DEFAULT NULL COMMENT '靶值（均值）',
  `sd_value` decimal(18,4) DEFAULT NULL COMMENT '标准差 SD',
  `cv_limit` decimal(8,2) DEFAULT NULL COMMENT '允许 CV 上限（%）',
  `expire_date` date DEFAULT NULL COMMENT '质控品效期',
  `status` tinyint DEFAULT '1' COMMENT '状态（1-启用 0-停用）',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_no` (`plan_no`),
  KEY `idx_item_code` (`item_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='室内质控计划';

-- ----------------------------
-- biz_lis_qc_record  室内质控记录
-- ----------------------------
CREATE TABLE `biz_lis_qc_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_id` bigint NOT NULL COMMENT '质控计划ID',
  `plan_no` varchar(32) DEFAULT NULL COMMENT '质控计划编号',
  `item_code` varchar(32) DEFAULT NULL COMMENT '检验项目编码',
  `item_name` varchar(200) DEFAULT NULL COMMENT '检验项目名称',
  `instrument_name` varchar(100) DEFAULT NULL COMMENT '仪器名称',
  `qc_level` tinyint DEFAULT NULL COMMENT '质控水平（1-低值 2-中值 3-高值）',
  `qc_date` date DEFAULT NULL COMMENT '质控日期',
  `qc_time` datetime DEFAULT NULL COMMENT '质控时间',
  `result_value` decimal(18,4) DEFAULT NULL COMMENT '质控测定值',
  `z_score` decimal(10,3) DEFAULT NULL COMMENT 'Z 值',
  `status` tinyint DEFAULT '1' COMMENT '质控状态（1-在控 2-警告 3-失控）',
  `violated_rules` varchar(100) DEFAULT NULL COMMENT '命中的 Westgard 规则',
  `operator` varchar(64) DEFAULT NULL COMMENT '操作人',
  `handle_status` tinyint DEFAULT '0' COMMENT '失控处理（0-无需处理 1-待处理 2-已处理）',
  `handle_cause` varchar(500) DEFAULT NULL COMMENT '失控原因分析',
  `handle_measure` varchar(500) DEFAULT NULL COMMENT '纠正措施',
  `handle_by` varchar(64) DEFAULT NULL COMMENT '处理人',
  `handle_time` datetime DEFAULT NULL COMMENT '处理时间',
  `review_by` varchar(64) DEFAULT NULL COMMENT '复核人',
  `review_time` datetime DEFAULT NULL COMMENT '复核时间',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_qc_date` (`qc_date`),
  KEY `idx_status` (`status`),
  KEY `idx_handle_status` (`handle_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='室内质控记录';

-- ----------------------------
-- biz_lis_eqa_plan  室间质评批次
-- ----------------------------
CREATE TABLE `biz_lis_eqa_plan` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_no` varchar(32) NOT NULL COMMENT '质评批次号',
  `plan_year` smallint NOT NULL COMMENT '质评年度',
  `batch_no` tinyint NOT NULL COMMENT '本年度第几批（1-上半年 2-下半年）',
  `org_name` varchar(200) NOT NULL COMMENT '组织方（国家/省/市临床检验中心 或 第三方质评机构）',
  `plan_name` varchar(200) DEFAULT NULL COMMENT '质评计划名称',
  `item_count` int DEFAULT '0' COMMENT '本次参加项目数',
  `sample_count` int DEFAULT '0' COMMENT '本次下发盲样数',
  `receive_date` date DEFAULT NULL COMMENT '盲样接收日期',
  `receive_by` varchar(64) DEFAULT NULL COMMENT '盲样接收人',
  `report_deadline` date DEFAULT NULL COMMENT '结果上报截止日期',
  `return_date` date DEFAULT NULL COMMENT '成绩回报日期',
  `status` tinyint DEFAULT '1' COMMENT '批次状态（1-待收样 2-检测中 3-已上报 4-已回报 5-已归档）',
  `pt_score` decimal(6,2) DEFAULT NULL COMMENT 'PT 得分',
  `pass_flag` tinyint DEFAULT NULL COMMENT '本次是否合格（1-合格 0-不合格）',
  `fail_count` int DEFAULT '0' COMMENT '判定为「不合格」的盲样项数',
  `archive_by` varchar(64) DEFAULT NULL COMMENT '归档人',
  `archive_time` datetime DEFAULT NULL COMMENT '归档时间',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_no` (`plan_no`),
  UNIQUE KEY `uk_year_batch_org` (`plan_year`,`batch_no`,`org_name`),
  KEY `idx_status` (`status`),
  KEY `idx_year` (`plan_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='室间质评批次';

-- ----------------------------
-- biz_lis_eqa_sample  室间质评盲样
-- ----------------------------
CREATE TABLE `biz_lis_eqa_sample` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_id` bigint NOT NULL COMMENT '质评批次ID',
  `plan_no` varchar(32) DEFAULT NULL COMMENT '质评批次号（冗余）',
  `sample_no` varchar(64) NOT NULL COMMENT '盲样编号',
  `sample_seq` tinyint NOT NULL COMMENT '第几个样品',
  `item_id` bigint DEFAULT NULL COMMENT '检验项目ID',
  `item_code` varchar(32) DEFAULT NULL COMMENT '检验项目编码',
  `item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `instrument_name` varchar(100) NOT NULL DEFAULT '' COMMENT '检测仪器',
  `method_name` varchar(100) DEFAULT NULL COMMENT '检测方法学',
  `receive_date` date DEFAULT NULL COMMENT '盲样接收日期',
  `receive_by` varchar(64) DEFAULT NULL COMMENT '盲样接收人',
  `test_value` decimal(18,4) DEFAULT NULL COMMENT '本室测定值',
  `test_by` varchar(64) DEFAULT NULL COMMENT '检测人',
  `test_time` datetime DEFAULT NULL COMMENT '检测时间',
  `overdue_flag` tinyint DEFAULT '0' COMMENT '是否逾期上报',
  `target_value` decimal(18,4) DEFAULT NULL COMMENT '回报靶值/组均值',
  `group_sd` decimal(18,4) DEFAULT NULL COMMENT '回报组标准差',
  `tea` decimal(8,2) DEFAULT NULL COMMENT '允许总误差 TEa（%）',
  `target_min` decimal(18,4) DEFAULT NULL COMMENT '可接受范围下限',
  `target_max` decimal(18,4) DEFAULT NULL COMMENT '可接受范围上限',
  `sdi` decimal(10,3) DEFAULT NULL COMMENT '标准差指数（SDI）',
  `bias_rate` decimal(10,2) DEFAULT NULL COMMENT '偏倚（%）',
  `judge_mode` tinyint DEFAULT '0' COMMENT '判定口径（0-无法判定 1-SDI 2-允许总误差 3-可接受范围）',
  `result_status` tinyint DEFAULT '0' COMMENT '判定结果（0-未判定 1-满意 2-尚可 3-不合格）',
  `status` tinyint DEFAULT '0' COMMENT '流转状态（0-待检测 1-已检测 2-已上报 3-已回报）',
  `handle_status` tinyint DEFAULT '0' COMMENT '整改状态（0-无需整改 1-待整改 2-已整改）',
  `handle_cause` varchar(500) DEFAULT NULL COMMENT '不合格原因分析',
  `handle_measure` varchar(500) DEFAULT NULL COMMENT '纠正措施',
  `handle_by` varchar(64) DEFAULT NULL COMMENT '整改人',
  `handle_time` datetime DEFAULT NULL COMMENT '整改时间',
  `review_by` varchar(64) DEFAULT NULL COMMENT '整改复核人',
  `review_time` datetime DEFAULT NULL COMMENT '复核时间',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sample` (`plan_id`,`sample_seq`,`item_code`,`instrument_name`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_result_status` (`result_status`),
  KEY `idx_handle_status` (`handle_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='室间质评盲样';

-- ----------------------------
-- biz_lis_eqa_compare  室间质评仪器间比对
-- ----------------------------
CREATE TABLE `biz_lis_eqa_compare` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_id` bigint NOT NULL COMMENT '质评批次ID',
  `plan_no` varchar(32) DEFAULT NULL COMMENT '质评批次号（冗余）',
  `item_code` varchar(32) DEFAULT NULL COMMENT '检验项目编码',
  `item_name` varchar(200) DEFAULT NULL COMMENT '检验项目名称',
  `sample_seq` tinyint DEFAULT NULL COMMENT '第几个样品',
  `sample_no` varchar(64) DEFAULT NULL COMMENT '盲样编号',
  `instrument_a` varchar(100) DEFAULT NULL COMMENT 'A 组仪器',
  `method_a` varchar(100) DEFAULT NULL COMMENT 'A 组方法学',
  `value_a` decimal(18,4) DEFAULT NULL COMMENT 'A 组测定值',
  `instrument_b` varchar(100) DEFAULT NULL COMMENT 'B 组仪器',
  `method_b` varchar(100) DEFAULT NULL COMMENT 'B 组方法学',
  `value_b` decimal(18,4) DEFAULT NULL COMMENT 'B 组测定值',
  `diff_value` decimal(18,4) DEFAULT NULL COMMENT '互差绝对值 |A-B|',
  `diff_rate` decimal(10,2) DEFAULT NULL COMMENT '相对互差% = |A-B| /(A+B)',
  `allow_rate` decimal(10,2) DEFAULT NULL COMMENT '允许互差%',
  `allow_source` tinyint DEFAULT '1' COMMENT '允许限来源（1-由该批次 2-无）',
  `status` tinyint DEFAULT '1' COMMENT '比对结论（1-可接受 2-超差）',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_compare` (`plan_id`,`sample_seq`,`item_code`,`instrument_a`,`instrument_b`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='室间质评仪器间比对';

-- ----------------------------
-- sys_lab_plain_item  检验项目白话词典（患者端报告解读的规则层地基，人工维护）
-- ----------------------------
CREATE TABLE `sys_lab_plain_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `group_name` varchar(32) NOT NULL COMMENT '所属分组（血常规/肝功能/肾功能/血糖/血脂/炎症/凝血/心肌/电解质/尿常规/大便）',
  `item_name` varchar(64) NOT NULL COMMENT '检验项目名称（与 biz_lab_result.laboratory_item_name 精确匹配）',
  `plain_name` varchar(64) NOT NULL COMMENT '白话名（如：血色素、坏胆固醇、心肌损伤指标）',
  `what_is_it` varchar(200) NOT NULL COMMENT '这项查什么（给患者看的一句话，不含诊断/用药）',
  `high_text` varchar(200) NOT NULL COMMENT '结果偏高时的白话说明',
  `low_text` varchar(200) NOT NULL COMMENT '结果偏低时的白话说明',
  `status` tinyint DEFAULT '1' COMMENT '状态（0-停用 1-启用）',
  `sort_order` int DEFAULT '0' COMMENT '排序号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_item_name` (`item_name`),
  KEY `idx_group_status` (`group_name`,`status`,`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检验项目白话词典（患者端报告解读的规则层地基，人工维护）';
