-- 领域：13-检查影像与报告（PACS·预约·心电·病理·内镜）
-- 库：hn_biz_his    表数：22
-- 说明：DDL 快照（由线上库 SHOW CREATE TABLE 导出，无 DROP / 无数据）。建表语句彼此独立，不含外键约束。

-- ----------------------------
-- biz_inspection_template  检查申请模板
-- ----------------------------
CREATE TABLE `biz_inspection_template` (
  `id` bigint NOT NULL,
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `inspection_item_id` bigint NOT NULL COMMENT '检查项目ID',
  `inspection_item_code` varchar(32) NOT NULL COMMENT '检查项目编码',
  `inspection_item_name` varchar(200) NOT NULL COMMENT '检查项目名称',
  `body_part` varchar(100) DEFAULT NULL COMMENT '检查部位',
  `inspection_purpose` varchar(200) DEFAULT NULL COMMENT '检查目的',
  `is_emergency` tinyint DEFAULT '0' COMMENT '是否急诊（0-否 1-是）',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_doctor_id` (`doctor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检查申请模板';

-- ----------------------------
-- biz_inspection_apply  检查申请单
-- ----------------------------
CREATE TABLE `biz_inspection_apply` (
  `id` bigint NOT NULL,
  `apply_no` varchar(32) NOT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别',
  `age` int DEFAULT NULL COMMENT '年龄',
  `regist_id` bigint NOT NULL COMMENT '挂号ID',
  `record_id` bigint DEFAULT NULL COMMENT '病历ID',
  `record_no` varchar(32) DEFAULT NULL COMMENT '病历号',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `dept_id` bigint NOT NULL COMMENT '申请科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '申请科室名称',
  `doctor_id` bigint NOT NULL COMMENT '申请医生ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '申请医生姓名',
  `inspection_item_id` bigint NOT NULL COMMENT '检查项目ID',
  `inspection_item_code` varchar(32) NOT NULL COMMENT '检查项目编码',
  `inspection_item_name` varchar(200) NOT NULL COMMENT '检查项目名称',
  `inspection_dept_id` bigint DEFAULT NULL COMMENT '检查科室ID',
  `inspection_dept_name` varchar(100) DEFAULT NULL COMMENT '检查科室名称',
  `body_part` varchar(200) DEFAULT NULL COMMENT '检查部位',
  `inspection_purpose` varchar(500) DEFAULT NULL COMMENT '检查目的',
  `clinical_diagnosis` varchar(500) DEFAULT NULL COMMENT '临床诊断',
  `disease_summary` text COMMENT '病史摘要',
  `special_requirements` varchar(500) DEFAULT NULL COMMENT '特殊要求',
  `is_emergency` tinyint DEFAULT '0' COMMENT '是否急诊（0-否 1-是）',
  `price` decimal(10,2) DEFAULT '0.00' COMMENT '检查费用',
  `apply_status` tinyint DEFAULT '1' COMMENT '申请状态（1-已提交 2-已缴费 6-已取消）',
  `appointment_time` datetime DEFAULT NULL COMMENT '预约时间',
  `sign_status` tinyint NOT NULL DEFAULT '0' COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint DEFAULT NULL COMMENT '当前有效签名ID',
  `signed_time` datetime DEFAULT NULL COMMENT '最近一次签名时刻',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `pay_time` datetime DEFAULT NULL COMMENT '缴费时间',
  `complete_time` datetime DEFAULT NULL COMMENT '完成时间',
  `report_id` bigint DEFAULT NULL COMMENT '报告ID',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(200) DEFAULT NULL COMMENT '取消原因',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_no` (`apply_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_regist_id` (`regist_id`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_visit_date` (`visit_date`),
  KEY `idx_doctor_id` (`doctor_id`),
  KEY `idx_apply_status` (`apply_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检查申请单';

-- ----------------------------
-- biz_inspection_record  检查记录
-- ----------------------------
CREATE TABLE `biz_inspection_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '检查记录号（唯一）',
  `apply_id` bigint NOT NULL COMMENT '申请单ID',
  `apply_no` varchar(32) NOT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号码',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '申请科室',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) DEFAULT NULL COMMENT '申请医生',
  `inspection_item_id` bigint NOT NULL COMMENT '检查项目ID',
  `inspection_item_code` varchar(32) NOT NULL COMMENT '检查项目编码',
  `inspection_item_name` varchar(200) NOT NULL COMMENT '检查项目名称',
  `inspection_dept_id` bigint DEFAULT NULL COMMENT '检查科室ID',
  `inspection_dept_name` varchar(100) DEFAULT NULL COMMENT '检查科室名称',
  `body_part` varchar(200) DEFAULT NULL COMMENT '检查部位',
  `inspection_purpose` varchar(500) DEFAULT NULL COMMENT '检查目的',
  `clinical_diagnosis` varchar(500) DEFAULT NULL COMMENT '临床诊断',
  `price` decimal(10,2) DEFAULT '0.00' COMMENT '检查费用',
  `appointment_time` datetime DEFAULT NULL COMMENT '预约时间',
  `check_in_time` datetime DEFAULT NULL COMMENT '签到时间',
  `execute_time` datetime DEFAULT NULL COMMENT '执行时间',
  `execute_by` varchar(64) DEFAULT NULL COMMENT '执行人',
  `result_description` text COMMENT '检查描述',
  `result_conclusion` text COMMENT '检查结论',
  `report_sign_id` bigint DEFAULT NULL COMMENT '报告医师签名ID',
  `report_signed_time` datetime DEFAULT NULL COMMENT '报告签名时刻',
  `result_image` varchar(500) DEFAULT NULL COMMENT '检查影像路径',
  `record_status` tinyint DEFAULT '1' COMMENT '记录状态（1-已登记 2-已签到 3-检查中 4-已出结果 5-已审核 6-已发布 7-已取消）',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核人（初审）',
  `audit_sign_id` bigint DEFAULT NULL COMMENT '审核医师签名ID',
  `audit_signed_time` datetime DEFAULT NULL COMMENT '审核签名时刻',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `audit2_by` varchar(64) DEFAULT NULL COMMENT '复审人',
  `audit2_time` datetime DEFAULT NULL COMMENT '复审时间',
  `report_time` datetime DEFAULT NULL COMMENT '报告发布时间',
  `report_by` varchar(64) DEFAULT NULL COMMENT '报告发布人',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(200) DEFAULT NULL COMMENT '取消原因',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`),
  KEY `idx_apply_id` (`apply_id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_inspection_item_id` (`inspection_item_id`),
  KEY `idx_inspection_dept_id` (`inspection_dept_id`),
  KEY `idx_record_status` (`record_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检查记录';

-- ----------------------------
-- biz_medicaltech_execution  医技执行记录
-- ----------------------------
CREATE TABLE `biz_medicaltech_execution` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `execution_no` varchar(32) NOT NULL COMMENT '执行单号',
  `apply_type` tinyint NOT NULL COMMENT '申请类型（1-检查 2-检验）',
  `apply_id` bigint NOT NULL COMMENT '申请单ID',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名',
  `item_id` bigint DEFAULT NULL COMMENT '项目ID',
  `item_code` varchar(32) DEFAULT NULL COMMENT '项目编码',
  `item_name` varchar(100) NOT NULL COMMENT '项目名称',
  `execution_status` tinyint NOT NULL DEFAULT '1' COMMENT '执行状态（1-待执行 2-执行中 3-已完成 4-已审核）',
  `executor_id` bigint DEFAULT NULL COMMENT '执行人ID',
  `executor_name` varchar(50) DEFAULT NULL COMMENT '执行人姓名',
  `execute_time` datetime DEFAULT NULL COMMENT '执行时间',
  `complete_time` datetime DEFAULT NULL COMMENT '完成时间',
  `reviewer_id` bigint DEFAULT NULL COMMENT '审核人ID',
  `reviewer_name` varchar(50) DEFAULT NULL COMMENT '审核人姓名',
  `review_time` datetime DEFAULT NULL COMMENT '审核时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_execution_no` (`execution_no`),
  KEY `idx_apply_id` (`apply_id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_execution_status` (`execution_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='医技执行记录';

-- ----------------------------
-- biz_report  报告单
-- ----------------------------
CREATE TABLE `biz_report` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `report_no` varchar(32) NOT NULL COMMENT '报告编号（唯一）',
  `report_type` tinyint NOT NULL COMMENT '报告类型（1-检查报告 2-检验报告）',
  `record_id` bigint NOT NULL COMMENT '检查/检验记录ID',
  `record_no` varchar(32) NOT NULL COMMENT '检查/检验记录号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期',
  `item_name` varchar(200) NOT NULL COMMENT '项目名称',
  `exam_method` varchar(200) DEFAULT NULL COMMENT '检查方法',
  `exam_dept_name` varchar(100) DEFAULT NULL COMMENT '检查/检验科室',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '申请科室',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) DEFAULT NULL COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) DEFAULT NULL COMMENT '临床诊断',
  `report_content` text COMMENT '报告内容',
  `conclusion` text COMMENT '报告结论',
  `positive_flag` tinyint DEFAULT NULL COMMENT '阴阳性（0-未判定 1-阴性 2-阳性 3-未见异常）',
  `is_critical` tinyint NOT NULL DEFAULT '0' COMMENT '是否危急（0-否 1-是）',
  `write_by` varchar(64) DEFAULT NULL COMMENT '报告书写人',
  `write_by_id` bigint DEFAULT NULL COMMENT '报告书写人员工ID',
  `write_time` datetime DEFAULT NULL COMMENT '报告书写时间',
  `template_id` bigint DEFAULT NULL COMMENT '使用的报告模板ID',
  `reject_reason` varchar(500) DEFAULT NULL COMMENT '退回原因',
  `report_version` int NOT NULL DEFAULT '1' COMMENT '报告版本号',
  `film_count` int NOT NULL DEFAULT '0' COMMENT '已登记胶片张数',
  `suggestions` text COMMENT '建议',
  `report_status` tinyint DEFAULT '1' COMMENT '报告状态（1-待审核 2-初审通过 3-已审核 4-已发布 5-已作废）',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核人（初审）',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `audit2_by` varchar(64) DEFAULT NULL COMMENT '复审人',
  `audit2_time` datetime DEFAULT NULL COMMENT '复审时间',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `publish_by` varchar(64) DEFAULT NULL COMMENT '发布人',
  `is_urgent` tinyint DEFAULT '0' COMMENT '是否加急（0-否 1-是）',
  `report_file_path` varchar(500) DEFAULT NULL COMMENT '报告文件路径',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_no` (`report_no`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_report_status` (`report_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='报告单';

-- ----------------------------
-- biz_exam_device  检查设备档位
-- ----------------------------
CREATE TABLE `biz_exam_device` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `device_code` varchar(32) NOT NULL COMMENT '预约设备编码',
  `device_name` varchar(100) NOT NULL COMMENT '设备名称',
  `device_type` tinyint NOT NULL COMMENT '设备类别（1-CT 2-MR 3-DR 4-超声 5-心电 6-内镜 7-其他）',
  `equipment_id` bigint DEFAULT NULL COMMENT '设备台账ID',
  `dept_id` bigint DEFAULT NULL COMMENT '检查科室ID',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '检查科室名称',
  `room_name` varchar(100) DEFAULT NULL COMMENT '检查室/机房位置',
  `am_start` char(5) NOT NULL DEFAULT '08:00' COMMENT '上午开放开始（HH:mm）',
  `am_end` char(5) NOT NULL DEFAULT '12:00' COMMENT '上午开放结束（HH:mm）',
  `pm_start` char(5) DEFAULT NULL COMMENT '下午开放开始（HH:mm）',
  `pm_end` char(5) DEFAULT NULL COMMENT '下午开放结束（HH:mm）',
  `slot_minutes` int NOT NULL DEFAULT '30' COMMENT '号源粒度',
  `parallel_count` int NOT NULL DEFAULT '1' COMMENT '单格子并行号数',
  `ahead_days` int NOT NULL DEFAULT '7' COMMENT '可提前预约天数',
  `max_slot_minutes` int NOT NULL DEFAULT '240' COMMENT '可占号最长时长（分钟）',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-开放预约 2-暂停预约）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_device_code` (`device_code`),
  KEY `idx_exam_device_type` (`device_type`),
  KEY `idx_exam_device_dept` (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检查设备档位';

-- ----------------------------
-- biz_exam_device_item  设备可开展项目
-- ----------------------------
CREATE TABLE `biz_exam_device_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `device_id` bigint NOT NULL COMMENT '设备ID',
  `item_id` bigint NOT NULL COMMENT '检查项目ID',
  `item_code` varchar(32) DEFAULT NULL COMMENT '项目编码（快照）',
  `item_name` varchar(200) DEFAULT NULL COMMENT '项目名称（快照）',
  `exam_minutes` int DEFAULT NULL COMMENT '该设备做该项目的时长（分钟）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_device_item` (`device_id`,`item_id`),
  KEY `idx_exam_item` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备可开展项目';

-- ----------------------------
-- biz_exam_slot  检查设备号源时段
-- ----------------------------
CREATE TABLE `biz_exam_slot` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `device_id` bigint NOT NULL COMMENT '设备ID',
  `slot_date` date NOT NULL COMMENT '号源日期',
  `seq` int DEFAULT NULL COMMENT '段序',
  `start_time` char(5) NOT NULL COMMENT '段开始时间（HH:mm）',
  `end_time` char(5) NOT NULL COMMENT '段结束时间（HH:mm）',
  `total_source` int NOT NULL DEFAULT '1' COMMENT '段号源总数',
  `used_source` int NOT NULL DEFAULT '0' COMMENT '段已占号数',
  `available_source` int NOT NULL DEFAULT '1' COMMENT '段剩余号源',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '段状态（0-停用锁号 1-正常）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_slot` (`device_id`,`slot_date`,`start_time`),
  KEY `idx_exam_slot_date` (`slot_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检查设备号源时段';

-- ----------------------------
-- biz_exam_appointment  检查预约单
-- ----------------------------
CREATE TABLE `biz_exam_appointment` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `appt_no` varchar(32) NOT NULL COMMENT '预约单号',
  `active_flag` tinyint DEFAULT '1' COMMENT '有效标记',
  `apply_id` bigint NOT NULL COMMENT '检查申请单ID',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '申请单号（快照）',
  `prev_apply_status` tinyint DEFAULT NULL COMMENT '预约前申请状态',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '申请科室',
  `doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `doctor_name` varchar(50) DEFAULT NULL COMMENT '申请医生',
  `item_id` bigint DEFAULT NULL COMMENT '检查项目ID',
  `item_code` varchar(32) DEFAULT NULL COMMENT '项目编码（快照）',
  `item_name` varchar(200) DEFAULT NULL COMMENT '项目名称（快照）',
  `body_part` varchar(200) DEFAULT NULL COMMENT '检查部位（快照）',
  `exam_minutes` int DEFAULT NULL COMMENT '本次占用时长',
  `device_id` bigint NOT NULL COMMENT '设备ID',
  `device_code` varchar(32) DEFAULT NULL COMMENT '设备编码（快照）',
  `device_name` varchar(100) DEFAULT NULL COMMENT '设备名称',
  `exam_dept_id` bigint DEFAULT NULL COMMENT '检查科室ID（快照）',
  `exam_dept_name` varchar(100) DEFAULT NULL COMMENT '检查科室名称（快照）',
  `room_name` varchar(100) DEFAULT NULL COMMENT '检查室（快照）',
  `exam_date` date NOT NULL COMMENT '检查日期',
  `start_time` char(5) NOT NULL COMMENT '开始时间（HH:mm）',
  `end_time` char(5) NOT NULL COMMENT '结束时间（HH:mm）',
  `is_emergency` tinyint DEFAULT '0' COMMENT '是否急诊（0-否 1-是）',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-已预约 2-已到检 3-已完成 4-已取消 5-爽约）',
  `book_by` varchar(64) DEFAULT NULL COMMENT '预约操作人',
  `book_time` datetime DEFAULT NULL COMMENT '预约操作时间',
  `arrive_time` datetime DEFAULT NULL COMMENT '到检时间',
  `finish_time` datetime DEFAULT NULL COMMENT '检查完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `noshow_time` datetime DEFAULT NULL COMMENT '爽约判定时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_appt_no` (`appt_no`),
  UNIQUE KEY `uk_exam_appt_active` (`apply_id`,`active_flag`),
  KEY `idx_exam_appt_apply` (`apply_id`),
  KEY `idx_exam_appt_patient_date` (`patient_id`,`exam_date`),
  KEY `idx_exam_appt_device_date` (`device_id`,`exam_date`),
  KEY `idx_exam_appt_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检查预约单';

-- ----------------------------
-- biz_exam_image  检查影像帧
-- ----------------------------
CREATE TABLE `biz_exam_image` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `biz_type` tinyint NOT NULL DEFAULT '1' COMMENT '影像来源单据类型',
  `apply_id` bigint NOT NULL COMMENT '申请单ID',
  `apply_no` varchar(64) DEFAULT NULL COMMENT '申请单号',
  `record_id` bigint DEFAULT NULL COMMENT '执行记录ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID（快照）',
  `patient_name` varchar(64) DEFAULT NULL COMMENT '患者姓名（快照）',
  `item_name` varchar(200) DEFAULT NULL COMMENT '检查/检验项目名称',
  `body_part` varchar(100) DEFAULT NULL COMMENT '检查部位（快照）',
  `modality` tinyint DEFAULT NULL COMMENT '影像模态（1-CT 2-MR 3-DR 4-超声 5-心电 6-内镜 7-其他）',
  `seq` int NOT NULL DEFAULT '1' COMMENT '本申请单内的帧序号',
  `file_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `file_url` varchar(500) NOT NULL COMMENT '访问路径',
  `file_size` bigint DEFAULT NULL COMMENT '文件字节数',
  `mime_type` varchar(64) DEFAULT NULL COMMENT '文件MIME类型',
  `source` tinyint NOT NULL DEFAULT '1' COMMENT '来源（1-工作站上传 2-模拟）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '上传人',
  `create_time` datetime DEFAULT NULL COMMENT '上传时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  KEY `idx_biz_apply` (`biz_type`,`apply_id`,`seq`),
  KEY `idx_patient` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检查影像帧';

-- ----------------------------
-- biz_exam_film  检查胶片用量
-- ----------------------------
CREATE TABLE `biz_exam_film` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `film_no` varchar(32) NOT NULL COMMENT '胶片单号',
  `record_id` bigint NOT NULL COMMENT '检查记录ID',
  `record_no` varchar(32) DEFAULT NULL COMMENT '检查记录号（快照）',
  `apply_id` bigint DEFAULT NULL COMMENT '检查申请单ID',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '申请单号（快照）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号（快照）',
  `patient_name` varchar(64) DEFAULT NULL COMMENT '患者姓名（快照）',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期（快照）',
  `item_code` varchar(32) DEFAULT NULL COMMENT '检查项目编码（快照）',
  `item_name` varchar(200) DEFAULT NULL COMMENT '检查项目名称（快照）',
  `body_part` varchar(100) DEFAULT NULL COMMENT '检查部位（快照）',
  `modality` tinyint DEFAULT NULL COMMENT '影像模态（，快照）',
  `spec_id` bigint NOT NULL COMMENT '胶片规格ID',
  `spec_code` varchar(32) DEFAULT NULL COMMENT '规格编码（快照）',
  `spec_name` varchar(100) NOT NULL COMMENT '规格名称',
  `unit_price` decimal(10,2) NOT NULL COMMENT '单价',
  `unit` varchar(20) DEFAULT NULL COMMENT '计价单位（快照）',
  `quantity` int NOT NULL COMMENT '胶片张数',
  `amount` decimal(12,2) NOT NULL COMMENT '金额 = 单价 × 张数',
  `film_status` tinyint NOT NULL DEFAULT '1' COMMENT '胶片状态（1-已登记 2-已打印 3-已发放 4-已作废）',
  `charge_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否已记账（0-未记账 1-已记账）',
  `fee_id` bigint DEFAULT NULL COMMENT '记账流水ID',
  `fee_no` varchar(32) DEFAULT NULL COMMENT '记账流水号（快照）',
  `print_by` varchar(64) DEFAULT NULL COMMENT '打印人',
  `print_time` datetime DEFAULT NULL COMMENT '打印时间',
  `deliver_by` varchar(64) DEFAULT NULL COMMENT '发放人',
  `deliver_time` datetime DEFAULT NULL COMMENT '发放时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_film_no` (`film_no`),
  KEY `idx_record` (`record_id`),
  KEY `idx_patient` (`patient_id`),
  KEY `idx_film_status` (`film_status`),
  KEY `idx_charge` (`charge_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='检查胶片用量';

-- ----------------------------
-- biz_film_spec  胶片规格价目
-- ----------------------------
CREATE TABLE `biz_film_spec` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `spec_code` varchar(32) NOT NULL COMMENT '规格编码',
  `spec_name` varchar(100) NOT NULL COMMENT '规格名称',
  `unit_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '单价',
  `unit` varchar(20) NOT NULL DEFAULT '张' COMMENT '计价单位',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_spec_code` (`spec_code`),
  KEY `idx_status_sort` (`status`,`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='胶片规格价目';

-- ----------------------------
-- biz_radio_report_template  放射报告模板
-- ----------------------------
CREATE TABLE `biz_radio_report_template` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_code` varchar(32) NOT NULL COMMENT '模板编码',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `modality` tinyint DEFAULT NULL COMMENT '适用模态',
  `item_code` varchar(32) DEFAULT NULL COMMENT '适用检查项目编码',
  `item_name` varchar(200) DEFAULT NULL COMMENT '适用检查项目名称（快照）',
  `body_part` varchar(100) DEFAULT NULL COMMENT '适用检查部位',
  `exam_method` varchar(200) DEFAULT NULL COMMENT '检查方法模板',
  `finding_tpl` text COMMENT '影像所见模板',
  `impression_tpl` text COMMENT '影像诊断/印象模板',
  `suggestion_tpl` text COMMENT '建议模板',
  `is_public` tinyint NOT NULL DEFAULT '1' COMMENT '是否公用（1-科室公用 0-个人模板）',
  `doctor_id` bigint DEFAULT NULL COMMENT '归属医生',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_code` (`template_code`),
  KEY `idx_modality` (`modality`,`status`),
  KEY `idx_doctor` (`doctor_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='放射报告模板';

-- ----------------------------
-- biz_ultrasound_record  超声检查记录
-- ----------------------------
CREATE TABLE `biz_ultrasound_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '超声检查号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '申请科室',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) DEFAULT NULL COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) DEFAULT NULL COMMENT '临床诊断',
  `us_type` tinyint DEFAULT '1' COMMENT '超声类型（1-腹部 2-心脏 3-妇产 4-血管 5-浅表器官 6-肌骨 7-腔内）',
  `body_part` varchar(200) DEFAULT NULL COMMENT '检查部位',
  `exam_purpose` varchar(500) DEFAULT NULL COMMENT '检查目的',
  `findings` text COMMENT '超声所见',
  `conclusion` text COMMENT '超声提示（结论）',
  `suggestion` varchar(1000) DEFAULT NULL COMMENT '建议',
  `sonographer` varchar(64) DEFAULT NULL COMMENT '检查医师',
  `execute_time` datetime DEFAULT NULL COMMENT '检查时间',
  `status` tinyint DEFAULT '1' COMMENT '状态（1-已登记 2-已签到 3-检查中 4-已出报告 5-已审核 6-已发布 7-已取消）',
  `report_by` varchar(64) DEFAULT NULL COMMENT '报告医师',
  `report_time` datetime DEFAULT NULL COMMENT '报告时间',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核医师',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `publish_by` varchar(64) DEFAULT NULL COMMENT '发布人',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_status` (`status`),
  KEY `idx_us_type` (`us_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='超声检查记录';

-- ----------------------------
-- biz_ultrasound_measure  超声测量值
-- ----------------------------
CREATE TABLE `biz_ultrasound_measure` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_id` bigint NOT NULL COMMENT '超声记录ID',
  `record_no` varchar(32) NOT NULL COMMENT '超声检查号',
  `measure_name` varchar(100) NOT NULL COMMENT '测量项',
  `measure_value` varchar(100) DEFAULT NULL COMMENT '测量值',
  `unit` varchar(20) DEFAULT NULL COMMENT '单位',
  `reference_range` varchar(100) DEFAULT NULL COMMENT '参考范围',
  `abnormal_flag` tinyint DEFAULT '0' COMMENT '异常标志（0-正常 1-偏高 2-偏低 3-异常）',
  `sort_order` int DEFAULT '0' COMMENT '排序号',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_record_id` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='超声测量值';

-- ----------------------------
-- biz_pathology_order  病理检查主单
-- ----------------------------
CREATE TABLE `biz_pathology_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_no` varchar(32) NOT NULL COMMENT '病理号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '申请科室',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) DEFAULT NULL COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) DEFAULT NULL COMMENT '临床诊断',
  `exam_type` tinyint DEFAULT '1' COMMENT '病理检查类型（1-常规石蜡 2-术中冰冻 3-细胞学 4-免疫组化 5-疑难会诊）',
  `specimen_type` varchar(100) DEFAULT NULL COMMENT '标本类型（活检/切除/穿刺/脱落细胞等）',
  `specimen_part` varchar(200) DEFAULT NULL COMMENT '取材部位',
  `is_frozen` tinyint DEFAULT '0' COMMENT '是否冰冻（0-否 1-是）',
  `frozen_result` varchar(500) DEFAULT NULL COMMENT '术中冰冻快速诊断结果',
  `receive_time` datetime DEFAULT NULL COMMENT '标本接收时间',
  `receive_by` varchar(64) DEFAULT NULL COMMENT '标本接收人',
  `sampling_time` datetime DEFAULT NULL COMMENT '取材时间',
  `sampling_by` varchar(64) DEFAULT NULL COMMENT '取材人',
  `embedding_time` datetime DEFAULT NULL COMMENT '包埋时间',
  `embedding_by` varchar(64) DEFAULT NULL COMMENT '包埋人',
  `slice_time` datetime DEFAULT NULL COMMENT '制片（切片）',
  `slice_by` varchar(64) DEFAULT NULL COMMENT '制片人',
  `gross_findings` text COMMENT '肉眼所见',
  `microscopy_findings` text COMMENT '镜下所见',
  `ihc_result` varchar(1000) DEFAULT NULL COMMENT '免疫组化 / 特殊染色结果',
  `diagnosis` text COMMENT '病理诊断',
  `suggestion` varchar(1000) DEFAULT NULL COMMENT '建议',
  `status` tinyint DEFAULT '1' COMMENT '状态',
  `report_by` varchar(64) DEFAULT NULL COMMENT '初诊医师',
  `report_time` datetime DEFAULT NULL COMMENT '初诊时间',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核医师',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `publish_by` varchar(64) DEFAULT NULL COMMENT '发布人',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_status` (`status`),
  KEY `idx_exam_type` (`exam_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病理检查主单';

-- ----------------------------
-- biz_pathology_block  病理蜡块与切片
-- ----------------------------
CREATE TABLE `biz_pathology_block` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '病理主单ID',
  `order_no` varchar(32) NOT NULL COMMENT '病理号',
  `block_no` varchar(32) NOT NULL COMMENT '蜡块号',
  `part_desc` varchar(200) DEFAULT NULL COMMENT '取材部位描述',
  `block_count` int DEFAULT '1' COMMENT '蜡块数',
  `slice_count` int DEFAULT '0' COMMENT '切片数',
  `slide_no` varchar(50) DEFAULT NULL COMMENT '切片号',
  `status` tinyint DEFAULT '1' COMMENT '状态（1-待取材 2-已取材 3-已包埋 4-已切片）',
  `sampling_by` varchar(64) DEFAULT NULL COMMENT '取材人',
  `sampling_time` datetime DEFAULT NULL COMMENT '取材时间',
  `embedding_by` varchar(64) DEFAULT NULL COMMENT '包埋人',
  `embedding_time` datetime DEFAULT NULL COMMENT '包埋时间',
  `slice_by` varchar(64) DEFAULT NULL COMMENT '切片人',
  `slice_time` datetime DEFAULT NULL COMMENT '切片时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='病理蜡块与切片';

-- ----------------------------
-- biz_endoscopy_record  内镜检查记录
-- ----------------------------
CREATE TABLE `biz_endoscopy_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '内镜检查号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `age` int DEFAULT NULL COMMENT '年龄',
  `visit_date` date DEFAULT NULL COMMENT '就诊日期',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) DEFAULT NULL COMMENT '申请科室',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) DEFAULT NULL COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) DEFAULT NULL COMMENT '临床诊断',
  `endo_type` tinyint DEFAULT '1' COMMENT '内镜类型（1-胃镜 2-肠镜 3-支气管镜 4-膀胱镜 5-宫腔镜 6-喉镜 7-ERCP 8-胶囊内镜）',
  `anesthesia_method` tinyint DEFAULT '1' COMMENT '麻醉方式（1-无麻醉 2-表面麻醉 3-静脉麻醉 4-全身麻醉）',
  `body_part` varchar(200) DEFAULT NULL COMMENT '检查部位 / 到达范围',
  `exam_purpose` varchar(500) DEFAULT NULL COMMENT '检查目的',
  `bowel_prep_score` tinyint DEFAULT NULL COMMENT '肠道准备质量 Boston 评分',
  `hp_result` tinyint DEFAULT '0' COMMENT '幽门螺杆菌（0-未查 1-阴性 2-阳性）',
  `findings` text COMMENT '内镜所见',
  `diagnosis` text COMMENT '内镜诊断',
  `suggestion` varchar(1000) DEFAULT NULL COMMENT '建议',
  `biopsy_flag` tinyint DEFAULT '0' COMMENT '是否活检（0-否 1-是）',
  `biopsy_part` varchar(200) DEFAULT NULL COMMENT '活检部位',
  `biopsy_count` int DEFAULT '0' COMMENT '活检块数',
  `pathology_order_no` varchar(32) DEFAULT NULL COMMENT '关联病理号',
  `endoscopist` varchar(64) DEFAULT NULL COMMENT '内镜医师',
  `execute_time` datetime DEFAULT NULL COMMENT '检查时间',
  `status` tinyint DEFAULT '1' COMMENT '状态（1-已登记 2-已签到 3-检查中 4-已出报告 5-已审核 6-已发布 7-已取消）',
  `report_by` varchar(64) DEFAULT NULL COMMENT '报告医师',
  `report_time` datetime DEFAULT NULL COMMENT '报告时间',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核医师',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `publish_by` varchar(64) DEFAULT NULL COMMENT '发布人',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_status` (`status`),
  KEY `idx_endo_type` (`endo_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='内镜检查记录';

-- ----------------------------
-- biz_ecg_waveform  心电波形采集
-- ----------------------------
CREATE TABLE `biz_ecg_waveform` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `wave_no` varchar(32) NOT NULL COMMENT '波形号',
  `record_id` bigint NOT NULL COMMENT '检查记录ID',
  `record_no` varchar(32) DEFAULT NULL COMMENT '检查记录号（快照）',
  `apply_id` bigint DEFAULT NULL COMMENT '检查申请单ID（冗余）',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '申请单号（快照）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号（快照）',
  `patient_name` varchar(64) DEFAULT NULL COMMENT '患者姓名（快照）',
  `ecg_type` tinyint NOT NULL DEFAULT '1' COMMENT '心电类型（1-常规静息心电图 2-24小时动态心电图）',
  `wave_data` longtext COMMENT '波形数据',
  `device_no` varchar(64) DEFAULT NULL COMMENT '采集设备号',
  `collect_by` varchar(64) DEFAULT NULL COMMENT '采集人',
  `collect_time` datetime DEFAULT NULL COMMENT '采集时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wave_no` (`wave_no`),
  KEY `idx_record` (`record_id`),
  KEY `idx_patient` (`patient_id`),
  KEY `idx_ecg_type` (`ecg_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='心电波形采集';

-- ----------------------------
-- biz_ecg_measure  心电测量参数
-- ----------------------------
CREATE TABLE `biz_ecg_measure` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_id` bigint NOT NULL COMMENT '检查记录ID',
  `waveform_id` bigint DEFAULT NULL COMMENT '波形ID',
  `hr` int DEFAULT NULL COMMENT '心率（次/分）',
  `pr_ms` int DEFAULT NULL COMMENT 'PR间期',
  `qrs_ms` int DEFAULT NULL COMMENT 'QRS时限',
  `qt_ms` int DEFAULT NULL COMMENT 'QT间期（ms）',
  `qtc_ms` int DEFAULT NULL COMMENT 'QTc校正间期',
  `p_axis` int DEFAULT NULL COMMENT 'P电轴（°）',
  `qrs_axis` int DEFAULT NULL COMMENT 'QRS电轴',
  `t_axis` int DEFAULT NULL COMMENT 'T电轴（°）',
  `rhythm_text` varchar(100) DEFAULT NULL COMMENT '节律描述',
  `measure_by` varchar(64) DEFAULT NULL COMMENT '测量人',
  `measure_time` datetime DEFAULT NULL COMMENT '测量时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_record` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='心电测量参数';

-- ----------------------------
-- biz_ecg_holter  Holter 动态心电
-- ----------------------------
CREATE TABLE `biz_ecg_holter` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_id` bigint NOT NULL COMMENT '检查记录ID',
  `waveform_id` bigint DEFAULT NULL COMMENT '波形ID',
  `wear_start_time` datetime DEFAULT NULL COMMENT '开始佩戴时间',
  `wear_end_time` datetime DEFAULT NULL COMMENT '结束佩戴时间',
  `total_beats` int DEFAULT NULL COMMENT '总心搏数',
  `avg_hr` int DEFAULT NULL COMMENT '平均心率（次/分）',
  `max_hr` int DEFAULT NULL COMMENT '最快心率（次/分）',
  `max_hr_time` varchar(16) DEFAULT NULL COMMENT '最快心率时刻（HH:mm）',
  `min_hr` int DEFAULT NULL COMMENT '最慢心率（次/分）',
  `min_hr_time` varchar(16) DEFAULT NULL COMMENT '最慢心率时刻（HH:mm）',
  `afib_flag` tinyint DEFAULT NULL COMMENT '是否检出房颤（0-否 1-是）',
  `afib_beats` int DEFAULT NULL COMMENT '房颤心搏数',
  `svc_count` int DEFAULT NULL COMMENT '室上性早搏总数',
  `pvc_count` int DEFAULT NULL COMMENT '室性早搏总数',
  `vt_count` int DEFAULT NULL COMMENT '室性心动过速阵数',
  `pause_count` int DEFAULT NULL COMMENT '停搏',
  `longest_pause_ms` int DEFAULT NULL COMMENT '最长停搏时长',
  `st_episode_count` int DEFAULT NULL COMMENT 'ST段异常发作阵数',
  `hourly_hr_json` text COMMENT '24小时逐时平均心率',
  `analysis_by` varchar(64) DEFAULT NULL COMMENT '分析人',
  `analysis_time` datetime DEFAULT NULL COMMENT '分析时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_record` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Holter 动态心电';

-- ----------------------------
-- biz_ecg_template  心电报告模板
-- ----------------------------
CREATE TABLE `biz_ecg_template` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `template_code` varchar(32) NOT NULL COMMENT '模板编码',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `ecg_type` tinyint DEFAULT NULL COMMENT '适用心电类型',
  `finding_tpl` text COMMENT '心电图所见模板',
  `conclusion_tpl` text COMMENT '心电图诊断模板',
  `suggestion_tpl` text COMMENT '建议模板',
  `sort_order` int NOT NULL DEFAULT '0' COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ecg_tpl_code` (`template_code`),
  KEY `idx_ecg_type` (`ecg_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='心电报告模板';
