-- 领域：14-手术麻醉与日间手术
-- 库：hn_biz_his    表数：14
-- 说明：DDL 快照（由线上库 SHOW CREATE TABLE 导出，无 DROP / 无数据）。建表语句彼此独立，不含外键约束。

-- ----------------------------
-- biz_operation_apply  手术申请单
-- ----------------------------
CREATE TABLE `biz_operation_apply` (
  `id` bigint NOT NULL COMMENT '手术申请单ID（雪花）',
  `apply_no` varchar(32) NOT NULL COMMENT '手术申请单号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `admission_no` varchar(32) DEFAULT NULL COMMENT '入院号（快照）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（快照）（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `apply_dept_id` bigint DEFAULT NULL COMMENT '申请科室ID',
  `apply_dept_name` varchar(64) DEFAULT NULL COMMENT '申请科室名称（快照）',
  `apply_ward_name` varchar(64) DEFAULT NULL COMMENT '申请时所在病区名称（快照）',
  `apply_bed_no` varchar(32) DEFAULT NULL COMMENT '申请时床号（快照）',
  `apply_doctor_id` bigint DEFAULT NULL COMMENT '申请医生ID',
  `apply_doctor_name` varchar(64) DEFAULT NULL COMMENT '申请医生姓名（快照）',
  `apply_time` datetime DEFAULT NULL COMMENT '申请时间',
  `planned_operation_code` varchar(32) DEFAULT NULL COMMENT '拟施手术编码',
  `planned_operation_name` varchar(200) NOT NULL COMMENT '拟施手术名称',
  `operation_level` tinyint DEFAULT NULL COMMENT '手术级别（1-一级 2-二级 3-三级 4-四级）',
  `incision_level` tinyint DEFAULT NULL COMMENT '切口等级（0-0类 1-Ⅰ类 2-Ⅱ类 3-Ⅲ类）',
  `anesthesia_type` tinyint DEFAULT NULL COMMENT '麻醉方式（1-全麻 2-椎管内 3-神经阻滞 4-局麻 5-其他）',
  `preop_diagnosis` varchar(500) NOT NULL COMMENT '术前诊断',
  `operation_reason` varchar(500) NOT NULL COMMENT '手术指征/理由',
  `is_emergency` tinyint NOT NULL DEFAULT '0' COMMENT '是否急诊手术（0-否 1-是）',
  `is_main` tinyint NOT NULL DEFAULT '1' COMMENT '是否主要手术',
  `operation_room` varchar(64) DEFAULT NULL COMMENT '手术间',
  `planned_start_time` datetime DEFAULT NULL COMMENT '计划开始时间',
  `planned_end_time` datetime DEFAULT NULL COMMENT '计划结束时间',
  `surgeon_id` bigint DEFAULT NULL COMMENT '主刀医师ID（员工ID）',
  `surgeon_name` varchar(64) DEFAULT NULL COMMENT '主刀医师姓名（快照）',
  `assistant_name` varchar(200) DEFAULT NULL COMMENT '助手姓名',
  `anesthetist_id` bigint DEFAULT NULL COMMENT '麻醉医师ID（员工ID）',
  `anesthetist_name` varchar(64) DEFAULT NULL COMMENT '麻醉医师姓名（快照）',
  `schedule_doctor_id` bigint DEFAULT NULL COMMENT '排台操作人ID（员工ID）',
  `schedule_doctor_name` varchar(64) DEFAULT NULL COMMENT '排台操作人姓名（快照）',
  `schedule_time` datetime DEFAULT NULL COMMENT '排台时间',
  `schedule_remark` varchar(500) DEFAULT NULL COMMENT '排台备注',
  `preop_check_items` varchar(200) DEFAULT NULL COMMENT '术前核对要点码',
  `preop_note` varchar(1000) DEFAULT NULL COMMENT '术前核对补充说明',
  `preop_check_doctor_id` bigint DEFAULT NULL COMMENT '术前核对人ID（员工ID）',
  `preop_check_doctor_name` varchar(64) DEFAULT NULL COMMENT '术前核对人姓名（快照）',
  `preop_check_time` datetime DEFAULT NULL COMMENT '术前核对时间',
  `actual_operation_code` varchar(32) DEFAULT NULL COMMENT '实际手术编码',
  `actual_operation_name` varchar(200) DEFAULT NULL COMMENT '实际手术名称',
  `operation_start_time` datetime DEFAULT NULL COMMENT '实际开始时间（切皮）',
  `operation_end_time` datetime DEFAULT NULL COMMENT '实际结束时间（关腹/关胸）',
  `blood_loss` int DEFAULT NULL COMMENT '术中出血量（ml）',
  `intraop_findings` varchar(2000) DEFAULT NULL COMMENT '术中所见',
  `intraop_procedure` varchar(2000) DEFAULT NULL COMMENT '手术经过/操作步骤',
  `postop_note` varchar(1000) DEFAULT NULL COMMENT '术后处理与注意事项',
  `specimen_sent` varchar(200) DEFAULT NULL COMMENT '标本送检',
  `finish_doctor_id` bigint DEFAULT NULL COMMENT '完成录入人ID（员工ID）',
  `finish_doctor_name` varchar(64) DEFAULT NULL COMMENT '完成录入人姓名（快照）',
  `finish_time` datetime DEFAULT NULL COMMENT '手术完成时间',
  `operation_id` bigint DEFAULT NULL COMMENT '回写病案首页手术明细ID',
  `record_id` bigint DEFAULT NULL COMMENT '回写住院病历ID',
  `operation_status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0-待排期 1-已排期 2-术前核对完成 3-已完成 4-已取消）',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `cancel_doctor_id` bigint DEFAULT NULL COMMENT '取消人ID（员工ID）',
  `cancel_doctor_name` varchar(64) DEFAULT NULL COMMENT '取消人姓名（快照）',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  KEY `idx_op_admission` (`admission_id`),
  KEY `idx_op_status` (`operation_status`),
  KEY `idx_op_room_time` (`operation_room`,`planned_start_time`),
  KEY `idx_op_surgeon` (`surgeon_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='手术申请单';

-- ----------------------------
-- biz_operation_safety_check  手术安全核查单
-- ----------------------------
CREATE TABLE `biz_operation_safety_check` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `check_no` varchar(32) NOT NULL COMMENT '核查单号',
  `apply_id` bigint NOT NULL COMMENT '手术申请单ID',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '手术申请单号（快照）',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `operation_name` varchar(200) DEFAULT NULL COMMENT '手术名称（快照，拟施）',
  `operation_room` varchar(64) DEFAULT NULL COMMENT '手术间（快照）',
  `phase` tinyint NOT NULL COMMENT '核查时段（1-麻醉诱导前 2-手术开始前 3-患者离开手术室前）',
  `items` varchar(300) NOT NULL COMMENT '核查项码值',
  `note` varchar(1000) DEFAULT NULL COMMENT '异常说明',
  `surgeon_id` bigint NOT NULL COMMENT '手术医师',
  `surgeon_name` varchar(64) DEFAULT NULL COMMENT '手术医师姓名（快照）',
  `surgeon_sign_time` datetime DEFAULT NULL COMMENT '手术医师签名时间',
  `anesthetist_id` bigint NOT NULL COMMENT '麻醉医师员工ID',
  `anesthetist_name` varchar(64) DEFAULT NULL COMMENT '麻醉医师姓名（快照）',
  `anesthetist_sign_time` datetime DEFAULT NULL COMMENT '麻醉医师签名时间',
  `nurse_id` bigint NOT NULL COMMENT '手术室护士（器械/巡回）',
  `nurse_name` varchar(64) DEFAULT NULL COMMENT '手术室护士姓名（快照）',
  `nurse_sign_time` datetime DEFAULT NULL COMMENT '手术室护士签名时间',
  `recorder_id` bigint DEFAULT NULL COMMENT '录入人ID',
  `recorder_name` varchar(64) DEFAULT NULL COMMENT '录入人姓名（快照）',
  `check_time` datetime DEFAULT NULL COMMENT '核查完成时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_check_no` (`check_no`),
  UNIQUE KEY `uk_check_apply_phase` (`apply_id`,`phase`),
  KEY `idx_check_time` (`check_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='手术安全核查单';

-- ----------------------------
-- biz_operation_count  手术清点主单
-- ----------------------------
CREATE TABLE `biz_operation_count` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `count_no` varchar(32) NOT NULL COMMENT '清点单号',
  `apply_id` bigint NOT NULL COMMENT '手术申请单ID',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '手术申请单号（快照）',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `operation_room` varchar(64) DEFAULT NULL COMMENT '手术间（快照）',
  `planned_operation_name` varchar(200) DEFAULT NULL COMMENT '手术名称（快照）',
  `instrument_nurse_id` bigint DEFAULT NULL COMMENT '器械（洗手）',
  `instrument_nurse_name` varchar(64) DEFAULT NULL COMMENT '器械护士姓名（快照）',
  `circulate_nurse_id` bigint DEFAULT NULL COMMENT '巡回护士ID（员工ID）',
  `circulate_nurse_name` varchar(64) DEFAULT NULL COMMENT '巡回护士姓名（快照）',
  `before_nurse_id` bigint DEFAULT NULL COMMENT '术前清点核对人ID',
  `before_nurse_name` varchar(64) DEFAULT NULL COMMENT '术前清点核对人姓名（快照）',
  `before_time` datetime DEFAULT NULL COMMENT '术前清点时间',
  `before_result` tinyint DEFAULT NULL COMMENT '术前清点结果（1-一致 2-不一致）',
  `closure_nurse_id` bigint DEFAULT NULL COMMENT '关体前清点核对人ID（员工ID）',
  `closure_nurse_name` varchar(64) DEFAULT NULL COMMENT '关体前核对人姓名（快照）',
  `closure_time` datetime DEFAULT NULL COMMENT '关体前清点时间',
  `closure_result` tinyint DEFAULT NULL COMMENT '关体前清点结果（1-一致 2-不一致）',
  `final_nurse_id` bigint DEFAULT NULL COMMENT '关体后清点核对人ID（员工ID）',
  `final_nurse_name` varchar(64) DEFAULT NULL COMMENT '关体后核对人姓名（快照）',
  `final_time` datetime DEFAULT NULL COMMENT '关体后清点时间',
  `final_result` tinyint DEFAULT NULL COMMENT '关体后清点结果（1-一致 2-不一致）',
  `phase` tinyint NOT NULL DEFAULT '0' COMMENT '当前阶段（0-未开始 1-术前完成 2-关体前完成 3-关体后完成）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0-清点中 1-三轮一致完成 2-存在差异待处理 3-异常终止）',
  `discrepancy_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否存在清点差异（0-无 1-有）',
  `diff_note` varchar(1000) DEFAULT NULL COMMENT '差异说明与处理过程（差了什么、怎么处理、结论如何必须写清）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_count_apply` (`apply_id`),
  UNIQUE KEY `uk_count_no` (`count_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='手术清点主单';

-- ----------------------------
-- biz_operation_count_item  手术清点明细
-- ----------------------------
CREATE TABLE `biz_operation_count_item` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `count_id` bigint NOT NULL COMMENT '清点单ID',
  `seq_no` int NOT NULL DEFAULT '1' COMMENT '行号',
  `item_category` tinyint NOT NULL COMMENT '类别（纱布/纱垫）（1-器械 2-敷料 3-缝针 4-刀片 5-其他）',
  `item_name` varchar(100) NOT NULL COMMENT '名称（如：止血钳 / 纱布块 / 圆针）',
  `spec` varchar(100) DEFAULT NULL COMMENT '规格',
  `before_qty` int DEFAULT NULL COMMENT '术前数量',
  `closure_qty` int DEFAULT NULL COMMENT '关体前数量',
  `final_qty` int DEFAULT NULL COMMENT '关体后数量',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  KEY `idx_count_item` (`count_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='手术清点明细';

-- ----------------------------
-- biz_anesthesia_visit  麻醉术前访视单
-- ----------------------------
CREATE TABLE `biz_anesthesia_visit` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `visit_no` varchar(32) NOT NULL COMMENT '访视单号',
  `apply_id` bigint NOT NULL COMMENT '手术申请单ID',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '手术申请单号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（快照）（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `diagnosis` varchar(500) DEFAULT NULL COMMENT '术前诊断（快照）',
  `planned_operation_code` varchar(32) DEFAULT NULL COMMENT '拟施手术编码（快照）',
  `planned_operation_name` varchar(200) DEFAULT NULL COMMENT '拟施手术名称（快照）',
  `operation_level` tinyint DEFAULT NULL COMMENT '手术级别（快照）',
  `anesthesia_type` tinyint DEFAULT NULL COMMENT '拟施麻醉方式（1-全麻 2-椎管内 3-神经阻滞 4-局麻 5-其他）',
  `is_emergency` tinyint NOT NULL DEFAULT '0' COMMENT '是否急诊手术（0-否 1-是）',
  `asa_grade` tinyint DEFAULT NULL COMMENT 'ASA 分级（1-Ⅰ 2-Ⅱ 3-Ⅲ 4-Ⅳ 5-Ⅴ）',
  `asa_emergency` tinyint NOT NULL DEFAULT '0' COMMENT 'ASA E（急诊）（0-否 1-是）',
  `mallampati` tinyint DEFAULT NULL COMMENT 'Mallampati 气道分级（1-Ⅰ 2-Ⅱ 3-Ⅲ 4-Ⅳ）',
  `mouth_open_cm` decimal(4,1) DEFAULT NULL COMMENT '张口度（cm）',
  `neck_mobility` tinyint DEFAULT NULL COMMENT '颈部活动度（1-正常 2-受限 3-强直）',
  `difficult_airway` tinyint NOT NULL DEFAULT '0' COMMENT '预计困难气道（0-否 1-是）',
  `airway_note` varchar(500) DEFAULT NULL COMMENT '气道评估补充说明',
  `past_anesthesia_history` varchar(1000) DEFAULT NULL COMMENT '既往麻醉史与不良反应史',
  `allergy_history` varchar(500) DEFAULT NULL COMMENT '过敏史（药物/食物/消毒剂）',
  `medication_history` varchar(1000) DEFAULT NULL COMMENT '长期用药史（抗凝药/降压药/激素等必须写）',
  `smoke_drink` varchar(200) DEFAULT NULL COMMENT '吸烟饮酒史',
  `npo_status` tinyint DEFAULT NULL COMMENT '禁食禁饮（0-未禁食 1-已按要求禁食 2-急诊饱胃）',
  `height_cm` decimal(5,1) DEFAULT NULL COMMENT '身高（cm）',
  `weight_kg` decimal(5,1) DEFAULT NULL COMMENT '体重（kg）',
  `exam_summary` varchar(1000) DEFAULT NULL COMMENT '辅助检查摘要（血常规/凝血/ECG/胸片/电解质等）',
  `anesthesia_plan` varchar(1000) DEFAULT NULL COMMENT '麻醉计划',
  `monitoring_plan` varchar(500) DEFAULT NULL COMMENT '监测计划（有创血压/CVP/BIS/体温等）',
  `risk_assessment` varchar(1000) DEFAULT NULL COMMENT '风险评估',
  `backup_plan` varchar(500) DEFAULT NULL COMMENT '备选方案',
  `conclusion` tinyint DEFAULT NULL COMMENT '访视结论（1-可施行麻醉 2-暂缓手术 3-需会诊）',
  `conclusion_note` varchar(1000) DEFAULT NULL COMMENT '结论说明',
  `visit_status` tinyint NOT NULL DEFAULT '0' COMMENT '访视状态（0-草稿 1-已完成）',
  `visit_doctor_id` bigint DEFAULT NULL COMMENT '访视麻醉医师ID（员工ID）',
  `visit_doctor_name` varchar(64) DEFAULT NULL COMMENT '访视麻醉医师姓名（快照）',
  `visit_time` datetime DEFAULT NULL COMMENT '访视时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_visit_apply` (`apply_id`),
  UNIQUE KEY `uk_visit_no` (`visit_no`),
  KEY `idx_visit_admission` (`admission_id`),
  KEY `idx_visit_conclusion` (`conclusion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='麻醉术前访视单';

-- ----------------------------
-- biz_anesthesia_record  麻醉记录单
-- ----------------------------
CREATE TABLE `biz_anesthesia_record` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `record_no` varchar(32) NOT NULL COMMENT '麻醉记录单号',
  `apply_id` bigint NOT NULL COMMENT '手术申请单ID',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '手术申请单号（快照）',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（快照）（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `visit_id` bigint DEFAULT NULL COMMENT '来源术前访视单ID',
  `anesthesia_type` tinyint DEFAULT NULL COMMENT '麻醉方式（1-全麻 2-椎管内 3-神经阻滞 4-局麻 5-其他）',
  `asa_grade` tinyint DEFAULT NULL COMMENT 'ASA 分级',
  `anesthetist_id` bigint DEFAULT NULL COMMENT '麻醉医师ID（员工ID）',
  `anesthetist_name` varchar(64) DEFAULT NULL COMMENT '麻醉医师姓名（快照）',
  `assistant_anesthetist_name` varchar(200) DEFAULT NULL COMMENT '麻醉助手姓名',
  `anesthesia_method_detail` varchar(500) DEFAULT NULL COMMENT '麻醉方法描述',
  `airway_device` tinyint DEFAULT NULL COMMENT '气道管理方式（0-无 1-气管插管 2-喉罩 3-面罩 4-其他）',
  `airway_device_spec` varchar(100) DEFAULT NULL COMMENT '气道器具规格',
  `ventilation_mode` tinyint DEFAULT NULL COMMENT '通气方式（1-自主呼吸 2-辅助通气 3-控制通气）',
  `enter_room_time` datetime DEFAULT NULL COMMENT '入手术室时间',
  `anesthesia_start_time` datetime DEFAULT NULL COMMENT '麻醉开始时间',
  `operation_start_time` datetime DEFAULT NULL COMMENT '手术开始时间（切皮）',
  `operation_end_time` datetime DEFAULT NULL COMMENT '手术结束时间（关腹/关胸）',
  `anesthesia_end_time` datetime DEFAULT NULL COMMENT '麻醉结束时间（停药）',
  `leave_room_time` datetime DEFAULT NULL COMMENT '出手术室时间',
  `crystalloid` int DEFAULT NULL COMMENT '晶体液入量（ml）',
  `colloid` int DEFAULT NULL COMMENT '胶体液入量（ml）',
  `blood_transfusion` int DEFAULT NULL COMMENT '异体输血量（ml）',
  `autotransfusion` int DEFAULT NULL COMMENT '自体血回输量（ml）',
  `urine_output` int DEFAULT NULL COMMENT '术中尿量（ml）',
  `blood_loss` int DEFAULT NULL COMMENT '术中出血量（ml）',
  `adverse_event_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否发生麻醉不良事件（0-无 1-有）',
  `adverse_event_note` varchar(1000) DEFAULT NULL COMMENT '不良事件经过与处理',
  `anesthesia_effect` tinyint DEFAULT NULL COMMENT '麻醉效果（1-满意 2-欠佳 3-失败改麻醉方式）',
  `postop_disposition` tinyint DEFAULT NULL COMMENT '术后去向（1-回病房 2-入PACU 3-入ICU）',
  `record_status` tinyint NOT NULL DEFAULT '0' COMMENT '记录状态（0-记录中 1-已提交 2-已审核）',
  `submit_doctor_id` bigint DEFAULT NULL COMMENT '提交人ID（员工ID）',
  `submit_doctor_name` varchar(64) DEFAULT NULL COMMENT '提交人姓名（快照）',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `audit_doctor_id` bigint DEFAULT NULL COMMENT '审核人ID（员工ID）',
  `audit_doctor_name` varchar(64) DEFAULT NULL COMMENT '审核人姓名（快照）',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `charge_status` tinyint NOT NULL DEFAULT '0' COMMENT '计费状态（0-未计费 1-已计费 2-计费异常）',
  `fee_no` varchar(32) DEFAULT NULL COMMENT '记账单号',
  `charged_amount` decimal(12,2) DEFAULT NULL COMMENT '本次计入金额（元）',
  `charge_fail_reason` varchar(500) DEFAULT NULL COMMENT '计费失败原因',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_apply` (`apply_id`),
  UNIQUE KEY `uk_record_no` (`record_no`),
  KEY `idx_record_admission` (`admission_id`),
  KEY `idx_record_status` (`record_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='麻醉记录单';

-- ----------------------------
-- biz_anesthesia_med  麻醉用药记录
-- ----------------------------
CREATE TABLE `biz_anesthesia_med` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `record_id` bigint NOT NULL COMMENT '麻醉记录ID',
  `med_time` datetime NOT NULL COMMENT '给药时刻',
  `med_phase` tinyint DEFAULT NULL COMMENT '用药阶段（1-诱导 2-维持 3-苏醒）',
  `drug_code` varchar(32) DEFAULT NULL COMMENT '药品编码',
  `drug_name` varchar(200) NOT NULL COMMENT '药品名称',
  `dose` decimal(10,2) DEFAULT NULL COMMENT '剂量',
  `unit` varchar(20) DEFAULT NULL COMMENT '剂量单位（mg / ug / ml）',
  `route` tinyint DEFAULT NULL COMMENT '给药途径（1-静脉推注 2-静脉泵注 3-静脉滴注 4-吸入 5-肌注 6-椎管内 7-局麻浸润 8-其他）',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_med_record` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='麻醉用药记录';

-- ----------------------------
-- biz_anesthesia_vital  麻醉期间生命体征
-- ----------------------------
CREATE TABLE `biz_anesthesia_vital` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `record_id` bigint NOT NULL COMMENT '麻醉记录ID',
  `sample_time` datetime NOT NULL COMMENT '采样时刻',
  `systolic` int DEFAULT NULL COMMENT '收缩压（mmHg）',
  `diastolic` int DEFAULT NULL COMMENT '舒张压（mmHg）',
  `heart_rate` int DEFAULT NULL COMMENT '心率（次/分）',
  `respiration` int DEFAULT NULL COMMENT '呼吸频率（次/分）',
  `temperature` decimal(4,1) DEFAULT NULL COMMENT '体温（℃）',
  `spo2` int DEFAULT NULL COMMENT '脉搏血氧饱和度（%）',
  `etco2` int DEFAULT NULL COMMENT '呼气末二氧化碳分压（mmHg）',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_vital_time` (`record_id`,`sample_time`),
  KEY `idx_vital_record` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='麻醉期间生命体征';

-- ----------------------------
-- biz_anesthesia_pacu  PACU 复苏记录
-- ----------------------------
CREATE TABLE `biz_anesthesia_pacu` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `pacu_no` varchar(32) NOT NULL COMMENT '复苏单号',
  `record_id` bigint NOT NULL COMMENT '麻醉记录ID',
  `record_no` varchar(32) DEFAULT NULL COMMENT '麻醉记录单号（快照）',
  `apply_id` bigint NOT NULL COMMENT '手术申请单ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（快照）（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `enter_time` datetime DEFAULT NULL COMMENT '入 PACU 时间',
  `leave_time` datetime DEFAULT NULL COMMENT '出 PACU 时间',
  `nurse_id` bigint DEFAULT NULL COMMENT '复苏护士ID（员工ID）',
  `nurse_name` varchar(64) DEFAULT NULL COMMENT '复苏护士姓名（快照）',
  `anesthetist_id` bigint DEFAULT NULL COMMENT '负责麻醉医师ID（员工ID）',
  `anesthetist_name` varchar(64) DEFAULT NULL COMMENT '负责麻醉医师姓名（快照）',
  `score_activity` tinyint DEFAULT NULL COMMENT '肌力/活动（0-无 1-两肢可动 2-四肢可动）',
  `score_respiration` tinyint DEFAULT NULL COMMENT '呼吸（0-需辅助通气 1-呼吸浅 2-深呼吸可咳嗽）',
  `score_circulation` tinyint DEFAULT NULL COMMENT '血压（0-±50mmHg以上波动 1-±20~50 2-±20）',
  `score_consciousness` tinyint DEFAULT NULL COMMENT '意识（0-无反应 1-可唤醒 2-完全清醒）',
  `score_spo2` tinyint DEFAULT NULL COMMENT '氧合（0-吸氧下<90% 1-吸氧下>90% 2-空气下>92%）',
  `aldrete_total` tinyint DEFAULT NULL COMMENT 'Aldrete 总分',
  `awareness` tinyint DEFAULT NULL COMMENT '清醒程度（1-完全清醒 2-嗜睡可唤醒 3-未清醒）',
  `complication_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否发生并发症（0-无 1-有）',
  `complication_note` varchar(1000) DEFAULT NULL COMMENT '并发症经过与处理',
  `oxygen_therapy` varchar(200) DEFAULT NULL COMMENT '氧疗方式',
  `analgesia` varchar(200) DEFAULT NULL COMMENT '镇痛方式',
  `disposition` tinyint DEFAULT NULL COMMENT '出室去向（1-回病房 2-转ICU 3-继续留观）',
  `leave_criteria_met` tinyint DEFAULT NULL COMMENT '是否满足出室标准（0-否 1-是）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0-在室 1-已出室）',
  `charge_status` tinyint NOT NULL DEFAULT '0' COMMENT '计费状态（0-未计费 1-已计费 2-计费失败）',
  `fee_no` varchar(32) DEFAULT NULL COMMENT '记账单号',
  `charged_amount` decimal(12,2) DEFAULT NULL COMMENT '本次计入金额（元）',
  `charge_fail_reason` varchar(500) DEFAULT NULL COMMENT '计费失败原因',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pacu_record` (`record_id`),
  UNIQUE KEY `uk_pacu_no` (`pacu_no`),
  KEY `idx_pacu_apply` (`apply_id`),
  KEY `idx_pacu_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='PACU 复苏记录';

-- ----------------------------
-- biz_anesthesia_followup  麻醉术后随访单
-- ----------------------------
CREATE TABLE `biz_anesthesia_followup` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `followup_no` varchar(32) NOT NULL COMMENT '随访单号',
  `record_id` bigint NOT NULL COMMENT '麻醉记录ID',
  `record_no` varchar(32) DEFAULT NULL COMMENT '麻醉记录单号（快照）',
  `apply_id` bigint DEFAULT NULL COMMENT '手术申请单ID（快照）',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（快照）（1-男 2-女）',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `followup_time` datetime NOT NULL COMMENT '随访时间',
  `round_no` tinyint NOT NULL DEFAULT '1' COMMENT '随访轮次（1-术后即刻 2-24h 3-48h及以后）',
  `pain_score` int DEFAULT NULL COMMENT '疼痛评分 NRS 0~10',
  `recovery` tinyint DEFAULT NULL COMMENT '麻醉恢复情况（1-良好 2-一般 3-差）',
  `adverse_items` varchar(200) DEFAULT NULL COMMENT '麻醉并发症码值',
  `adverse_note` varchar(1000) DEFAULT NULL COMMENT '并发症经过描述',
  `handling` varchar(1000) DEFAULT NULL COMMENT '处理措施与转归',
  `followup_status` tinyint NOT NULL DEFAULT '0' COMMENT '状态（0-草稿 1-已完成）',
  `followup_doctor_id` bigint DEFAULT NULL COMMENT '随访麻醉医师ID（员工ID）',
  `followup_doctor_name` varchar(64) DEFAULT NULL COMMENT '随访麻醉医师姓名（快照）',
  `finish_time` datetime DEFAULT NULL COMMENT '随访完成时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_followup_no` (`followup_no`),
  KEY `idx_followup_record` (`record_id`),
  KEY `idx_followup_status` (`followup_status`),
  KEY `idx_followup_time` (`followup_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='麻醉术后随访单';

-- ----------------------------
-- biz_operation_charge_item  手术麻醉计费明细
-- ----------------------------
CREATE TABLE `biz_operation_charge_item` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `apply_id` bigint NOT NULL COMMENT '手术申请单ID',
  `apply_no` varchar(32) DEFAULT NULL COMMENT '手术申请单号（快照）',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(64) DEFAULT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名（快照）',
  `source_type` tinyint NOT NULL COMMENT '收费来源（预留）（1-麻醉记录 2-PACU复苏 3-手术）',
  `source_id` bigint NOT NULL COMMENT '来源单据ID',
  `source_no` varchar(32) DEFAULT NULL COMMENT '来源单据号（快照）',
  `item_code` varchar(32) NOT NULL COMMENT '收费项目编码',
  `item_name` varchar(200) DEFAULT NULL COMMENT '收费项目名称（快照）',
  `item_type` tinyint DEFAULT NULL COMMENT '项目类型',
  `spec` varchar(100) DEFAULT NULL COMMENT '规格',
  `unit` varchar(20) DEFAULT NULL COMMENT '计价单位',
  `quantity` decimal(12,2) DEFAULT NULL COMMENT '数量',
  `price` decimal(12,2) DEFAULT NULL COMMENT '单价',
  `amount` decimal(12,2) DEFAULT NULL COMMENT '金额',
  `charge_status` tinyint NOT NULL DEFAULT '0' COMMENT '计费状态（0-未计费 1-已计费 2-计费失败）',
  `fee_record_id` bigint DEFAULT NULL COMMENT '记账行ID',
  `fee_no` varchar(32) DEFAULT NULL COMMENT '记账单号',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '失败原因（未发现项目 / 金额异常 / 收费模块缺席）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_charge_src` (`source_type`,`source_id`,`item_code`),
  KEY `idx_oci_apply` (`apply_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='手术麻醉计费明细';

-- ----------------------------
-- biz_day_surgery_item  日间手术准入目录
-- ----------------------------
CREATE TABLE `biz_day_surgery_item` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `item_code` varchar(32) NOT NULL COMMENT '术式编码',
  `item_name` varchar(128) NOT NULL COMMENT '术式名称',
  `dept_id` bigint DEFAULT NULL COMMENT '适用科室ID',
  `dept_name` varchar(128) DEFAULT NULL COMMENT '适用科室名称（快照）',
  `max_stay_hours` int NOT NULL DEFAULT '48' COMMENT '最长滞留小时数',
  `operation_level` tinyint NOT NULL DEFAULT '2' COMMENT '手术级别',
  `anesthesia_type` tinyint DEFAULT NULL COMMENT '麻醉方式（1-局部麻醉 2-椎管内麻醉 3-全身麻醉 4-神经阻滞 5-其他）',
  `standard_fee` decimal(10,2) DEFAULT NULL COMMENT '标准费用',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-启用 0-停用）',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dsitem_code` (`item_code`),
  KEY `idx_dsitem_dept` (`dept_id`),
  KEY `idx_dsitem_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='日间手术准入目录';

-- ----------------------------
-- biz_day_surgery_apply  日间手术登记单
-- ----------------------------
CREATE TABLE `biz_day_surgery_apply` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `apply_no` varchar(32) NOT NULL COMMENT '登记单号',
  `item_id` bigint NOT NULL COMMENT '准入术式ID',
  `item_code` varchar(32) DEFAULT NULL COMMENT '术式编码（快照）',
  `item_name` varchar(128) DEFAULT NULL COMMENT '术式名称（快照）',
  `max_stay_hours` int DEFAULT NULL COMMENT '最长滞留小时数',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(64) DEFAULT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(128) DEFAULT NULL COMMENT '患者姓名（快照）',
  `dept_id` bigint DEFAULT NULL COMMENT '手术科室ID',
  `dept_name` varchar(128) DEFAULT NULL COMMENT '手术科室名称（快照）',
  `doctor_id` bigint DEFAULT NULL COMMENT '手术医生ID（员工ID）',
  `doctor_name` varchar(64) DEFAULT NULL COMMENT '手术医生姓名',
  `plan_surgery_date` date NOT NULL COMMENT '计划手术日期',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-待评估 2-评估通过 3-已安排 4-术后观察 5-已出院 6-已取消 7-已转住院）',
  `eval_result` tinyint DEFAULT NULL COMMENT '术前评估结论（1-通过 2-不通过）',
  `eval_by` varchar(64) DEFAULT NULL COMMENT '评估人',
  `eval_time` datetime DEFAULT NULL COMMENT '评估时间',
  `eval_remark` varchar(500) DEFAULT NULL COMMENT '评估意见/禁忌筛查结果',
  `surgery_time` datetime DEFAULT NULL COMMENT '手术开始时间',
  `operating_room` varchar(64) DEFAULT NULL COMMENT '手术间',
  `seq_no` int DEFAULT NULL COMMENT '台次',
  `anesthesia_type` tinyint DEFAULT NULL COMMENT '实际麻醉方式',
  `surgeon` varchar(64) DEFAULT NULL COMMENT '主刀医生姓名',
  `arrange_by` varchar(64) DEFAULT NULL COMMENT '安排人',
  `arrange_time` datetime DEFAULT NULL COMMENT '安排时间',
  `surgery_end_time` datetime DEFAULT NULL COMMENT '手术结束时间',
  `leave_type` tinyint DEFAULT NULL COMMENT '离院方式（1-按时离院 2-转普通住院 3-非计划再入院）',
  `discharge_time` datetime DEFAULT NULL COMMENT '离院时间',
  `discharge_by` varchar(64) DEFAULT NULL COMMENT '离院登记人',
  `discharge_remark` varchar(500) DEFAULT NULL COMMENT '出院评估结论/医嘱交代',
  `transfer_admission_id` bigint DEFAULT NULL COMMENT '转住院的住院ID',
  `transfer_remark` varchar(500) DEFAULT NULL COMMENT '转住院原因',
  `follow_count` int NOT NULL DEFAULT '0' COMMENT '随访次数',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dsapply_no` (`apply_no`),
  KEY `idx_dsapply_patient` (`patient_id`),
  KEY `idx_dsapply_status` (`status`),
  KEY `idx_dsapply_item` (`item_id`),
  KEY `idx_dsapply_date` (`plan_surgery_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='日间手术登记单';

-- ----------------------------
-- biz_day_surgery_follow  日间手术随访台账
-- ----------------------------
CREATE TABLE `biz_day_surgery_follow` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `apply_id` bigint NOT NULL COMMENT '登记单ID',
  `follow_type` tinyint NOT NULL DEFAULT '1' COMMENT '随访方式（1-电话 2-门诊 3-上门 4-线上）',
  `result` tinyint NOT NULL COMMENT '随访结果（1-无异常 2-有异常已处置 3-有异常再就诊 4-失联）',
  `content` varchar(500) DEFAULT NULL COMMENT '随访内容',
  `operator_id` bigint DEFAULT NULL COMMENT '随访人（员工ID）',
  `operator` varchar(64) DEFAULT NULL COMMENT '随访人姓名',
  `follow_time` datetime DEFAULT NULL COMMENT '随访时间',
  `create_by` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_dsfollow_apply` (`apply_id`),
  KEY `idx_dsfollow_time` (`follow_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='日间手术随访台账';
