-- 领域：15-输血与血库
-- 库：hn_biz_his    表数：6
-- 说明：DDL 快照（由线上库 SHOW CREATE TABLE 导出，无 DROP / 无数据）。建表语句彼此独立，不含外键约束。

-- ----------------------------
-- biz_transfusion_apply  输血申请单
-- ----------------------------
CREATE TABLE `biz_transfusion_apply`
(
    `id`                     bigint       NOT NULL COMMENT '输血申请单ID（雪花）',
    `apply_no`               varchar(32)  NOT NULL COMMENT '输血申请单号',
    `admission_id`           bigint       NOT NULL COMMENT '入院ID',
    `admission_no`           varchar(32)           DEFAULT NULL COMMENT '入院号（快照）',
    `patient_id`             bigint       NOT NULL COMMENT '患者ID',
    `patient_no`             varchar(32)           DEFAULT NULL COMMENT '患者号（快照）',
    `patient_name`           varchar(50)           DEFAULT NULL COMMENT '患者姓名（快照）',
    `gender`                 tinyint               DEFAULT NULL COMMENT '性别（快照）（1-男 2-女）',
    `age`                    int                   DEFAULT NULL COMMENT '年龄（快照）',
    `apply_dept_id`          bigint                DEFAULT NULL COMMENT '申请科室ID',
    `apply_dept_name`        varchar(64)           DEFAULT NULL COMMENT '申请科室名称（快照）',
    `apply_ward_name`        varchar(64)           DEFAULT NULL COMMENT '申请时所在病区名称（快照）',
    `apply_bed_no`           varchar(32)           DEFAULT NULL COMMENT '申请时床号（快照）',
    `apply_doctor_id`        bigint                DEFAULT NULL COMMENT '申请医生ID',
    `apply_doctor_name`      varchar(64)           DEFAULT NULL COMMENT '申请医生姓名（快照）',
    `apply_time`             datetime              DEFAULT NULL COMMENT '申请时间',
    `patient_abo`            varchar(4)   NOT NULL COMMENT '受血者ABO血型',
    `patient_rh`             varchar(4)   NOT NULL COMMENT '受血者Rh血型',
    `blood_component`        tinyint      NOT NULL COMMENT '血液品种（1-红细胞悬液 2-血浆 3-血小板 4-冷沉淀 5-全血 6-其他）',
    `component_spec`         varchar(64)           DEFAULT NULL COMMENT '规格',
    `bag_count`              int          NOT NULL DEFAULT '1' COMMENT '申请袋数',
    `planned_amount`         decimal(10, 2)        DEFAULT NULL COMMENT '申请总量',
    `amount_ml`              int                   DEFAULT NULL COMMENT '申请量折算毫升数',
    `approve_level`          tinyint      NOT NULL DEFAULT '1' COMMENT '审批级别（1-上级医师 400-799ml）',
    `approve_status`         tinyint      NOT NULL DEFAULT '0' COMMENT '审批状态（0-待审批 1-已通过 2-已驳回 3-急诊待补审）',
    `approve_reject_reason`  varchar(200)          DEFAULT NULL COMMENT '最近一次驳回原因',
    `approve_time`           datetime              DEFAULT NULL COMMENT '审批通过时间',
    `approve_makeup`         tinyint      NOT NULL DEFAULT '0' COMMENT '是否急诊补审（0-常规审批 1-急诊后补）',
    `amount_unit`            varchar(16)           DEFAULT NULL COMMENT '总量单位',
    `transfusion_purpose`    varchar(200)          DEFAULT NULL COMMENT '输血目的（纠正贫血/补充凝血因子/提升血小板…）',
    `indication`             varchar(500) NOT NULL COMMENT '输血指征（Hb/HCT/PLT 指标 + 临床症状，缺了就是无指征用血）',
    `pre_hb`                 decimal(6, 2)         DEFAULT NULL COMMENT '输血前血红蛋白 Hb（g/L）',
    `pre_hct`                decimal(5, 2)         DEFAULT NULL COMMENT '输血前红细胞压积 HCT（%）',
    `pre_plt`                int                   DEFAULT NULL COMMENT '输血前血小板 PLT',
    `transfusion_history`    varchar(500)          DEFAULT NULL COMMENT '既往输血史',
    `reaction_history`       varchar(500)          DEFAULT NULL COMMENT '既往输血反应史',
    `pregnancy_history`      varchar(200)          DEFAULT NULL COMMENT '妊娠史',
    `is_emergency`           tinyint      NOT NULL DEFAULT '0' COMMENT '是否紧急用血（0-否 1-是）',
    `crossmatch_status`      tinyint      NOT NULL DEFAULT '0' COMMENT '配血状态（0-待配血 1-配血中 3-存在配血不合）',
    `crossmatch_doctor_id`   bigint                DEFAULT NULL COMMENT '配血人ID',
    `crossmatch_doctor_name` varchar(64)           DEFAULT NULL COMMENT '配血人姓名（快照）',
    `crossmatch_time`        datetime              DEFAULT NULL COMMENT '配血完成时间',
    `issue_doctor_id`        bigint                DEFAULT NULL COMMENT '发血人ID（员工ID）',
    `issue_doctor_name`      varchar(64)           DEFAULT NULL COMMENT '发血人姓名（快照）',
    `issue_time`             datetime              DEFAULT NULL COMMENT '发血时间',
    `check_items`            varchar(200)          DEFAULT NULL COMMENT '输血前核对要点码',
    `check_note`             varchar(1000)         DEFAULT NULL COMMENT '核对补充说明',
    `check_nurse_id`         bigint                DEFAULT NULL COMMENT '核对护士1 ID（员工ID）',
    `check_nurse_name`       varchar(64)           DEFAULT NULL COMMENT '核对护士1 姓名（快照）',
    `check_nurse2_id`        bigint                DEFAULT NULL COMMENT '核对护士2 ID',
    `check_nurse2_name`      varchar(64)           DEFAULT NULL COMMENT '核对护士2 姓名（快照）',
    `check_time`             datetime              DEFAULT NULL COMMENT '双人核对时间',
    `infusion_nurse_id`      bigint                DEFAULT NULL COMMENT '输注执行护士ID（员工ID）',
    `infusion_nurse_name`    varchar(64)           DEFAULT NULL COMMENT '输注执行护士姓名（快照）',
    `infusion_start_time`    datetime              DEFAULT NULL COMMENT '输注开始时间',
    `infusion_end_time`      datetime              DEFAULT NULL COMMENT '输注结束时间',
    `actual_amount`          decimal(10, 2)        DEFAULT NULL COMMENT '实际输注量',
    `infusion_speed`         varchar(32)           DEFAULT NULL COMMENT '滴速',
    `observation`            varchar(1000)         DEFAULT NULL COMMENT '输注过程观察',
    `has_reaction`           tinyint      NOT NULL DEFAULT '0' COMMENT '有无输血反应（0-未上报 1-已上报有反应）',
    `reaction_type`          varchar(100)          DEFAULT NULL COMMENT '反应类型',
    `reaction_desc`          varchar(1000)         DEFAULT NULL COMMENT '反应描述',
    `reaction_handle`        varchar(1000)         DEFAULT NULL COMMENT '处理措施',
    `reaction_reporter_id`   bigint                DEFAULT NULL COMMENT '上报人ID（员工ID）',
    `reaction_reporter_name` varchar(64)           DEFAULT NULL COMMENT '上报人姓名（快照）',
    `reaction_time`          datetime              DEFAULT NULL COMMENT '上报时间',
    `efficacy_eval`          varchar(1000)         DEFAULT NULL COMMENT '输注后疗效评估',
    `post_hb`                decimal(6, 2)         DEFAULT NULL COMMENT '输血后血红蛋白 Hb（g/L）',
    `post_hct`               decimal(5, 2)         DEFAULT NULL COMMENT '输血后红细胞压积 HCT（%）',
    `post_plt`               int                   DEFAULT NULL COMMENT '输血后血小板 PLT',
    `finish_doctor_id`       bigint                DEFAULT NULL COMMENT '完成录入人ID（员工ID）',
    `finish_doctor_name`     varchar(64)           DEFAULT NULL COMMENT '完成录入人姓名（快照）',
    `finish_time`            datetime              DEFAULT NULL COMMENT '完成时间',
    `record_id`              bigint                DEFAULT NULL COMMENT '回写住院病历ID',
    `transfusion_status`     tinyint      NOT NULL DEFAULT '0' COMMENT '状态（0-待配血 1-已配血 2-已发血 3-输注中 4-已完成 5-已取消）',
    `cancel_reason`          varchar(500)          DEFAULT NULL COMMENT '取消原因（仅待配血/已配血/已发血可取消）',
    `cancel_doctor_id`       bigint                DEFAULT NULL COMMENT '取消人ID（员工ID）',
    `cancel_doctor_name`     varchar(64)           DEFAULT NULL COMMENT '取消人姓名（快照）',
    `cancel_time`            datetime              DEFAULT NULL COMMENT '取消时间',
    `remark`                 varchar(500)          DEFAULT NULL COMMENT '备注',
    `create_by`              varchar(64)  NOT NULL COMMENT '创建人',
    `create_by_id`           bigint                DEFAULT NULL COMMENT '创建人ID',
    `create_time`            datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by`              varchar(64)  NOT NULL COMMENT '更新人',
    `update_by_id`           bigint                DEFAULT NULL COMMENT '更新人ID',
    `update_time`            datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag`               tinyint      NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
    PRIMARY KEY (`id`),
    KEY                      `idx_tf_admission` (`admission_id`),
    KEY                      `idx_tf_status` (`transfusion_status`),
    KEY                      `idx_tf_crossmatch` (`crossmatch_status`),
    KEY                      `idx_tf_patient` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='输血申请单';

-- ----------------------------
-- biz_transfusion_approve  用血分级审批流水
-- ----------------------------
CREATE TABLE `biz_transfusion_approve`
(
    `id`             bigint      NOT NULL COMMENT '审批记录ID（雪花）',
    `apply_id`       bigint      NOT NULL COMMENT '输血申请单ID',
    `apply_no`       varchar(32)          DEFAULT NULL COMMENT '输血申请单号',
    `approve_level`  tinyint     NOT NULL COMMENT '审批级别（1-上级医师 2-科主任 3-医务科）',
    `approve_result` tinyint     NOT NULL COMMENT '审批结论（1-通过 2-驳回）',
    `approver_id`    bigint               DEFAULT NULL COMMENT '审批人ID（员工ID）',
    `approver_name`  varchar(64)          DEFAULT NULL COMMENT '审批人姓名（快照）',
    `approver_title` varchar(32)          DEFAULT NULL COMMENT '审批人职称',
    `opinion`        varchar(200)         DEFAULT NULL COMMENT '审批意见',
    `is_makeup`      tinyint     NOT NULL DEFAULT '0' COMMENT '是否急诊补审（0-常规 1-补审）',
    `remark`         varchar(500)         DEFAULT NULL COMMENT '备注',
    `create_by`      varchar(64) NOT NULL COMMENT '创建人',
    `create_by_id`   bigint               DEFAULT NULL COMMENT '创建人ID',
    `create_time`    datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by`      varchar(64) NOT NULL COMMENT '更新人',
    `update_by_id`   bigint               DEFAULT NULL COMMENT '更新人ID',
    `update_time`    datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag`       tinyint     NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
    PRIMARY KEY (`id`),
    KEY              `idx_ta_apply` (`apply_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用血分级审批流水';

-- ----------------------------
-- biz_transfusion_bag  输血血袋明细
-- ----------------------------
CREATE TABLE `biz_transfusion_bag`
(
    `id`                     bigint      NOT NULL COMMENT '血袋明细ID（雪花）',
    `apply_id`               bigint      NOT NULL COMMENT '输血申请单ID',
    `admission_id`           bigint      NOT NULL COMMENT '入院ID',
    `patient_id`             bigint               DEFAULT NULL COMMENT '患者ID（冗余）',
    `bag_no`                 varchar(64) NOT NULL COMMENT '血袋号',
    `donor_no`               varchar(64)          DEFAULT NULL COMMENT '献血编号',
    `bag_abo`                varchar(4)  NOT NULL COMMENT '血袋ABO血型',
    `bag_rh`                 varchar(4)  NOT NULL COMMENT '血袋Rh血型',
    `blood_component`        tinyint              DEFAULT NULL COMMENT '血液品种',
    `spec`                   varchar(64)          DEFAULT NULL COMMENT '规格',
    `amount`                 decimal(10, 2)       DEFAULT NULL COMMENT '血量',
    `amount_unit`            varchar(16)          DEFAULT NULL COMMENT '血量单位',
    `source_bank`            varchar(100)         DEFAULT NULL COMMENT '来源血站',
    `collect_date`           date                 DEFAULT NULL COMMENT '采集日期',
    `expire_date`            date                 DEFAULT NULL COMMENT '有效期至',
    `crossmatch_main`        varchar(16)          DEFAULT NULL COMMENT '主侧配血结果（阴性=相合）',
    `crossmatch_side`        varchar(16)          DEFAULT NULL COMMENT '次侧配血结果',
    `crossmatch_result`      tinyint              DEFAULT NULL COMMENT '配血结论（1-相合 2-不合）',
    `crossmatch_time`        datetime             DEFAULT NULL COMMENT '配血时间',
    `crossmatch_doctor_id`   bigint               DEFAULT NULL COMMENT '配血人ID（员工ID）',
    `crossmatch_doctor_name` varchar(64)          DEFAULT NULL COMMENT '配血人姓名（快照）',
    `bag_status`             tinyint     NOT NULL DEFAULT '0' COMMENT '血袋状态（0-待配血 1-已配血 2-已发血 3-已输注）',
    `issue_time`             datetime             DEFAULT NULL COMMENT '发血时间',
    `remark`                 varchar(500)         DEFAULT NULL COMMENT '备注',
    `create_by`              varchar(64) NOT NULL COMMENT '创建人',
    `create_by_id`           bigint               DEFAULT NULL COMMENT '创建人ID',
    `create_time`            datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by`              varchar(64) NOT NULL COMMENT '更新人',
    `update_by_id`           bigint               DEFAULT NULL COMMENT '更新人ID',
    `update_time`            datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag`               tinyint     NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
    PRIMARY KEY (`id`),
    KEY                      `idx_tfb_apply` (`apply_id`),
    KEY                      `idx_tfb_bag_no` (`bag_no`),
    KEY                      `idx_tfb_admission` (`admission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='输血血袋明细';

-- ----------------------------
-- biz_blood_inventory  血库血袋库存
-- ----------------------------
CREATE TABLE `biz_blood_inventory`
(
    `id`             bigint      NOT NULL COMMENT '主键ID',
    `bag_no`         varchar(50) NOT NULL COMMENT '血袋号（唯一）',
    `blood_type`     tinyint     NOT NULL COMMENT '血型（1-A 2-B 3-O 4-AB）',
    `rh_type`        tinyint              DEFAULT '1' COMMENT 'Rh 血型（1-阳性 2-阴性）',
    `component_type` tinyint     NOT NULL COMMENT '血液成分（1-全血 2-红细胞悬液 3-洗涤红细胞 4-冰冻血浆 5-血小板 6-冷沉淀）',
    `volume`         int                  DEFAULT '0' COMMENT '血量（ml）',
    `unit_amount`    decimal(6, 2)        DEFAULT '0.00' COMMENT '单位（U）',
    `collect_date`   date                 DEFAULT NULL COMMENT '采集日期',
    `expire_date`    date                 DEFAULT NULL COMMENT '失效日期',
    `source_type`    tinyint              DEFAULT '1' COMMENT '血液来源（1-血站 2-自体储血 3-互助献血）',
    `source_name`    varchar(100)         DEFAULT NULL COMMENT '来源单位 / 献血人',
    `donor_no`       varchar(50)          DEFAULT NULL COMMENT '献血码',
    `abo_verify`     tinyint              DEFAULT '0' COMMENT '血型复核（0-未复核 1-已复核）',
    `storage_loc`    varchar(100)         DEFAULT NULL COMMENT '存放位置',
    `status`         tinyint              DEFAULT '1' COMMENT '状态（1-在库 2-已预留 3-已发血 4-已报废 5-已退回）',
    `inbound_by`     varchar(64)          DEFAULT NULL COMMENT '入库人',
    `inbound_time`   datetime             DEFAULT NULL COMMENT '入库时间',
    `outbound_by`    varchar(64)          DEFAULT NULL COMMENT '出库人',
    `outbound_time`  datetime             DEFAULT NULL COMMENT '出库时间',
    `apply_no`       varchar(32)          DEFAULT NULL COMMENT '关联用血申请单号',
    `create_by`      varchar(64) NOT NULL COMMENT '创建人',
    `create_by_id`   bigint               DEFAULT NULL COMMENT '创建人ID',
    `create_time`    datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by`      varchar(64) NOT NULL COMMENT '更新人',
    `update_by_id`   bigint               DEFAULT NULL COMMENT '更新人ID',
    `update_time`    datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag`       tinyint              DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
    `remark`         varchar(500)         DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_bag_no` (`bag_no`),
    KEY              `idx_blood_type` (`blood_type`),
    KEY              `idx_status` (`status`),
    KEY              `idx_expire_date` (`expire_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='血库血袋库存';

-- ----------------------------
-- biz_blood_crossmatch  交叉配血记录
-- ----------------------------
CREATE TABLE `biz_blood_crossmatch`
(
    `id`                 bigint      NOT NULL COMMENT '主键ID',
    `match_no`           varchar(32) NOT NULL COMMENT '配血编号',
    `apply_no`           varchar(32)          DEFAULT NULL COMMENT '用血申请单号',
    `patient_id`         bigint               DEFAULT NULL COMMENT '患者ID',
    `patient_no`         varchar(32)          DEFAULT NULL COMMENT '患者号',
    `patient_name`       varchar(50)          DEFAULT NULL COMMENT '患者姓名',
    `patient_blood_type` tinyint              DEFAULT NULL COMMENT '患者血型（1-A 2-B 3-O 4-AB）',
    `patient_rh_type`    tinyint              DEFAULT NULL COMMENT '患者 Rh（1-阳性 2-阴性）',
    `bag_no`             varchar(50) NOT NULL COMMENT '血袋号',
    `bag_blood_type`     tinyint              DEFAULT NULL COMMENT '血袋血型',
    `bag_rh_type`        tinyint              DEFAULT NULL COMMENT '血袋 Rh',
    `component_type`     tinyint              DEFAULT NULL COMMENT '血液成分',
    `volume`             int                  DEFAULT '0' COMMENT '血量（ml）',
    `method`             tinyint              DEFAULT '2' COMMENT '配血方法（1-盐水法 2-凝聚胺法 3-抗人球蛋白法 4-微柱凝胶法）',
    `result`             tinyint              DEFAULT '1' COMMENT '配血结果（1-相合 2-不相合 3-可疑凝集）',
    `conclusion`         varchar(500)         DEFAULT NULL COMMENT '配血结论',
    `status`             tinyint              DEFAULT '1' COMMENT '状态（1-待配血 2-已配血 3-已复核 4-已作废）',
    `operator`           varchar(64)          DEFAULT NULL COMMENT '配血人',
    `match_time`         datetime             DEFAULT NULL COMMENT '配血时间',
    `verifier`           varchar(64)          DEFAULT NULL COMMENT '复核人',
    `verify_time`        datetime             DEFAULT NULL COMMENT '复核时间',
    `create_by`          varchar(64) NOT NULL COMMENT '创建人',
    `create_by_id`       bigint               DEFAULT NULL COMMENT '创建人ID',
    `create_time`        datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by`          varchar(64) NOT NULL COMMENT '更新人',
    `update_by_id`       bigint               DEFAULT NULL COMMENT '更新人ID',
    `update_time`        datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag`           tinyint              DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
    `remark`             varchar(500)         DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_match_no` (`match_no`),
    KEY                  `idx_apply_no` (`apply_no`),
    KEY                  `idx_bag_no` (`bag_no`),
    KEY                  `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='交叉配血记录';

-- ----------------------------
-- biz_blood_stock_log  血库出入库流水
-- ----------------------------
CREATE TABLE `biz_blood_stock_log`
(
    `id`           bigint      NOT NULL COMMENT '主键ID',
    `bag_no`       varchar(50) NOT NULL COMMENT '血袋号',
    `biz_type`     tinyint     NOT NULL COMMENT '业务类型（1-入库 2-发血 3-退回 4-报废 5-预留 6-取消预留）',
    `from_status`  tinyint              DEFAULT NULL COMMENT '变更前状态',
    `to_status`    tinyint              DEFAULT NULL COMMENT '变更后状态',
    `apply_no`     varchar(32)          DEFAULT NULL COMMENT '关联用血申请单号',
    `reason`       varchar(500)         DEFAULT NULL COMMENT '原因',
    `operator`     varchar(64)          DEFAULT NULL COMMENT '操作人',
    `operate_time` datetime             DEFAULT NULL COMMENT '操作时间',
    `create_by`    varchar(64) NOT NULL COMMENT '创建人',
    `create_by_id` bigint               DEFAULT NULL COMMENT '创建人ID',
    `create_time`  datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by`    varchar(64) NOT NULL COMMENT '更新人',
    `update_by_id` bigint               DEFAULT NULL COMMENT '更新人ID',
    `update_time`  datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    `del_flag`     tinyint              DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
    `remark`       varchar(500)         DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    KEY            `idx_bag_no` (`bag_no`),
    KEY            `idx_biz_type` (`biz_type`),
    KEY            `idx_operate_time` (`operate_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='血库出入库流水';
