-- 领域：20-院感·公卫·医疗安全与死亡登记
-- 库：hn_biz_his    表数：13
-- 说明：DDL 快照（由线上库 SHOW CREATE TABLE 导出，无 DROP / 无数据）。建表语句彼此独立，不含外键约束。

-- ----------------------------
-- biz_infection_case  院感病例报告卡
-- ----------------------------
CREATE TABLE `biz_infection_case` (
  `id` bigint NOT NULL COMMENT '主键',
  `case_no` varchar(32) NOT NULL COMMENT '病例编号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `visit_type` tinyint NOT NULL COMMENT '就诊类型',
  `regist_id` bigint DEFAULT NULL COMMENT '门诊就诊ID',
  `inp_id` bigint DEFAULT NULL COMMENT '住院记录ID',
  `dept_id` bigint DEFAULT NULL COMMENT '发现科室ID（快照）',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '发现科室（快照）',
  `case_source` tinyint NOT NULL COMMENT '感染来源',
  `infection_site` varchar(8) NOT NULL COMMENT '感染部位',
  `infection_diag` varchar(200) NOT NULL COMMENT '感染诊断',
  `pathogen` varchar(100) DEFAULT NULL COMMENT '病原菌',
  `specimen` varchar(100) DEFAULT NULL COMMENT '标本来源',
  `infect_date` date NOT NULL COMMENT '感染/诊断日期',
  `case_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `leak_flag` tinyint NOT NULL DEFAULT '0' COMMENT '漏报标志',
  `report_by` bigint NOT NULL COMMENT '上报人ID',
  `report_name` varchar(50) NOT NULL COMMENT '上报人姓名（快照）',
  `report_time` datetime NOT NULL COMMENT '上报时间',
  `audit_name` varchar(50) DEFAULT NULL COMMENT '核实人',
  `audit_time` datetime DEFAULT NULL COMMENT '核实时间',
  `audit_remark` varchar(200) DEFAULT NULL COMMENT '核实意见',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记',
  `remark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_infection_case_no` (`case_no`),
  KEY `idx_infection_case_status` (`case_status`),
  KEY `idx_infection_case_patient` (`patient_id`),
  KEY `idx_infection_case_infect_date` (`infect_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='院感病例报告卡';

-- ----------------------------
-- biz_infection_monitor  院感目标性监测登记
-- ----------------------------
CREATE TABLE `biz_infection_monitor` (
  `id` bigint NOT NULL COMMENT '主键',
  `monitor_no` varchar(32) NOT NULL COMMENT '监测编号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名（快照）',
  `monitor_type` tinyint NOT NULL COMMENT '监测类型',
  `dept_id` bigint DEFAULT NULL COMMENT '监测科室ID',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '监测科室（快照）',
  `insert_date` date NOT NULL COMMENT '置入日期',
  `remove_date` date DEFAULT NULL COMMENT '拔除日期',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `infection_flag` tinyint NOT NULL DEFAULT '0' COMMENT '感染确认',
  `infection_date` date DEFAULT NULL COMMENT '感染日期',
  `infection_site` varchar(8) DEFAULT NULL COMMENT '感染部位',
  `infection_diag` varchar(200) DEFAULT NULL COMMENT '感染诊断',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记',
  `remark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_infection_monitor_no` (`monitor_no`),
  KEY `idx_infection_monitor_type` (`monitor_type`),
  KEY `idx_infection_monitor_status` (`status`),
  KEY `idx_infection_monitor_patient` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='院感目标性监测登记';

-- ----------------------------
-- biz_infection_monitor_daily  监测每日打卡
-- ----------------------------
CREATE TABLE `biz_infection_monitor_daily` (
  `id` bigint NOT NULL COMMENT '主键',
  `monitor_id` bigint NOT NULL COMMENT '监测登记ID',
  `monitor_date` date NOT NULL COMMENT '监测日期',
  `recorder_id` bigint NOT NULL COMMENT '记录人ID',
  `recorder_name` varchar(50) NOT NULL COMMENT '记录人姓名（快照）',
  `record_time` datetime NOT NULL COMMENT '记录时间',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记',
  `remark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_monitor_daily_mid` (`monitor_id`),
  KEY `idx_monitor_daily_date` (`monitor_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='监测每日打卡';

-- ----------------------------
-- biz_hand_hygiene_obs  手卫生依从性观察记录
-- ----------------------------
CREATE TABLE `biz_hand_hygiene_obs` (
  `id` bigint NOT NULL COMMENT '主键',
  `obs_date` date NOT NULL COMMENT '观察日期',
  `dept_id` bigint NOT NULL COMMENT '被观察科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '被观察科室（快照）',
  `obs_object` tinyint NOT NULL COMMENT '观察对象',
  `opportunity_count` int NOT NULL COMMENT '手卫生时机数',
  `comply_count` int NOT NULL COMMENT '实际执行数',
  `observer_id` bigint NOT NULL COMMENT '观察人ID',
  `observer_name` varchar(50) NOT NULL COMMENT '观察人姓名（快照）',
  `obs_time` datetime NOT NULL COMMENT '观察登记时间',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记',
  `remark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_hand_obs_date` (`obs_date`),
  KEY `idx_hand_obs_dept` (`dept_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='手卫生依从性观察记录';

-- ----------------------------
-- biz_infectious_report  传染病报告卡
-- ----------------------------
CREATE TABLE `biz_infectious_report` (
  `id` bigint NOT NULL COMMENT '主键',
  `report_no` varchar(32) NOT NULL COMMENT '报卡编号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别',
  `age` int DEFAULT NULL COMMENT '年龄（快照）',
  `regist_id` bigint DEFAULT NULL COMMENT '门诊就诊ID',
  `inp_id` bigint DEFAULT NULL COMMENT '住院记录ID',
  `visit_dept_id` bigint DEFAULT NULL COMMENT '发现/就诊科室ID（快照）',
  `visit_dept_name` varchar(100) DEFAULT NULL COMMENT '发现/就诊科室（快照）',
  `disease_id` bigint NOT NULL COMMENT '病种ID',
  `disease_code` varchar(16) NOT NULL COMMENT '病种编码（快照）',
  `disease_name` varchar(50) NOT NULL COMMENT '病种名称（快照）',
  `infectious_class` tinyint NOT NULL COMMENT '传染病类别（快照，1甲/2乙/3丙）',
  `icd10` varchar(16) DEFAULT NULL COMMENT 'ICD-10（快照）',
  `report_deadline` datetime NOT NULL COMMENT '报卡时限',
  `clinical_desc` varchar(500) DEFAULT NULL COMMENT '临床摘要',
  `report_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态',
  `report_count` int NOT NULL DEFAULT '1' COMMENT '报卡次数',
  `report_by` bigint NOT NULL COMMENT '填卡医生ID',
  `report_by_name` varchar(50) NOT NULL COMMENT '填卡医生姓名（快照）',
  `report_time` datetime NOT NULL COMMENT '填卡时间',
  `audit_by_name` varchar(50) DEFAULT NULL COMMENT '审核人姓名',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `audit_opinion` varchar(200) DEFAULT NULL COMMENT '审核意见',
  `return_reason` varchar(200) DEFAULT NULL COMMENT '退报原因',
  `notify_time` datetime DEFAULT NULL COMMENT '最近一次超时催报时间',
  `direct_time` datetime DEFAULT NULL COMMENT '直报时间',
  `direct_payload` text COMMENT '直报报文',
  `create_by` varchar(64) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标记',
  `remark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_infectious_report_no` (`report_no`),
  KEY `idx_infectious_report_status` (`report_status`),
  KEY `idx_infectious_report_deadline` (`report_status`,`report_deadline`),
  KEY `idx_infectious_report_patient` (`patient_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='传染病报告卡';

-- ----------------------------
-- biz_public_health_report  公卫上报表
-- ----------------------------
CREATE TABLE `biz_public_health_report` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `report_no` varchar(32) NOT NULL COMMENT '上报编号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) DEFAULT NULL COMMENT '患者号',
  `patient_name` varchar(50) DEFAULT NULL COMMENT '患者姓名',
  `record_id` bigint DEFAULT NULL COMMENT '病历ID',
  `report_type` tinyint NOT NULL COMMENT '上报类型（1-传染病 2-死因监测 3-慢性病 4-其他）',
  `report_content` varchar(1000) NOT NULL COMMENT '上报内容',
  `diagnosis` varchar(200) DEFAULT NULL COMMENT '诊断',
  `diagnosis_code` varchar(32) DEFAULT NULL COMMENT '诊断编码',
  `report_status` tinyint NOT NULL DEFAULT '1' COMMENT '上报状态（1-待审核 2-审核通过 3-审核驳回）',
  `report_by` varchar(64) DEFAULT NULL COMMENT '上报人',
  `report_time` datetime DEFAULT NULL COMMENT '上报时间',
  `audit_by` varchar(64) DEFAULT NULL COMMENT '审核人',
  `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
  `audit_remark` varchar(500) DEFAULT NULL COMMENT '审核意见',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_no` (`report_no`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_report_type` (`report_type`),
  KEY `idx_report_status` (`report_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='公卫上报表';

-- ----------------------------
-- biz_adverse_event  不良事件上报
-- ----------------------------
CREATE TABLE `biz_adverse_event` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `event_no` varchar(32) NOT NULL COMMENT '事件编号 AE+yyyyMMdd+4位',
  `event_type` tinyint NOT NULL COMMENT '事件类型',
  `event_level` tinyint NOT NULL COMMENT '事件等级',
  `acquired_flag` tinyint NOT NULL DEFAULT '1' COMMENT '来源（1-院内获得 2-入院带入）',
  `occur_dept_id` bigint NOT NULL COMMENT '发生科室 sys_department.id',
  `occur_dept_name` varchar(64) DEFAULT NULL COMMENT '发生科室名称（快照）',
  `occur_ward_id` bigint DEFAULT NULL COMMENT '发生病区ID',
  `occur_ward_name` varchar(128) DEFAULT NULL COMMENT '发生病区名称（快照）',
  `occur_time` datetime NOT NULL COMMENT '发生时间',
  `patient_id` bigint DEFAULT NULL COMMENT '关联患者',
  `patient_name` varchar(64) DEFAULT NULL COMMENT '患者姓名（快照，可空）',
  `visit_id` bigint DEFAULT NULL COMMENT '关联就诊 biz_regist_info.id（可空）',
  `title` varchar(100) NOT NULL COMMENT '事件摘要',
  `description` text NOT NULL COMMENT '事件详细经过',
  `immediate_action` varchar(500) DEFAULT NULL COMMENT '即时处置措施',
  `reporter_id` bigint NOT NULL COMMENT '上报人员工ID',
  `reporter_name` varchar(64) DEFAULT NULL COMMENT '上报人姓名（快照）',
  `report_time` datetime NOT NULL COMMENT '上报时间',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-已上报待处理 2-处理中 3-已整改 4-已结案）',
  `handler_id` bigint DEFAULT NULL COMMENT '处理人员工ID',
  `handler_name` varchar(64) DEFAULT NULL COMMENT '处理人姓名（快照）',
  `handle_remark` varchar(500) DEFAULT NULL COMMENT '处理意见（D）',
  `handle_time` datetime DEFAULT NULL COMMENT '处理时间',
  `rectify_by_id` bigint DEFAULT NULL COMMENT '整改人员工ID',
  `rectify_by_name` varchar(64) DEFAULT NULL COMMENT '整改人姓名（快照）',
  `rectify_measures` varchar(500) DEFAULT NULL COMMENT '整改措施（C）',
  `rectify_time` datetime DEFAULT NULL COMMENT '整改时间',
  `close_by_id` bigint DEFAULT NULL COMMENT '结案人员工ID',
  `close_by_name` varchar(64) DEFAULT NULL COMMENT '结案人姓名（快照）',
  `verify_remark` varchar(500) DEFAULT NULL COMMENT '验证结论（A）',
  `close_time` datetime DEFAULT NULL COMMENT '结案时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_no` (`event_no`),
  KEY `idx_status` (`status`),
  KEY `idx_occur_dept` (`occur_dept_id`),
  KEY `idx_report_time` (`report_time`),
  KEY `idx_nursing_qc_stat` (`event_type`,`occur_ward_id`,`occur_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='不良事件上报';

-- ----------------------------
-- biz_medical_waste  医疗废物登记
-- ----------------------------
CREATE TABLE `biz_medical_waste` (
  `id` bigint NOT NULL COMMENT '医废登记ID',
  `waste_no` varchar(32) NOT NULL COMMENT '医废交接单号',
  `waste_type` tinyint NOT NULL COMMENT '医废类别（1-感染性 2-损伤性 3-病理性 4-药物性 5-化学性）',
  `weight_kg` decimal(8,2) DEFAULT NULL COMMENT '重量（kg）',
  `dept_id` bigint DEFAULT NULL COMMENT '产生科室ID',
  `dept_name` varchar(100) DEFAULT NULL COMMENT '产生科室名称',
  `collect_time` datetime NOT NULL COMMENT '收集时间',
  `collector_name` varchar(50) DEFAULT NULL COMMENT '收集人',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-已登记 2-已交接 3-已处置）',
  `handover_name` varchar(50) DEFAULT NULL COMMENT '交接人',
  `handover_time` datetime DEFAULT NULL COMMENT '交接时间',
  `disposal_company` varchar(128) DEFAULT NULL COMMENT '处置公司',
  `disposal_time` datetime DEFAULT NULL COMMENT '处置时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_medical_waste_no` (`waste_no`),
  KEY `idx_bmw_status` (`status`),
  KEY `idx_bmw_collect` (`collect_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='医疗废物登记';

-- ----------------------------
-- biz_death_certificate  死亡医学证明书
-- ----------------------------
CREATE TABLE `biz_death_certificate` (
  `id` bigint NOT NULL COMMENT '主键（雪花ID）',
  `cert_no` varchar(32) NOT NULL COMMENT '证明编号',
  `admission_id` bigint NOT NULL COMMENT '住院记录ID',
  `discharge_id` bigint DEFAULT NULL COMMENT '死亡出院记录ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) NOT NULL COMMENT '死者姓名（快照）',
  `gender` tinyint DEFAULT NULL COMMENT '性别（1-男 2-女 3-未知）',
  `nation` varchar(20) DEFAULT NULL COMMENT '民族（快照）',
  `birth_date` date DEFAULT NULL COMMENT '出生日期（快照）',
  `age` int DEFAULT NULL COMMENT '死亡年龄',
  `id_card` varchar(18) DEFAULT NULL COMMENT '身份证号',
  `occupation` varchar(50) DEFAULT NULL COMMENT '职业（快照）',
  `marital_status` tinyint DEFAULT NULL COMMENT '婚姻状况（0-未婚 1-已婚 2-离异 3-丧偶）',
  `death_time` datetime NOT NULL COMMENT '死亡时间',
  `death_place` tinyint NOT NULL COMMENT '死亡地点（1-医院 2-来院途中 3-家中 4-民政管理机构 5-其他机构 9-未指明）',
  `death_dept_id` bigint DEFAULT NULL COMMENT '死亡科室ID',
  `death_dept_name` varchar(100) DEFAULT NULL COMMENT '死亡科室名称（快照）',
  `death_ward_name` varchar(64) DEFAULT NULL COMMENT '死亡病区名称（快照）',
  `death_bed_no` varchar(16) DEFAULT NULL COMMENT '死亡床位号（快照）',
  `clinical_diagnosis` varchar(500) NOT NULL COMMENT '死亡诊断',
  `underlying_icd_code` varchar(32) DEFAULT NULL COMMENT '根本死因ICD-10编码',
  `underlying_icd_name` varchar(200) DEFAULT NULL COMMENT '根本死因名称（快照）',
  `past_history` varchar(500) DEFAULT NULL COMMENT '既往病史',
  `autopsy_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否尸检（0-否 1-是）',
  `autopsy_result` varchar(500) DEFAULT NULL COMMENT '尸检结论/病理诊断',
  `relative_name` varchar(50) DEFAULT NULL COMMENT '死者近亲属姓名',
  `relative_relation` varchar(20) DEFAULT NULL COMMENT '与死者关系',
  `relative_phone` varchar(20) DEFAULT NULL COMMENT '近亲属联系电话',
  `physician_id` bigint DEFAULT NULL COMMENT '填表医师ID',
  `physician_name` varchar(50) NOT NULL COMMENT '填表医师姓名',
  `fill_time` datetime DEFAULT NULL COMMENT '填表时间',
  `reviewer_id` bigint DEFAULT NULL COMMENT '审核人ID',
  `reviewer_name` varchar(50) DEFAULT NULL COMMENT '审核人姓名',
  `review_time` datetime DEFAULT NULL COMMENT '审核时间',
  `review_opinion` varchar(500) DEFAULT NULL COMMENT '审核意见',
  `cert_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-草稿 2-已审核 3-已开具 4-已作废）',
  `issue_time` datetime DEFAULT NULL COMMENT '签发（出具/盖章）',
  `printer_name` varchar(64) DEFAULT NULL COMMENT '最后打印人',
  `print_count` int NOT NULL DEFAULT '0' COMMENT '打印次数',
  `last_print_time` datetime DEFAULT NULL COMMENT '最后打印时间',
  `void_reason` varchar(500) DEFAULT NULL COMMENT '作废原因',
  `void_by` varchar(64) DEFAULT NULL COMMENT '作废经办人',
  `void_time` datetime DEFAULT NULL COMMENT '作废时间',
  `orig_cert_id` bigint DEFAULT NULL COMMENT '重开来源证明ID',
  `report_status` tinyint NOT NULL DEFAULT '1' COMMENT '死因监测上报状态（1-未上报 2-已上报 3-上报失败）',
  `report_deadline` datetime DEFAULT NULL COMMENT '上报时限',
  `report_time` datetime DEFAULT NULL COMMENT '上报时间',
  `report_no` varchar(64) DEFAULT NULL COMMENT '上报回执编号/区域死因监测编号',
  `report_error` varchar(500) DEFAULT NULL COMMENT '上报失败原因',
  `report_payload` text COMMENT '上报报文',
  `notify_time` datetime DEFAULT NULL COMMENT '最近一次超时催报时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cert_no` (`cert_no`) COMMENT '单号一经生成不复用，软删行不会与新单撞号',
  KEY `idx_cert_admission` (`admission_id`,`cert_status`) COMMENT '一次住院的有效证明唯一性校验 + 按住院回看',
  KEY `idx_cert_status_deadline` (`cert_status`,`report_status`,`report_deadline`) COMMENT '欠账榜（未签发/未上报/已逾期）一次索引扫',
  KEY `idx_cert_death_time` (`death_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='死亡医学证明书';

-- ----------------------------
-- biz_death_certificate_cause  死亡证明死因链
-- ----------------------------
CREATE TABLE `biz_death_certificate_cause` (
  `id` bigint NOT NULL COMMENT '主键（雪花ID）',
  `cert_id` bigint NOT NULL COMMENT '死亡证明ID',
  `part` tinyint NOT NULL COMMENT '部分（1-Ⅰ部分死因链 2-Ⅱ部分其他疾病）',
  `seq_no` tinyint NOT NULL COMMENT '行序',
  `icd_code` varchar(32) DEFAULT NULL COMMENT 'ICD-10编码',
  `icd_name` varchar(200) NOT NULL COMMENT '疾病或情况名称',
  `interval_text` varchar(50) DEFAULT NULL COMMENT '发病至死亡间隔',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cert_part_seq` (`cert_id`,`part`,`seq_no`) COMMENT '本表无 del_flag，草稿整体替换走物理删（软删会占键）',
  KEY `idx_cause_cert` (`cert_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='死亡证明死因链';

-- ----------------------------
-- biz_death_registration  住院死亡登记簿
-- ----------------------------
CREATE TABLE `biz_death_registration` (
  `id` bigint NOT NULL COMMENT '主键（雪花ID）',
  `register_no` varchar(32) NOT NULL COMMENT '死亡登记号',
  `admission_id` bigint NOT NULL COMMENT '住院记录ID',
  `cert_id` bigint DEFAULT NULL COMMENT '死亡证明ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) NOT NULL COMMENT '死者姓名（快照）',
  `death_time` datetime NOT NULL COMMENT '死亡时间',
  `death_dept_id` bigint DEFAULT NULL COMMENT '死亡科室ID',
  `death_dept_name` varchar(100) DEFAULT NULL COMMENT '死亡科室名称（快照）',
  `death_bed_no` varchar(16) DEFAULT NULL COMMENT '死亡床位号（快照）',
  `death_type` tinyint NOT NULL COMMENT '死亡类型（1-疾病死亡 2-非疾病死亡）',
  `police_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否已报公安/司法（0-否 1-是）',
  `police_org` varchar(100) DEFAULT NULL COMMENT '受理公安机关',
  `police_case_no` varchar(64) DEFAULT NULL COMMENT '公安受理/案件编号',
  `police_report_time` datetime DEFAULT NULL COMMENT '报案时间',
  `forensic_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否由法医出具/检验（0-否 1-是）',
  `body_disposal` tinyint DEFAULT NULL COMMENT '尸体处理方式（1-殡仪馆接运 2-家属自行处理 3-病理解剖 4-其他）',
  `body_unit` varchar(100) DEFAULT NULL COMMENT '遗体接运/接收单位',
  `body_transport_time` datetime DEFAULT NULL COMMENT '遗体移出时间',
  `relative_name` varchar(50) DEFAULT NULL COMMENT '办理人/近亲属姓名',
  `relative_relation` varchar(20) DEFAULT NULL COMMENT '与死者关系',
  `relative_phone` varchar(20) DEFAULT NULL COMMENT '联系电话',
  `received_copies` varchar(50) DEFAULT NULL COMMENT '家属已领取联次（1-记录联 2-户籍联 3-殡葬联 4-家属联）',
  `receive_time` datetime DEFAULT NULL COMMENT '领取时间',
  `dispute_flag` tinyint NOT NULL DEFAULT '0' COMMENT '是否存在医疗纠纷/患方异议（0-否 1-是）',
  `dispute_desc` varchar(500) DEFAULT NULL COMMENT '纠纷/异议情况',
  `register_status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-草稿 2-已登记 3-已作废）',
  `registrar_id` bigint DEFAULT NULL COMMENT '登记人ID（值班医师/病区护士/防保科）',
  `registrar_name` varchar(50) DEFAULT NULL COMMENT '登记人姓名',
  `register_time` datetime DEFAULT NULL COMMENT '登记（确认）',
  `void_reason` varchar(500) DEFAULT NULL COMMENT '作废原因',
  `void_time` datetime DEFAULT NULL COMMENT '作废时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_register_no` (`register_no`),
  KEY `idx_register_admission` (`admission_id`,`register_status`) COMMENT '按住院查有效登记（服务层保证唯一，作废可重登）',
  KEY `idx_register_status` (`register_status`,`death_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='住院死亡登记簿';

-- ----------------------------
-- biz_dispute_case  医疗纠纷投诉主单
-- ----------------------------
CREATE TABLE `biz_dispute_case` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `case_no` varchar(32) NOT NULL COMMENT '单据编号',
  `case_type` tinyint NOT NULL COMMENT '类型（1-服务投诉 2-医疗纠纷 3-医疗损害争议 4-其他）',
  `source_type` tinyint NOT NULL COMMENT '来源（1-来电 2-来访 3-来信 4-政务热线 5-上级交办 6-院内发现 7-其他）',
  `level` tinyint NOT NULL DEFAULT '1' COMMENT '等级（1-一般 2-较大 3-重大）',
  `patient_id` bigint DEFAULT NULL COMMENT '患者ID',
  `patient_no` varchar(64) DEFAULT NULL COMMENT '患者编号（快照）',
  `patient_name` varchar(128) DEFAULT NULL COMMENT '患者姓名（快照）',
  `admission_id` bigint DEFAULT NULL COMMENT '关联住院ID',
  `dept_id` bigint DEFAULT NULL COMMENT '被投诉科室ID',
  `dept_name` varchar(128) DEFAULT NULL COMMENT '被投诉科室名称（快照）',
  `involved_staff` varchar(255) DEFAULT NULL COMMENT '涉及人员',
  `complainant` varchar(64) DEFAULT NULL COMMENT '投诉人姓名（可为患者本人/家属/其他）',
  `complainant_rel` varchar(32) DEFAULT NULL COMMENT '与患者关系（1-本人 2-家属 3-代理人 4-其他）',
  `complainant_tel` varchar(32) DEFAULT NULL COMMENT '投诉人联系电话',
  `occur_time` datetime DEFAULT NULL COMMENT '事件发生时间',
  `occur_place` varchar(128) DEFAULT NULL COMMENT '事件发生地点',
  `content` varchar(1000) NOT NULL COMMENT '投诉/纠纷内容',
  `demand` varchar(500) DEFAULT NULL COMMENT '投诉人诉求',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态（1-待受理 2-调查中 3-处理中 4-已结案 5-已撤销）',
  `need_seal` tinyint NOT NULL DEFAULT '0' COMMENT '是否需封存病历（0-否 1-是）',
  `seal_status` tinyint NOT NULL DEFAULT '0' COMMENT '封存状态（0-未申请 1-已封存 2-待归档后封存）',
  `archive_id` bigint DEFAULT NULL COMMENT '已封存病案ID',
  `seal_time` datetime DEFAULT NULL COMMENT '封存时间',
  `deal_type` tinyint DEFAULT NULL COMMENT '处理途径（1-院内协商 2-医调委调解 3-行政调解 4-司法鉴定 5-诉讼 6-其他）',
  `duty_type` tinyint DEFAULT NULL COMMENT '责任认定（1-无责 2-轻微责任 3-次要责任 4-主要责任 5-完全责任）',
  `compensation` decimal(12,2) DEFAULT NULL COMMENT '赔偿/补偿金额',
  `conclusion` varchar(1000) DEFAULT NULL COMMENT '调查结论/处理结果',
  `register_by` varchar(64) DEFAULT NULL COMMENT '登记人',
  `register_time` datetime DEFAULT NULL COMMENT '登记时间',
  `accept_by` varchar(64) DEFAULT NULL COMMENT '受理人',
  `accept_time` datetime DEFAULT NULL COMMENT '受理时间',
  `close_by` varchar(64) DEFAULT NULL COMMENT '结案人',
  `close_time` datetime DEFAULT NULL COMMENT '结案时间',
  `revoke_reason` varchar(500) DEFAULT NULL COMMENT '撤销原因',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_case_no` (`case_no`),
  KEY `idx_case_patient` (`patient_id`),
  KEY `idx_case_dept` (`dept_id`),
  KEY `idx_case_status` (`status`),
  KEY `idx_case_type` (`case_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='医疗纠纷投诉主单';

-- ----------------------------
-- biz_dispute_flow  纠纷投诉处理台账
-- ----------------------------
CREATE TABLE `biz_dispute_flow` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `case_id` bigint NOT NULL COMMENT '主单ID',
  `action` varchar(64) NOT NULL COMMENT '动作（受理/调查/协商/回复投诉人/封存病历/结案/撤销…）',
  `from_status` tinyint DEFAULT NULL COMMENT '动作前状态',
  `to_status` tinyint DEFAULT NULL COMMENT '动作后状态',
  `content` varchar(1000) DEFAULT NULL COMMENT '处理说明',
  `operator_id` bigint DEFAULT NULL COMMENT '操作人（员工ID）',
  `operator` varchar(64) DEFAULT NULL COMMENT '操作人姓名',
  `operate_time` datetime DEFAULT NULL COMMENT '操作时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT '0' COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_flow_case` (`case_id`),
  KEY `idx_flow_time` (`operate_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='纠纷投诉处理台账';
