package com.his.miniapp.util;

import com.his.common.util.DateFormats;
import com.his.common.util.TextUtil;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * 报告 PDF 打印（小程序二期·报告原文）。
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public final class MiniappPdfStub {

    /**
     * 报告 PDF ：单页占位文档。
     */
    public static byte[] reportPdf(String reportNo, String patientName, String itemName,
                                   String deptName, String doctorName, LocalDateTime reportTime) {
        String time = reportTime == null
                ? "-" : reportTime.format(DateFormats.DATETIME_MINUTE);
        List<String> lines = List.of(
                "Lukang Hospital (HIS stub PDF)",
                "--------------------------------------------",
                "MEDICAL REPORT (STUB)",
                "Report No : " + safe(reportNo),
                "Patient   : " + safe(patientName),
                "Item      : " + safe(itemName),
                "Dept      : " + safe(deptName),
                "Doctor    : " + safe(doctorName),
                "Issued    : " + time,
                "--------------------------------------------",
                "This is a stub document generated by his-miniapp.",
                "Real PDF rendering will replace this when the",
                "external report service is connected."
        );
        StringBuilder body = new StringBuilder("BT /F1 11 Tf 16 TL 50 790 Td\n");
        for (String line : lines) {
            body.append('(').append(escape(line)).append(") Tj T*\n");
        }
        body.append("ET");
        return build(body.toString());
    }

    /**
     * 手工组包最小 PDF：对象偏移精确写入 xref，保证系统级 PDF 渲染器可开。
     */
    private static byte[] build(String contentStream) {
        List<String> objects = new ArrayList<>();
        objects.add("<< /Type /Catalog /Pages 2 0 R >>");
        objects.add("<< /Type /Pages /Kids [3 0 R] /Count 1 >>");
        objects.add("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
                + "/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>");
        objects.add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>");
        objects.add("<< /Length " + contentStream.getBytes(StandardCharsets.ISO_8859_1).length
                + " >>\nstream\n" + contentStream + "\nendstream");

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        List<Integer> offsets = new ArrayList<>();
        out.writeBytes("%PDF-1.4\n".getBytes(StandardCharsets.ISO_8859_1));
        for (int i = 0; i < objects.size(); i++) {
            offsets.add(out.size());
            out.writeBytes((i + 1 + " 0 obj\n" + objects.get(i) + "\nendobj\n")
                    .getBytes(StandardCharsets.ISO_8859_1));
        }
        int xrefAt = out.size();
        StringBuilder xref = new StringBuilder("xref\n0 " + (objects.size() + 1) + "\n0000000000 65535 f \n");
        for (int off : offsets) {
            xref.append(String.format("%010d 00000 n \n", off));
        }
        out.writeBytes(xref.toString().getBytes(StandardCharsets.ISO_8859_1));
        String trailer = "trailer\n<< /Size " + (objects.size() + 1)
                + " /Root 1 0 R >>\nstartxref\n" + xrefAt + "\n%%EOF";
        out.writeBytes(trailer.getBytes(StandardCharsets.ISO_8859_1));
        return out.toByteArray();
    }

    private static String safe(String s) {
        return !TextUtil.hasText(s) ? "-" : s.replaceAll("[()\\\\]", " ");
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)");
    }
}
