<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.his</groupId>
        <artifactId>his-backend</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>his-report</artifactId>
    <packaging>jar</packaging>
    <name>his-report</name>
    <description>统计报表：运营报表聚合查询</description>

    <dependencies>
        <dependency>
            <groupId>com.his</groupId>
            <artifactId>his-common</artifactId>
        </dependency>
        
        <dependency>
            <groupId>com.his</groupId>
            <artifactId>his-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.his</groupId>
            <artifactId>his-patient</artifactId>
        </dependency>
        <dependency>
            <groupId>com.his</groupId>
            <artifactId>his-appoint</artifactId>
        </dependency>
        <dependency>
            <groupId>com.his</groupId>
            <artifactId>his-charge</artifactId>
        </dependency>    </dependencies>
</project>
