-- 依次导入 02-铺底基础数据 目录下所有表
-- 用法: 在 mysql 客户端中 cd 到本目录后执行
--   source 00_import_all.sql;

SET NAMES utf8mb4;
SET
FOREIGN_KEY_CHECKS=0;

SOURCE
sys_employee.sql;
SOURCE
sys_employee_post.sql;
SOURCE
sys_employee_qualification.sql;
SOURCE
sys_employee_tech_auth.sql;
SOURCE
sys_menu.sql;
SOURCE
sys_role.sql;
SOURCE
sys_role_menu.sql;
SOURCE
sys_user.sql;
SOURCE
sys_bed.sql;
SOURCE
sys_clinic_room.sql;
SOURCE
sys_department.sql;
SOURCE
sys_operation_room.sql;
SOURCE
sys_ward.sql;
SOURCE
sys_config.sql;
SOURCE
sys_dict_data.sql;
SOURCE
sys_dict_type.sql;
SOURCE
sys_sign_cert.sql;
SOURCE
sys_tsa_server.sql;
SOURCE
sys_consumable.sql;
SOURCE
sys_diagnosis.sql;
SOURCE
sys_drug.sql;
SOURCE
sys_icd10.sql;
SOURCE
sys_icd9cm3.sql;
SOURCE
sys_inspection_item.sql;
SOURCE
sys_laboratory_item.sql;
SOURCE
sys_laboratory_item_detail.sql;
SOURCE
sys_treatment_item.sql;
SOURCE
sys_alert_rule.sql;
SOURCE
sys_checkup_package.sql;
SOURCE
sys_checkup_package_item.sql;
SOURCE
sys_drug_dose_limit.sql;
SOURCE
sys_drug_interaction.sql;
SOURCE
sys_drug_price_history.sql;
SOURCE
sys_faq.sql;
SOURCE
sys_imaging_plain_item.sql;
SOURCE
sys_infectious_disease.sql;
SOURCE
sys_insurance_policy.sql;
SOURCE
sys_knowledge_chunk.sql;
SOURCE
sys_knowledge_doc.sql;
SOURCE
sys_lab_plain_item.sql;
SOURCE
sys_nursing_qc_item.sql;
SOURCE
sys_price_change_history.sql;
SOURCE
sys_single_disease.sql;
SOURCE
sys_supplier.sql;
SOURCE
sys_workbench_layout.sql;
SOURCE
sys_workbench_role.sql;
SOURCE
sys_workbench_widget.sql;
SOURCE
biz_diag_template.sql;
SOURCE
biz_drug_package.sql;
SOURCE
biz_drug_package_detail.sql;
SOURCE
biz_ecg_template.sql;
SOURCE
biz_film_spec.sql;
SOURCE
biz_inpatient_order_template.sql;
SOURCE
biz_inpatient_order_template_item.sql;
SOURCE
biz_inspection_template.sql;
SOURCE
biz_laboratory_template.sql;
SOURCE
biz_pathway.sql;
SOURCE
biz_pathway_step.sql;
SOURCE
biz_radio_report_template.sql;
SOURCE
biz_rx_template.sql;
SOURCE
biz_rx_template_detail.sql;
SOURCE
biz_schedule_template.sql;
SOURCE
biz_shift.sql;
SOURCE
biz_survey_item.sql;
SOURCE
biz_survey_template.sql;
SOURCE
biz_arrears_policy.sql;
SOURCE
biz_day_surgery_item.sql;
SOURCE
biz_insurance_catalog_rule.sql;
SOURCE
biz_lis_qc_plan.sql;
SOURCE
biz_nurse_schedule_rule.sql;
SOURCE
biz_revisit_fee_policy.sql;
SOURCE
biz_staff_plan_rule.sql;
SOURCE
biz_triage_rule.sql;
SOURCE
biz_yb_chronic_catalog.sql;
SOURCE
biz_blood_inventory.sql;
SOURCE
biz_consumable_stock.sql;
SOURCE
biz_drug_stock.sql;
SOURCE
biz_exam_device.sql;
SOURCE
biz_exam_device_item.sql;
SOURCE
biz_exam_slot.sql;
SOURCE
biz_fund_account.sql;
SOURCE
biz_infusion_seat.sql;
SOURCE
biz_nurse_schedule.sql;
SOURCE
biz_schedule.sql;
SOURCE
biz_schedule_slot.sql;
SOURCE
biz_schedule_slot_template.sql;
SOURCE
biz_staff_schedule.sql;
SOURCE
biz_yb_catalog.sql;
SOURCE
biz_yb_mapping.sql;
SOURCE
sys_equipment.sql;

SET
FOREIGN_KEY_CHECKS=1;
