-- ============================================================
-- 领域 11 病历质控与病案（归档·首页·编码·签名）（本域 15 表 + 上游参照 9 表 / 48 条关系）
-- 由 workspace/_er/refresh.mjs 从 dev 库 information_schema 反向生成，只用于建模，禁止在业务库执行。
-- 关系 = *_id 列命名推断 + 真实数据覆盖率验证，逐条证据见 docs/er/relationships.csv。
-- PowerDesigner：File → Reverse Engineer → Database → 模板选 MySQL 8.0 → 勾选 Script file 指向本文件。
-- ============================================================


-- biz_inpatient_record  住院病历文书
CREATE TABLE `biz_inpatient_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '病历文书号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者编号（快照）',
  `patient_name` varchar(50) COMMENT '患者姓名（快照）',
  `gender` tinyint COMMENT '性别（快照）（1-男 2-女）',
  `age` int COMMENT '年龄（快照）',
  `age_unit` tinyint COMMENT '年龄单位（快照）（1-岁 2-月 3-天）',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(64) COMMENT '科室名称（快照）',
  `ward_id` bigint COMMENT '病区ID',
  `ward_name` varchar(64) COMMENT '病区名称（快照）',
  `bed_no` varchar(32) COMMENT '床号（快照）',
  `record_type` tinyint NOT NULL COMMENT '文书类型',
  `record_title` varchar(200) COMMENT '文书标题',
  `record_time` datetime NOT NULL COMMENT '记录时间',
  `chief_complaint` varchar(500) COMMENT '主诉',
  `present_illness` text COMMENT '现病史',
  `past_history` text COMMENT '既往史',
  `personal_history` text COMMENT '个人史（含婚育、烟酒、职业）',
  `family_history` text COMMENT '家族史',
  `allergy_history` varchar(500) COMMENT '过敏史',
  `temperature` decimal(4,1) COMMENT '体温（℃）',
  `pulse` int COMMENT '脉搏（次/分）',
  `respiration` int COMMENT '呼吸（次/分）',
  `systolic_pressure` int COMMENT '收缩压（mmHg）',
  `diastolic_pressure` int COMMENT '舒张压（mmHg）',
  `height` decimal(5,1) COMMENT '身高（cm）',
  `weight` decimal(5,1) COMMENT '体重（kg）',
  `general_condition` varchar(500) COMMENT '一般情况（神志/发育/营养/体位/面容）',
  `skin_mucosa` varchar(500) COMMENT '皮肤黏膜',
  `head_neck` varchar(500) COMMENT '头颈部',
  `chest_lung` varchar(500) COMMENT '胸部及肺',
  `heart` varchar(500) COMMENT '心脏',
  `abdomen` varchar(500) COMMENT '腹部',
  `spine_limbs` varchar(500) COMMENT '脊柱四肢',
  `nervous_system` varchar(500) COMMENT '神经系统',
  `specialist_exam` text COMMENT '专科检查',
  `auxiliary_exam` text COMMENT '辅助检查',
  `diagnosis_name` varchar(500) COMMENT '诊断名称',
  `diagnosis_code` varchar(100) COMMENT '诊断编码',
  `treatment_plan` text COMMENT '诊疗计划 / 处理意见',
  `course_note` text COMMENT '病程记录正文',
  `record_status` tinyint NOT NULL DEFAULT 1 COMMENT '文书状态（1-草稿 2-已提交 3-已归档）',
  `doctor_id` bigint COMMENT '书写医生ID',
  `doctor_name` varchar(64) COMMENT '书写医生姓名',
  `submit_time` datetime COMMENT '提交时间',
  `archive_time` datetime COMMENT '归档时间',
  `archive_by` bigint COMMENT '归档人ID（员工ID）',
  `archive_by_name` varchar(64) COMMENT '归档人姓名',
  `sign_status` tinyint NOT NULL DEFAULT 0 COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint COMMENT '当前有效签名ID',
  `signed_time` datetime COMMENT '最近一次签名时刻',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='住院病历文书';

-- biz_inpatient_record_log  住院文书修改日志
CREATE TABLE `biz_inpatient_record_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `doc_type` tinyint NOT NULL COMMENT '单据类型（1-住院病历文书 2-护理文书）',
  `record_id` bigint NOT NULL COMMENT '单据ID',
  `record_no` varchar(50) COMMENT '单据号',
  `record_type` tinyint COMMENT '文书类型码',
  `user_id` bigint COMMENT '操作人ID（员工ID）',
  `user_name` varchar(64) COMMENT '操作人姓名',
  `operation` varchar(50) COMMENT '操作',
  `field_name` varchar(100) COMMENT '变更字段',
  `old_value` text COMMENT '变更前值',
  `new_value` text COMMENT '变更后值',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='住院文书修改日志';

-- biz_medical_record_archive  病历归档
CREATE TABLE `biz_medical_record_archive` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `archive_no` varchar(32) NOT NULL COMMENT '归档编号',
  `record_id` bigint NOT NULL COMMENT '病历ID',
  `record_no` varchar(32) COMMENT '病历号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) COMMENT '患者姓名',
  `regist_id` bigint COMMENT '挂号ID',
  `visit_date` date COMMENT '就诊日期',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(50) COMMENT '科室名称',
  `doctor_id` bigint COMMENT '医生ID',
  `doctor_name` varchar(50) COMMENT '医生姓名',
  `diagnosis` varchar(500) COMMENT '诊断',
  `archive_status` tinyint NOT NULL DEFAULT 1 COMMENT '归档状态（1-待归档 2-已归档 3-已封存）',
  `archive_time` datetime COMMENT '归档时间',
  `seal_time` datetime COMMENT '封存时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_archive_no` (`archive_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病历归档';

-- biz_record_qc_flow  病历三级质控流转单
CREATE TABLE `biz_record_qc_flow` (
  `id` bigint NOT NULL COMMENT '主键',
  `flow_no` varchar(32) NOT NULL COMMENT '流转单号',
  `record_id` bigint NOT NULL COMMENT '病历ID',
  `record_source` varchar(20) NOT NULL DEFAULT 'OUTPATIENT' COMMENT '病历来源',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(64) COMMENT '患者姓名',
  `dept_id` bigint COMMENT '病历所属科室ID',
  `dept_name` varchar(64) COMMENT '病历所属科室名称',
  `flow_status` tinyint NOT NULL DEFAULT 1 COMMENT '流转状态（1-科级待审 2-病案室待审 3-医务处待审 4-终审通过 5-整改中）',
  `current_level` tinyint NOT NULL DEFAULT 1 COMMENT '当前停留级（1-科级 2-病案室 3-医务处）',
  `return_level` tinyint COMMENT '最近一次退回发生级',
  `return_reason` varchar(500) COMMENT '最近一次退回的缺陷明细',
  `return_requirement` varchar(500) COMMENT '最近一次退回的整改要求',
  `return_deadline` date COMMENT '整改期限',
  `grade` tinyint COMMENT '终审定级（1-甲级 2-乙级 3-丙级）',
  `final_score` int COMMENT '终审评分',
  `final_opinion` varchar(500) COMMENT '终审意见',
  `create_by` varchar(64),
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64),
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `del_flag` tinyint NOT NULL DEFAULT 0,
  `remark` varchar(500),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_qc_flow_no` (`flow_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病历三级质控流转单';

-- biz_record_qc_flow_action  质控流转动作时间线
CREATE TABLE `biz_record_qc_flow_action` (
  `id` bigint NOT NULL COMMENT '主键',
  `flow_id` bigint NOT NULL COMMENT '流转单ID',
  `level` tinyint NOT NULL COMMENT '动作发生级（1-科级 2-病案室 3-医务处）',
  `action` tinyint NOT NULL COMMENT '动作（1-发起送审 2-审核通过 3-退回整改 4-整改提交 5-终审通过）',
  `opinion` varchar(500) COMMENT '审核意见',
  `defect_detail` varchar(1000) COMMENT '缺陷明细',
  `requirement` varchar(500) COMMENT '整改要求',
  `operator_id` bigint COMMENT '操作人员工ID',
  `operator_name` varchar(64) COMMENT '操作人姓名',
  `action_time` datetime NOT NULL COMMENT '动作时间',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `del_flag` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='质控流转动作时间线';

-- biz_quality_control  质控检查记录
CREATE TABLE `biz_quality_control` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `qc_no` varchar(32) NOT NULL COMMENT '质控编号',
  `record_id` bigint NOT NULL COMMENT '病历ID',
  `record_source` varchar(16) NOT NULL DEFAULT 'OUTPATIENT' COMMENT '质控对象来源',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `qc_type` tinyint NOT NULL COMMENT '质控类型（0-综合 1-完整性检查 2-规范性检查 3-逻辑性检查 4-AI内涵质控）',
  `qc_content` varchar(500) NOT NULL COMMENT '检查内容',
  `qc_result` tinyint NOT NULL COMMENT '检查结果（0-不通过 1-通过）',
  `error_count` int DEFAULT 0 COMMENT '错误数量',
  `error_detail` varchar(1000) COMMENT '错误详情',
  `score` int COMMENT '质控得分',
  `severity_max` tinyint COMMENT '最高问题严重度（0-无问题 1-提示 2-重要 3-否决项）',
  `qc_status` tinyint NOT NULL DEFAULT 1 COMMENT '质控状态（1-待处理 2-已处理 3-已忽略）',
  `qc_by` varchar(64) COMMENT '质控人',
  `qc_time` datetime COMMENT '质控时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_qc_no` (`qc_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='质控检查记录';

-- biz_quality_control_issue  质控问题明细
CREATE TABLE `biz_quality_control_issue` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `qc_id` bigint NOT NULL COMMENT '质控单ID',
  `qc_no` varchar(32) NOT NULL COMMENT '质控单号',
  `record_source` varchar(16) NOT NULL COMMENT '病历来源',
  `record_id` bigint NOT NULL COMMENT '病历ID',
  `patient_id` bigint COMMENT '患者ID',
  `rule_code` varchar(16) NOT NULL COMMENT '规则编码',
  `rule_name` varchar(64) NOT NULL COMMENT '规则名称',
  `dimension` tinyint NOT NULL COMMENT '维度（1-完整性 2-规范性 3-逻辑性）',
  `severity` tinyint NOT NULL COMMENT '严重度（1-提示 2-重要 3-否决）',
  `deduct` int NOT NULL DEFAULT 0 COMMENT '扣分',
  `field_name` varchar(64) COMMENT '问题字段',
  `error_detail` varchar(500) COMMENT '问题描述',
  `suggestion` varchar(500) COMMENT '整改建议',
  `evidence` varchar(200) COMMENT '病历原文证据（截断）',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='质控问题明细';

-- biz_inpatient_summary  住院病案首页
CREATE TABLE `biz_inpatient_summary` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女 9-未知）',
  `age` int COMMENT '年龄',
  `age_unit` tinyint COMMENT '年龄单位（1-岁 2-月 3-天）',
  `id_card` varchar(18) COMMENT '身份证号',
  `admit_dept_id` bigint COMMENT '入院科别ID',
  `admit_dept_name` varchar(64) COMMENT '入院科别名称（快照）',
  `medical_insurance_no` varchar(32) COMMENT '医保卡号',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(50) COMMENT '科室名称',
  `ward_id` bigint COMMENT '病区ID',
  `ward_name` varchar(64) COMMENT '病区名称',
  `bed_no` varchar(16) COMMENT '床位号',
  `admit_time` datetime COMMENT '入院时间',
  `discharge_time` datetime COMMENT '出院时间',
  `inpatient_days` int COMMENT '实际住院天数',
  `admit_way` tinyint COMMENT '入院途径（1-门诊 2-急诊 3-转院 4-其他）',
  `discharge_way` tinyint COMMENT '离院方式（1-医嘱离院 2-医嘱转院 3-医嘱转社区 4-非医嘱离院 5-死亡 9-其他）',
  `death_flag` tinyint DEFAULT 0 COMMENT '死亡标志（0-否 1-是）',
  `autopsy_flag` tinyint DEFAULT 0 COMMENT '死亡患者尸检（0-否 1-是）',
  `readmit_31d` tinyint COMMENT '31日内再入院（0-否 1-是）',
  `is_surgery` tinyint DEFAULT 0 COMMENT '是否手术（0-否 1-是）',
  `is_transfusion` tinyint DEFAULT 0 COMMENT '是否输血（0-否 1-是）',
  `is_rescue` tinyint DEFAULT 0 COMMENT '是否抢救（0-否 1-是）',
  `is_critical` tinyint DEFAULT 0 COMMENT '是否危重（0-否 1-是）',
  `main_diagnosis_code` varchar(32) COMMENT '主要诊断编码',
  `main_diagnosis_name` varchar(200) COMMENT '主要诊断名称',
  `total_amount` decimal(12,2) COMMENT '住院总费用',
  `western_drug_amount` decimal(12,2) COMMENT '西药费',
  `chinese_drug_amount` decimal(12,2) COMMENT '中成药费',
  `herbal_amount` decimal(12,2) COMMENT '中药饮片费',
  `exam_amount` decimal(12,2) COMMENT '检查费',
  `lab_amount` decimal(12,2) COMMENT '检验费',
  `treatment_amount` decimal(12,2) COMMENT '治疗费',
  `operation_amount` decimal(12,2) COMMENT '手术费',
  `material_amount` decimal(12,2) COMMENT '耗材费',
  `bed_amount` decimal(12,2) COMMENT '床位费',
  `nursing_amount` decimal(12,2) COMMENT '护理费',
  `other_amount` decimal(12,2) COMMENT '其他费用',
  `summary_status` tinyint NOT NULL DEFAULT 1 COMMENT '首页状态（1-草稿 2-已提交 3-已归档）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_summary_admission` (`admission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='住院病案首页';

-- biz_inpatient_diagnosis  病案首页诊断明细
CREATE TABLE `biz_inpatient_diagnosis` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `seq_no` int NOT NULL DEFAULT 1 COMMENT '序号',
  `diag_type` tinyint NOT NULL DEFAULT 2 COMMENT '诊断类型（1-主要诊断 2-其他诊断）',
  `icd_code` varchar(32) COMMENT 'ICD-10 编码',
  `icd_name` varchar(200) COMMENT '诊断名称',
  `admit_condition` tinyint COMMENT '入院病情（1-有 2-临床未确定 3-情况不明 4-无）',
  `cc_level` varchar(8) COMMENT '并发症合并症级别',
  `diagnosis_basis` varchar(500) COMMENT '诊断依据',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病案首页诊断明细';

-- biz_inpatient_operation  病案首页手术明细
CREATE TABLE `biz_inpatient_operation` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `apply_id` bigint COMMENT '来源手术申请单ID',
  `seq_no` int NOT NULL DEFAULT 1 COMMENT '序号',
  `is_main` tinyint DEFAULT 0 COMMENT '是否主要手术（0-否 1-是）',
  `operation_code` varchar(32) COMMENT '手术操作编码',
  `operation_name` varchar(200) COMMENT '手术操作名称',
  `operation_date` datetime COMMENT '手术日期',
  `operation_level` tinyint COMMENT '手术级别（1-一级 2-二级 3-三级 4-四级）',
  `incision_level` tinyint COMMENT '切口等级（0-0类 1-Ⅰ类 2-Ⅱ类 3-Ⅲ类）',
  `anesthesia_type` tinyint COMMENT '麻醉方式（1-全麻 2-椎管内 3-神经阻滞 4-局麻 5-其他）',
  `surgeon_id` bigint COMMENT '主刀医师ID',
  `surgeon_name` varchar(50) COMMENT '主刀医师姓名',
  `assistant_name` varchar(200) COMMENT '助手姓名',
  `operation_basis` varchar(500) COMMENT '手术依据',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病案首页手术明细';

-- biz_archive_borrow  病案借阅复印
CREATE TABLE `biz_archive_borrow` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `borrow_no` varchar(32) NOT NULL COMMENT '单号 BR+yyyyMMdd+4位',
  `borrow_type` tinyint NOT NULL COMMENT '类型（1-借阅 2-复印）',
  `archive_id` bigint NOT NULL COMMENT '归档记录 biz_medical_record_archive.id',
  `record_no` varchar(64) COMMENT '病历号（快照）',
  `patient_name` varchar(64) COMMENT '患者姓名（快照）',
  `dept_name` varchar(64) COMMENT '病历所属科室（快照）',
  `applicant_id` bigint NOT NULL COMMENT '申请人员工ID',
  `applicant_name` varchar(64) COMMENT '申请人姓名（快照）',
  `purpose` varchar(500) NOT NULL COMMENT '借阅/复印用途（病历讨论/医保核查/司法取证/科研等）',
  `expect_return_date` date COMMENT '应归还日期',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（1-待审核 2-已借出 3-已归还 4-已拒绝 5-已复印）',
  `audit_by_id` bigint COMMENT '审核人员工ID',
  `audit_by_name` varchar(64) COMMENT '审核人姓名（快照）',
  `audit_remark` varchar(500) COMMENT '审核意见',
  `audit_time` datetime COMMENT '审核时间',
  `lend_time` datetime COMMENT '借出时间',
  `return_time` datetime COMMENT '归还时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `create_time` datetime COMMENT '创建时间',
  `update_time` datetime COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_borrow_no` (`borrow_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病案借阅复印';

-- biz_archive_code_task  病案编码任务池
CREATE TABLE `biz_archive_code_task` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `task_no` varchar(32) NOT NULL COMMENT '任务号 CT+yyyyMMdd+4位',
  `archive_id` bigint NOT NULL COMMENT '归档记录 biz_medical_record_archive.id',
  `record_no` varchar(64) COMMENT '病历号（快照）',
  `patient_name` varchar(64) COMMENT '患者姓名（快照）',
  `dept_name` varchar(64) COMMENT '病历所属科室（快照）',
  `diagnosis` varchar(500) COMMENT '病历诊断',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（1-待编码 2-已提交 3-已完成 4-已退修）',
  `coder_id` bigint COMMENT '编码人员工ID',
  `coder_name` varchar(64) COMMENT '编码员姓名（快照）',
  `assign_time` datetime COMMENT '分配时间',
  `main_icd_code` varchar(20) COMMENT '主诊断 ICD-10 编码',
  `main_icd_name` varchar(200) COMMENT '主诊断名称',
  `other_icd_text` varchar(500) COMMENT '其他诊断/手术 ICD',
  `submit_time` datetime COMMENT '提交编码时间',
  `audit_by_id` bigint COMMENT '审核人员工ID',
  `audit_by_name` varchar(64) COMMENT '审核人姓名（快照）',
  `audit_remark` varchar(500) COMMENT '审核意见',
  `audit_time` datetime COMMENT '审核时间',
  `return_count` int NOT NULL DEFAULT 0 COMMENT '累计退修次数',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `create_time` datetime COMMENT '创建时间',
  `update_time` datetime COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_no` (`task_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病案编码任务池';

-- biz_stat_report  病案统计上报台账
CREATE TABLE `biz_stat_report` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `report_no` varchar(32) NOT NULL COMMENT '上报单号',
  `report_type` tinyint NOT NULL COMMENT '报表类型（1-卫统年报 2-出院患者统计月报 3-手术工作量专项报表）',
  `period_type` tinyint NOT NULL DEFAULT 2 COMMENT '期间类型（1-月报 2-年报）',
  `period_value` varchar(10) NOT NULL COMMENT '期间值',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(100) COMMENT '科室名称',
  `title` varchar(200) NOT NULL COMMENT '报表标题',
  `discharge_count` int NOT NULL DEFAULT 0 COMMENT '摘要-出院患者例数',
  `death_count` int NOT NULL DEFAULT 0 COMMENT '摘要-死亡例数',
  `operation_count` int NOT NULL DEFAULT 0 COMMENT '摘要-手术台次',
  `level3up_count` int NOT NULL DEFAULT 0 COMMENT '摘要-三级及以上手术台次',
  `avg_los_days` decimal(6,1) NOT NULL DEFAULT 0.0 COMMENT '摘要-平均住院日',
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00 COMMENT '摘要-结算总金额',
  `payload` mediumtext NOT NULL COMMENT '上报报文',
  `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0-草稿 1-已报出 2-已作废）',
  `generate_time` datetime COMMENT '报文生成时间',
  `submit_time` datetime COMMENT '报出时间',
  `void_time` datetime COMMENT '作废时间',
  `void_reason` varchar(200) COMMENT '作废原因',
  `operator_name` varchar(50) COMMENT '生成人',
  `submit_by_name` varchar(50) COMMENT '报出人',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stat_report_no` (`report_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病案统计上报台账';

-- biz_drg_sim_result  DRG 分组模拟结果
CREATE TABLE `biz_drg_sim_result` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `summary_id` bigint NOT NULL COMMENT '病案首页ID',
  `patient_name` varchar(50) COMMENT '患者姓名（快照）',
  `main_diag_code` varchar(32) COMMENT '分组时使用的主诊断编码（快照）',
  `main_diag_name` varchar(200) COMMENT '主诊断名称（快照）',
  `is_surgery` tinyint NOT NULL DEFAULT 0 COMMENT '是否手术',
  `inpatient_days` int COMMENT '住院天数',
  `drg_code` varchar(32) NOT NULL COMMENT '入组编码',
  `drg_name` varchar(200) COMMENT '组名称',
  `mdc_code` varchar(8) COMMENT 'MDC 大类',
  `weight` decimal(10,4) COMMENT '权重 RW',
  `pay_standard` decimal(10,2) COMMENT '病组支付标准（元）',
  `actual_amount` decimal(10,2) COMMENT '实际住院费用',
  `profit_amount` decimal(10,2) COMMENT '盈亏 = 支付标准 - 实际费用',
  `sim_status` tinyint NOT NULL DEFAULT 1 COMMENT '结果（1-已入组 2-未入组）',
  `rule_note` varchar(300) COMMENT '命中规则说明',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_summary` (`summary_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DRG 分组模拟结果';

-- biz_emr_signature  电子签名证据
CREATE TABLE `biz_emr_signature` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `sign_no` varchar(32) NOT NULL COMMENT '签名流水号',
  `biz_type` tinyint NOT NULL COMMENT '签名对象类型',
  `biz_id` bigint NOT NULL COMMENT '签名对象ID',
  `biz_no` varchar(64) COMMENT '对象单号（快照）',
  `patient_id` bigint COMMENT '患者ID',
  `patient_name` varchar(50) COMMENT '患者姓名（快照）',
  `dept_id` bigint COMMENT '对象所属科室ID（快照）',
  `dept_name` varchar(64) COMMENT '对象所属科室名称（快照）',
  `sign_scene` tinyint NOT NULL COMMENT '签名场景',
  `chain_no` int NOT NULL DEFAULT 1 COMMENT '同对象第几次签名',
  `prev_sign_id` bigint COMMENT '前一次签名ID',
  `prev_digest` varchar(128) COMMENT '前一次签名摘要',
  `signer_id` bigint NOT NULL COMMENT '签名人员工ID',
  `signer_name` varchar(64) NOT NULL COMMENT '签名人姓名（快照）',
  `signer_dept_id` bigint COMMENT '签名人科室ID（快照）',
  `signer_dept_name` varchar(64) COMMENT '签名人科室名称（快照）',
  `signer_title` varchar(64) COMMENT '签名人职称',
  `cert_id` bigint NOT NULL COMMENT '所用证书ID',
  `cert_no` varchar(32) NOT NULL COMMENT '所用证书编号（快照）',
  `digest_algo` varchar(16) NOT NULL COMMENT '摘要算法',
  `sign_algo` varchar(32) NOT NULL COMMENT '签名算法',
  `content_digest` varchar(128) NOT NULL COMMENT '被签内容摘要',
  `sign_value` text NOT NULL COMMENT '签名值',
  `content_snapshot` mediumtext COMMENT '被签内容快照',
  `signed_time` datetime NOT NULL COMMENT '签名时刻',
  `time_source` tinyint NOT NULL DEFAULT 1 COMMENT '时间来源（1-本机时钟 2-院内授时服务器 3-第三方TSA）',
  `tsa_serial` varchar(64) COMMENT '第三方时间戳序列号',
  `tsa_time` datetime COMMENT 'TSA 授时时刻',
  `tsa_token` text COMMENT '时间戳令牌',
  `sign_status` tinyint NOT NULL DEFAULT 1 COMMENT '签名状态（1-有效 2-已作废）',
  `verify_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近一次验签结果（0-未校验 1-通过 2-失败）',
  `verify_time` datetime COMMENT '最近一次验签时间',
  `verify_count` int NOT NULL DEFAULT 0 COMMENT '累计验签次数',
  `invalid_reason` varchar(200) COMMENT '作废原因',
  `invalid_time` datetime COMMENT '作废时间',
  `invalid_by` bigint COMMENT '作废操作人员工ID',
  `invalid_by_name` varchar(64) COMMENT '作废操作人姓名',
  `client_ip` varchar(64) COMMENT '签名来源 IP（留痕）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sign_no` (`sign_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电子签名证据';

-- biz_admission  入院记录
CREATE TABLE `biz_admission` (
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `admission_no` varchar(32) NOT NULL COMMENT '入院记录号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `visit_id` bigint COMMENT '就诊次ID',
  `regist_id` bigint COMMENT '来源挂号ID',
  `regist_no` varchar(32) COMMENT '来源挂号号（快照）',
  `admission_order_id` bigint COMMENT '来源住院证ID',
  `admit_dept_id` bigint COMMENT '入院科室ID',
  `dept_id` bigint COMMENT '入院科室ID',
  `ward_id` bigint NOT NULL COMMENT '病区ID',
  `nursing_level` tinyint COMMENT '护理等级（1-特级 2-一级 3-二级 4-三级，字典 his_nursing_level）',
  `nursing_level_source` tinyint NOT NULL DEFAULT 1 COMMENT '护理等级来源（1-默认兜底 2-护理记录带出 3-护士长评定）',
  `nursing_level_time` datetime COMMENT '护理等级评定时间（默认兜底时为写入时间）',
  `bed_id` bigint NOT NULL COMMENT '床位ID',
  `admit_doctor_id` bigint NOT NULL COMMENT '入院医生ID',
  `admit_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入院时间',
  `admit_way` tinyint COMMENT '入院途径（1-门诊 2-急诊 3-转院 4-其他）',
  `diagnosis` varchar(500) COMMENT '入院诊断',
  `admit_diagnosis_code` varchar(32) COMMENT '入院诊断ICD编码',
  `admit_diagnosis_name` varchar(200) COMMENT '入院诊断名称',
  `discharge_time` datetime COMMENT '出院时间',
  `admit_status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（0-已出院 1-在院）',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`admission_id`),
  UNIQUE KEY `uk_admission_no` (`admission_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='入院记录';

-- biz_appoint_info  挂号信息
CREATE TABLE `biz_appoint_info` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `regist_no` varchar(32) NOT NULL COMMENT '挂号单号（唯一）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别（1-男 2-女 3-未知）',
  `age` int COMMENT '年龄',
  `phone` varchar(20) COMMENT '手机号码',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `room_id` bigint COMMENT '诊室ID',
  `room_name` varchar(100) COMMENT '诊室名称',
  `doctor_id` bigint COMMENT '医生ID',
  `doctor_name` varchar(50) COMMENT '医生姓名',
  `schedule_id` bigint COMMENT '排班ID',
  `slot_id` bigint COMMENT '排班时间片段ID',
  `slot_start` char(5) COMMENT '就诊时段开始快照（HH:mm）',
  `slot_end` char(5) COMMENT '就诊时段结束快照（HH:mm）',
  `regist_type` tinyint DEFAULT 1 COMMENT '挂号类型（1-普通号 2-专家号 3-急诊号 4-免费号）',
  `regist_source` tinyint DEFAULT 1 COMMENT '挂号来源（1-窗口挂号 2-自助机挂号 3-网上挂号 4-预约挂号）',
  `regist_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '挂号时间',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `arrive_time` datetime COMMENT '到达时间',
  `schedule_type` tinyint COMMENT '时间段（1-上午 2-下午 3-全天 4-凌晨）',
  `slot_time` varchar(8) COMMENT '就诊时段',
  `visit_type` tinyint NOT NULL COMMENT '就诊类型（号别）（1-初诊 2-复诊）',
  `revisit_source` tinyint COMMENT '复诊来源（1-当日回诊 2-医嘱复诊预约 3-患者自助复诊 4-随访计划复诊）',
  `settlement_type` tinyint DEFAULT 1 COMMENT '结算方式（1-自费 2-城镇职工医保 3-城乡居民医保 4-公费 5-商业保险）',
  `medical_insurance_type` varchar(50) COMMENT '医保类型（如：在职职工、退休职工、城乡居民等）',
  `medical_insurance_no` varchar(50) COMMENT '医保卡号',
  `regist_status` tinyint DEFAULT 1 COMMENT '挂号状态（1-已挂号 2-已签到 3-已接诊 4-已就诊 5-已退号 6-已过号 7-爽约 8-未就诊）',
  `revisit_type` tinyint COMMENT '【已废置】改用 visit_type',
  `revisit_record_id` bigint COMMENT '复诊关联的病历ID',
  `refund_time` datetime COMMENT '退号时间',
  `refund_reason` varchar(200) COMMENT '退号原因',
  `bill_id` bigint COMMENT '挂号费结算账单ID',
  `bill_no` varchar(32) COMMENT '账单号（快照）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_by_id` bigint COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_by_id` bigint COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_regist_no` (`regist_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='挂号信息';

-- biz_medical_record  门诊病历
CREATE TABLE `biz_medical_record` (
  `id` bigint NOT NULL,
  `record_no` varchar(32) NOT NULL COMMENT '病历号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别',
  `age` int COMMENT '年龄',
  `regist_id` bigint NOT NULL COMMENT '挂号ID',
  `regist_no` varchar(32) NOT NULL COMMENT '挂号单号',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `visit_type` tinyint DEFAULT 1 COMMENT '就诊类型（1-初诊 2-复诊）',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '医生姓名',
  `chief_complaint` text COMMENT '主诉',
  `present_illness` text COMMENT '现病史',
  `past_history` text COMMENT '既往史',
  `personal_history` text COMMENT '个人史',
  `family_history` text COMMENT '家族史',
  `allergy_history` text COMMENT '过敏史',
  `temperature` varchar(10) COMMENT '体温（℃）',
  `pulse` varchar(10) COMMENT '脉搏（次/分）',
  `respiration` varchar(10) COMMENT '呼吸（次/分）',
  `systolic_pressure` varchar(10) COMMENT '收缩压（mmHg）',
  `diastolic_pressure` varchar(10) COMMENT '舒张压（mmHg）',
  `general_condition` text COMMENT '一般情况',
  `skin_mucosa` text COMMENT '皮肤黏膜',
  `head_neck` text COMMENT '头颈部',
  `chest_lung` text COMMENT '胸肺',
  `heart` text COMMENT '心脏',
  `abdomen` text COMMENT '腹部',
  `spine_limbs` text COMMENT '脊柱四肢',
  `nervous_system` text COMMENT '神经系统',
  `specialist_exam` text COMMENT '专科检查',
  `auxiliary_exam` text COMMENT '辅助检查',
  `diagnosis` text COMMENT '诊断',
  `diagnosis_code` varchar(100) COMMENT '诊断编码',
  `diagnosis_name` varchar(500) COMMENT '诊断名称',
  `treatment_plan` text COMMENT '处理意见',
  `record_status` tinyint DEFAULT 1 COMMENT '病历状态（1-草稿 2-已提交 3-已归档 4-已作废）',
  `review_status` tinyint DEFAULT 0 COMMENT '审核状态（0-待提交 1-待审核 2-审核通过 3-审核驳回）',
  `review_by` varchar(64) COMMENT '审核人',
  `review_time` datetime COMMENT '审核时间',
  `review_remark` varchar(500) COMMENT '审核意见',
  `guide_pdf_path` varchar(512) COMMENT '患者引导单文件路径',
  `submit_time` datetime COMMENT '提交时间',
  `archive_time` datetime COMMENT '归档时间',
  `sign_status` tinyint NOT NULL DEFAULT 0 COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint COMMENT '当前有效签名ID',
  `signed_time` datetime COMMENT '最近一次签名时刻',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门诊病历';

-- biz_operation_apply  手术申请单
CREATE TABLE `biz_operation_apply` (
  `id` bigint NOT NULL COMMENT '手术申请单ID（雪花）',
  `apply_no` varchar(32) NOT NULL COMMENT '手术申请单号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `admission_no` varchar(32) COMMENT '入院号（快照）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(50) COMMENT '患者姓名（快照）',
  `gender` tinyint COMMENT '性别（快照）（1-男 2-女）',
  `age` int COMMENT '年龄（快照）',
  `apply_dept_id` bigint COMMENT '申请科室ID',
  `apply_dept_name` varchar(64) COMMENT '申请科室名称（快照）',
  `apply_ward_name` varchar(64) COMMENT '申请时所在病区名称（快照）',
  `apply_bed_no` varchar(32) COMMENT '申请时床号（快照）',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(64) COMMENT '申请医生姓名（快照）',
  `apply_time` datetime COMMENT '申请时间',
  `planned_operation_code` varchar(32) COMMENT '拟施手术编码',
  `planned_operation_name` varchar(200) NOT NULL COMMENT '拟施手术名称',
  `operation_level` tinyint COMMENT '手术级别（1-一级 2-二级 3-三级 4-四级）',
  `incision_level` tinyint COMMENT '切口等级（0-0类 1-Ⅰ类 2-Ⅱ类 3-Ⅲ类）',
  `anesthesia_type` tinyint COMMENT '麻醉方式（1-全麻 2-椎管内 3-神经阻滞 4-局麻 5-其他）',
  `preop_diagnosis` varchar(500) NOT NULL COMMENT '术前诊断',
  `operation_reason` varchar(500) NOT NULL COMMENT '手术指征/理由',
  `is_emergency` tinyint NOT NULL DEFAULT 0 COMMENT '是否急诊手术（0-否 1-是）',
  `is_main` tinyint NOT NULL DEFAULT 1 COMMENT '是否主要手术',
  `operation_room` varchar(64) COMMENT '手术间',
  `planned_start_time` datetime COMMENT '计划开始时间',
  `planned_end_time` datetime COMMENT '计划结束时间',
  `surgeon_id` bigint COMMENT '主刀医师ID（员工ID）',
  `surgeon_name` varchar(64) COMMENT '主刀医师姓名（快照）',
  `assistant_name` varchar(200) COMMENT '助手姓名',
  `anesthetist_id` bigint COMMENT '麻醉医师ID（员工ID）',
  `anesthetist_name` varchar(64) COMMENT '麻醉医师姓名（快照）',
  `schedule_doctor_id` bigint COMMENT '排台操作人ID（员工ID）',
  `schedule_doctor_name` varchar(64) COMMENT '排台操作人姓名（快照）',
  `schedule_time` datetime COMMENT '排台时间',
  `schedule_remark` varchar(500) COMMENT '排台备注',
  `preop_check_items` varchar(200) COMMENT '术前核对要点码',
  `preop_note` varchar(1000) COMMENT '术前核对补充说明',
  `preop_check_doctor_id` bigint COMMENT '术前核对人ID（员工ID）',
  `preop_check_doctor_name` varchar(64) COMMENT '术前核对人姓名（快照）',
  `preop_check_time` datetime COMMENT '术前核对时间',
  `actual_operation_code` varchar(32) COMMENT '实际手术编码',
  `actual_operation_name` varchar(200) COMMENT '实际手术名称',
  `operation_start_time` datetime COMMENT '实际开始时间（切皮）',
  `operation_end_time` datetime COMMENT '实际结束时间（关腹/关胸）',
  `blood_loss` int COMMENT '术中出血量（ml）',
  `intraop_findings` varchar(2000) COMMENT '术中所见',
  `intraop_procedure` varchar(2000) COMMENT '手术经过/操作步骤',
  `postop_note` varchar(1000) COMMENT '术后处理与注意事项',
  `specimen_sent` varchar(200) COMMENT '标本送检',
  `finish_doctor_id` bigint COMMENT '完成录入人ID（员工ID）',
  `finish_doctor_name` varchar(64) COMMENT '完成录入人姓名（快照）',
  `finish_time` datetime COMMENT '手术完成时间',
  `operation_id` bigint COMMENT '回写病案首页手术明细ID',
  `record_id` bigint COMMENT '回写住院病历ID',
  `operation_status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0-待排期 1-已排期 2-术前核对完成 3-已完成 4-已取消）',
  `cancel_reason` varchar(500) COMMENT '取消原因',
  `cancel_doctor_id` bigint COMMENT '取消人ID（员工ID）',
  `cancel_doctor_name` varchar(64) COMMENT '取消人姓名（快照）',
  `cancel_time` datetime COMMENT '取消时间',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='手术申请单';

-- biz_patient  患者基本信息
CREATE TABLE `biz_patient` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `master_id` bigint COMMENT '主索引',
  `merge_status` tinyint NOT NULL DEFAULT 0 COMMENT '主索引状态（0-正常 1-已并入主档）',
  `merge_time` datetime COMMENT '并入主档的时间',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `birth_date` date COMMENT '出生日期',
  `age` int COMMENT '年龄',
  `id_card` varchar(18) COMMENT '身份证号',
  `phone` varchar(20) COMMENT '手机号码',
  `contact_name` varchar(50) COMMENT '联系人姓名',
  `contact_phone` varchar(20) COMMENT '联系人电话',
  `contact_relation` varchar(20) COMMENT '联系人关系（父母、配偶、子女等）',
  `address` varchar(200) COMMENT '家庭住址',
  `nation` varchar(20) COMMENT '民族',
  `occupation` varchar(50) COMMENT '职业',
  `marital_status` tinyint DEFAULT 0 COMMENT '婚姻状况（0-未婚 1-已婚 2-离异 3-丧偶）',
  `blood_type` varchar(10) COMMENT '血型（A/B/O/AB）',
  `allergy_history` text COMMENT '过敏史',
  `medical_history` text COMMENT '既往病史',
  `patient_type` tinyint DEFAULT 1 COMMENT '患者类型（1-自费 2-城镇职工医保 3-城乡居民医保 4-公费 5-其他）',
  `medical_insurance_no` varchar(50) COMMENT '医保卡号',
  `medical_insurance_type` varchar(50) COMMENT '医保类型',
  `card_type` tinyint DEFAULT 1 COMMENT '卡片类型（1-就诊卡 2-身份证 3-医保卡）',
  `card_no` varchar(50) COMMENT '卡片号码',
  `balance` decimal(10,2) DEFAULT 0.00 COMMENT '账户余额',
  `total_expense` decimal(10,2) DEFAULT 0.00 COMMENT '累计消费金额',
  `visit_count` int DEFAULT 0 COMMENT '就诊次数',
  `last_visit_time` datetime COMMENT '最后就诊时间',
  `last_visit_dept` bigint COMMENT '最后就诊科室',
  `last_visit_doctor` bigint COMMENT '最后就诊医生',
  `last_visit_dept_name` varchar(100) COMMENT '最近就诊科室名',
  `last_visit_doctor_name` varchar(50) COMMENT '最近接诊医生名',
  `first_visit_time` datetime COMMENT '首次就诊时间',
  `first_visit_dept_id` bigint COMMENT '首次就诊科室ID',
  `first_visit_dept_name` varchar(100) COMMENT '首次就诊科室名',
  `first_visit_doctor_id` bigint COMMENT '首次接诊医生ID',
  `first_visit_doctor_name` varchar(50) COMMENT '首次接诊医生名',
  `photo` varchar(200) COMMENT '患者照片',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_patient_no` (`patient_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='患者基本信息';

-- sys_department  科室
CREATE TABLE `sys_department` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `dept_code` varchar(32) NOT NULL COMMENT '科室编码（唯一）',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `dept_type` varchar(20) NOT NULL COMMENT '科室类型（1-门诊科室 2-医技科室 3-药房 4-住院科室 5-其他），多个类型逗号分隔',
  `parent_id` bigint NOT NULL DEFAULT 0 COMMENT '父科室ID',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序号',
  `dept_icon` varchar(200) COMMENT '科室图标',
  `dept_desc` varchar(500) COMMENT '科室描述',
  `contact_phone` varchar(20) COMMENT '联系电话',
  `location` varchar(200) COMMENT '科室位置',
  `dept_leader_id` bigint COMMENT '科室负责人（sys_employee.id)',
  `is_open` tinyint DEFAULT 1 COMMENT '是否开诊（0-否 1-是）',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dept_code` (`dept_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='科室';

-- sys_employee  员工
CREATE TABLE `sys_employee` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `emp_code` varchar(32) NOT NULL COMMENT '员工编号（唯一）',
  `emp_name` varchar(50) NOT NULL COMMENT '员工姓名',
  `emp_type` tinyint NOT NULL DEFAULT 1 COMMENT '员工类型（1-医生 2-护士 3-收费员 4-药剂师 5-管理员 6-其他）',
  `gender` tinyint DEFAULT 1 COMMENT '性别',
  `birth_date` date COMMENT '出生日期',
  `hire_date` date COMMENT '入职日期',
  `id_card` varchar(18) COMMENT '身份证号',
  `phone` varchar(20) COMMENT '手机号码',
  `email` varchar(100) COMMENT '电子邮箱',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(200) COMMENT '科室ID',
  `title` varchar(50) COMMENT '职称',
  `position` varchar(50) COMMENT '职位',
  `specialty` varchar(200) COMMENT '专业特长',
  `education` varchar(50) COMMENT '学历',
  `avatar` varchar(200) COMMENT '头像地址',
  `is_expert` tinyint DEFAULT 0 COMMENT '是否专家（0-否 1-是）',
  `expert_price` decimal(10,2) DEFAULT 0.00 COMMENT '专家号价格',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_emp_code` (`emp_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工';

-- sys_sign_cert  电子签名证书
CREATE TABLE `sys_sign_cert` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `cert_no` varchar(32) NOT NULL COMMENT '证书编号',
  `emp_id` bigint NOT NULL COMMENT '签名人员工ID',
  `emp_name` varchar(64) NOT NULL COMMENT '签名人姓名（快照）',
  `dept_id` bigint COMMENT '所属科室ID（快照）',
  `dept_name` varchar(64) COMMENT '所属科室名称（快照）',
  `key_algo` varchar(16) NOT NULL DEFAULT 'RSA2048' COMMENT '密钥算法',
  `digest_algo` varchar(16) NOT NULL DEFAULT 'SHA256' COMMENT '摘要算法',
  `sign_algo` varchar(32) NOT NULL DEFAULT 'SHA256withRSA' COMMENT '签名算法',
  `public_key` text NOT NULL COMMENT '公钥',
  `key_fingerprint` varchar(64) NOT NULL COMMENT '公钥指纹',
  `protected_private_key` text NOT NULL COMMENT '私钥密文',
  `key_salt` varchar(64) NOT NULL COMMENT '私钥派生盐',
  `key_iterations` int NOT NULL COMMENT '私钥派生迭代次数',
  `issued_mode` tinyint NOT NULL DEFAULT 1 COMMENT '签发方式（1-人工签发 2-系统自动签发）',
  `cert_status` tinyint NOT NULL DEFAULT 1 COMMENT '证书状态（1-有效 2-已吊销）',
  `valid_from` datetime NOT NULL COMMENT '生效时间',
  `valid_to` datetime NOT NULL COMMENT '失效时间',
  `revoke_reason` varchar(200) COMMENT '吊销原因',
  `revoke_time` datetime COMMENT '吊销时间',
  `revoke_by` bigint COMMENT '吊销操作人员工ID',
  `revoke_by_name` varchar(64) COMMENT '吊销操作人姓名',
  `last_used_time` datetime COMMENT '最近一次使用时间',
  `sign_count` int NOT NULL DEFAULT 0 COMMENT '累计签名次数',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cert_no` (`cert_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电子签名证书';

-- sys_ward  病区
CREATE TABLE `sys_ward` (
  `ward_id` bigint NOT NULL COMMENT '病区ID',
  `ward_code` varchar(32) NOT NULL COMMENT '病区编码',
  `ward_name` varchar(64) NOT NULL COMMENT '病区名称',
  `dept_id` bigint NOT NULL COMMENT '所属科室ID',
  `total_beds` int NOT NULL DEFAULT 0 COMMENT '总床位数',
  `occupied_beds` int NOT NULL DEFAULT 0 COMMENT '已占用床位数',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（0-停用 1-正常）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`ward_id`),
  UNIQUE KEY `uk_ward_code` (`ward_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病区';
-- ---------------- 参照关系（E-R 连线） ----------------
ALTER TABLE `biz_archive_borrow` ADD CONSTRAINT `fk_biz_archive_borrow_archive_id` FOREIGN KEY (`archive_id`) REFERENCES `biz_medical_record_archive` (`id`);
ALTER TABLE `biz_archive_borrow` ADD CONSTRAINT `fk_biz_archive_borrow_applicant_id` FOREIGN KEY (`applicant_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_archive_borrow` ADD CONSTRAINT `fk_biz_archive_borrow_audit_by_id` FOREIGN KEY (`audit_by_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_archive_code_task` ADD CONSTRAINT `fk_biz_archive_code_task_archive_id` FOREIGN KEY (`archive_id`) REFERENCES `biz_medical_record_archive` (`id`);
ALTER TABLE `biz_archive_code_task` ADD CONSTRAINT `fk_biz_archive_code_task_coder_id` FOREIGN KEY (`coder_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_archive_code_task` ADD CONSTRAINT `fk_biz_archive_code_task_audit_by_id` FOREIGN KEY (`audit_by_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_drg_sim_result` ADD CONSTRAINT `fk_biz_drg_sim_result_summary_id` FOREIGN KEY (`summary_id`) REFERENCES `biz_inpatient_summary` (`id`);
ALTER TABLE `biz_emr_signature` ADD CONSTRAINT `fk_biz_emr_signature_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_emr_signature` ADD CONSTRAINT `fk_biz_emr_signature_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_emr_signature` ADD CONSTRAINT `fk_biz_emr_signature_prev_sign_id` FOREIGN KEY (`prev_sign_id`) REFERENCES `biz_emr_signature` (`id`);
ALTER TABLE `biz_emr_signature` ADD CONSTRAINT `fk_biz_emr_signature_signer_id` FOREIGN KEY (`signer_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_emr_signature` ADD CONSTRAINT `fk_biz_emr_signature_signer_dept_id` FOREIGN KEY (`signer_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_emr_signature` ADD CONSTRAINT `fk_biz_emr_signature_cert_id` FOREIGN KEY (`cert_id`) REFERENCES `sys_sign_cert` (`id`);
ALTER TABLE `biz_emr_signature` ADD CONSTRAINT `fk_biz_emr_signature_invalid_by` FOREIGN KEY (`invalid_by`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_inpatient_diagnosis` ADD CONSTRAINT `fk_biz_inpatient_diagnosis_admission_id` FOREIGN KEY (`admission_id`) REFERENCES `biz_admission` (`admission_id`);
ALTER TABLE `biz_inpatient_operation` ADD CONSTRAINT `fk_biz_inpatient_operation_admission_id` FOREIGN KEY (`admission_id`) REFERENCES `biz_admission` (`admission_id`);
ALTER TABLE `biz_inpatient_operation` ADD CONSTRAINT `fk_biz_inpatient_operation_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_operation_apply` (`id`);
ALTER TABLE `biz_inpatient_operation` ADD CONSTRAINT `fk_biz_inpatient_operation_surgeon_id` FOREIGN KEY (`surgeon_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_inpatient_record` ADD CONSTRAINT `fk_biz_inpatient_record_admission_id` FOREIGN KEY (`admission_id`) REFERENCES `biz_admission` (`admission_id`);
ALTER TABLE `biz_inpatient_record` ADD CONSTRAINT `fk_biz_inpatient_record_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_inpatient_record` ADD CONSTRAINT `fk_biz_inpatient_record_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_inpatient_record` ADD CONSTRAINT `fk_biz_inpatient_record_ward_id` FOREIGN KEY (`ward_id`) REFERENCES `sys_ward` (`ward_id`);
ALTER TABLE `biz_inpatient_record` ADD CONSTRAINT `fk_biz_inpatient_record_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_inpatient_record` ADD CONSTRAINT `fk_biz_inpatient_record_archive_by` FOREIGN KEY (`archive_by`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_inpatient_record` ADD CONSTRAINT `fk_biz_inpatient_record_sign_id` FOREIGN KEY (`sign_id`) REFERENCES `biz_emr_signature` (`id`);
ALTER TABLE `biz_inpatient_record_log` ADD CONSTRAINT `fk_biz_inpatient_record_log_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inpatient_record` (`id`);
ALTER TABLE `biz_inpatient_record_log` ADD CONSTRAINT `fk_biz_inpatient_record_log_user_id` FOREIGN KEY (`user_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_inpatient_summary` ADD CONSTRAINT `fk_biz_inpatient_summary_admission_id` FOREIGN KEY (`admission_id`) REFERENCES `biz_admission` (`admission_id`);
ALTER TABLE `biz_inpatient_summary` ADD CONSTRAINT `fk_biz_inpatient_summary_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_inpatient_summary` ADD CONSTRAINT `fk_biz_inpatient_summary_admit_dept_id` FOREIGN KEY (`admit_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_inpatient_summary` ADD CONSTRAINT `fk_biz_inpatient_summary_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_inpatient_summary` ADD CONSTRAINT `fk_biz_inpatient_summary_ward_id` FOREIGN KEY (`ward_id`) REFERENCES `sys_ward` (`ward_id`);
ALTER TABLE `biz_medical_record_archive` ADD CONSTRAINT `fk_biz_medical_record_archive_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_medical_record` (`id`);
ALTER TABLE `biz_medical_record_archive` ADD CONSTRAINT `fk_biz_medical_record_archive_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_medical_record_archive` ADD CONSTRAINT `fk_biz_medical_record_archive_regist_id` FOREIGN KEY (`regist_id`) REFERENCES `biz_appoint_info` (`id`);
ALTER TABLE `biz_medical_record_archive` ADD CONSTRAINT `fk_biz_medical_record_archive_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_medical_record_archive` ADD CONSTRAINT `fk_biz_medical_record_archive_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_quality_control` ADD CONSTRAINT `fk_biz_quality_control_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inpatient_record` (`id`);
ALTER TABLE `biz_quality_control` ADD CONSTRAINT `fk_biz_quality_control_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_quality_control_issue` ADD CONSTRAINT `fk_biz_quality_control_issue_qc_id` FOREIGN KEY (`qc_id`) REFERENCES `biz_quality_control` (`id`);
ALTER TABLE `biz_quality_control_issue` ADD CONSTRAINT `fk_biz_quality_control_issue_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inpatient_record` (`id`);
ALTER TABLE `biz_quality_control_issue` ADD CONSTRAINT `fk_biz_quality_control_issue_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_record_qc_flow` ADD CONSTRAINT `fk_biz_record_qc_flow_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_medical_record` (`id`);
ALTER TABLE `biz_record_qc_flow` ADD CONSTRAINT `fk_biz_record_qc_flow_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_record_qc_flow` ADD CONSTRAINT `fk_biz_record_qc_flow_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_record_qc_flow_action` ADD CONSTRAINT `fk_biz_record_qc_flow_action_flow_id` FOREIGN KEY (`flow_id`) REFERENCES `biz_record_qc_flow` (`id`);
ALTER TABLE `biz_record_qc_flow_action` ADD CONSTRAINT `fk_biz_record_qc_flow_action_operator_id` FOREIGN KEY (`operator_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_stat_report` ADD CONSTRAINT `fk_biz_stat_report_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
