-- ============================================================
-- 领域 12 检验LIS（申请·结果·质控·室间质评）（本域 11 表 + 上游参照 9 表 / 29 条关系）
-- 由 workspace/_er/refresh.mjs 从 dev 库 information_schema 反向生成，只用于建模，禁止在业务库执行。
-- 关系 = *_id 列命名推断 + 真实数据覆盖率验证，逐条证据见 docs/er/relationships.csv。
-- PowerDesigner：File → Reverse Engineer → Database → 模板选 MySQL 8.0 → 勾选 Script file 指向本文件。
-- ============================================================


-- biz_laboratory_template  检验申请模板
CREATE TABLE `biz_laboratory_template` (
  `id` bigint NOT NULL,
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `laboratory_item_id` bigint NOT NULL COMMENT '检验项目ID',
  `laboratory_item_code` varchar(32) NOT NULL COMMENT '检验项目编码',
  `laboratory_item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `sample_type` varchar(50) COMMENT '标本类型',
  `inspection_purpose` varchar(200) COMMENT '检验目的',
  `is_emergency` tinyint DEFAULT 0 COMMENT '是否急诊（0-否 1-是）',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检验申请模板';

-- biz_laboratory_apply  检验申请单
CREATE TABLE `biz_laboratory_apply` (
  `id` bigint NOT NULL,
  `apply_no` varchar(32) NOT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别',
  `age` int COMMENT '年龄',
  `regist_id` bigint NOT NULL COMMENT '挂号ID',
  `record_id` bigint COMMENT '病历ID',
  `record_no` varchar(32) COMMENT '病历号',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `dept_id` bigint NOT NULL COMMENT '申请科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '申请科室名称',
  `doctor_id` bigint NOT NULL COMMENT '申请医生ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '申请医生姓名',
  `laboratory_item_id` bigint NOT NULL COMMENT '检验项目ID',
  `laboratory_item_code` varchar(32) NOT NULL COMMENT '检验项目编码',
  `laboratory_item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `laboratory_dept_id` bigint COMMENT '检验科室ID',
  `laboratory_dept_name` varchar(100) COMMENT '检验科室名称',
  `specimen_type` varchar(50) NOT NULL COMMENT '标本类型',
  `specimen_source` varchar(100) COMMENT '标本来源',
  `laboratory_purpose` varchar(500) COMMENT '检验目的',
  `clinical_diagnosis` varchar(500) COMMENT '临床诊断',
  `disease_summary` text COMMENT '病史摘要',
  `is_fasting` tinyint DEFAULT 0 COMMENT '是否空腹（0-否 1-是）',
  `is_emergency` tinyint DEFAULT 0 COMMENT '是否急诊（0-否 1-是）',
  `price` decimal(10,2) DEFAULT 0.00 COMMENT '检验费用',
  `apply_status` tinyint DEFAULT 1 COMMENT '申请状态（1-已提交 2-已缴费 6-已取消）',
  `submit_time` datetime COMMENT '提交时间',
  `sign_status` tinyint NOT NULL DEFAULT 0 COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint COMMENT '当前有效签名ID',
  `signed_time` datetime COMMENT '最近一次签名时刻',
  `pay_time` datetime COMMENT '缴费时间',
  `sample_time` datetime COMMENT '采样时间',
  `sample_by` varchar(64) COMMENT '采样人',
  `complete_time` datetime COMMENT '完成时间',
  `report_id` bigint COMMENT '报告ID',
  `cancel_time` datetime COMMENT '取消时间',
  `cancel_reason` varchar(200) COMMENT '取消原因',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_no` (`apply_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检验申请单';

-- biz_laboratory_record  检验记录
CREATE TABLE `biz_laboratory_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '检验记录号（唯一）',
  `apply_id` bigint NOT NULL COMMENT '申请单ID',
  `apply_no` varchar(32) NOT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女）',
  `age` int COMMENT '年龄',
  `phone` varchar(20) COMMENT '手机号码',
  `visit_date` date COMMENT '就诊日期',
  `apply_dept_id` bigint COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) COMMENT '申请科室',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) COMMENT '申请医生',
  `laboratory_item_id` bigint NOT NULL COMMENT '检验项目ID',
  `laboratory_item_code` varchar(32) NOT NULL COMMENT '检验项目编码',
  `laboratory_item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `laboratory_dept_id` bigint COMMENT '检验科室ID',
  `laboratory_dept_name` varchar(100) COMMENT '检验科室名称',
  `specimen_type` varchar(50) NOT NULL COMMENT '标本类型（血液、尿液、粪便等）',
  `specimen_no` varchar(50) COMMENT '标本编号',
  `specimen_status` tinyint DEFAULT 1 COMMENT '标本状态（1-待采集 2-已采集 3-已接收 4-检测中 5-已完成 6-已退回）',
  `sample_time` datetime COMMENT '采样时间',
  `sample_by` varchar(64) COMMENT '采样人',
  `receive_time` datetime COMMENT '接收时间',
  `receive_by` varchar(64) COMMENT '接收人',
  `execute_time` datetime COMMENT '检测时间',
  `execute_by` varchar(64) COMMENT '检测人',
  `price` decimal(10,2) DEFAULT 0.00 COMMENT '检验费用',
  `diagnosis` text COMMENT '检验结论/诊断',
  `report_sign_id` bigint COMMENT '报告医师签名ID',
  `report_signed_time` datetime COMMENT '报告签名时刻',
  `suggestions` text COMMENT '建议',
  `record_status` tinyint DEFAULT 1 COMMENT '记录状态（1-已登记 2-已采样 3-已接收 4-检测中 5-已出结果 6-已审核 7-已发布 8-已取消）',
  `audit_by` varchar(64) COMMENT '审核人（初审）',
  `audit_sign_id` bigint COMMENT '审核医师签名ID',
  `audit_signed_time` datetime COMMENT '审核签名时刻',
  `audit_time` datetime COMMENT '审核时间',
  `audit2_by` varchar(64) COMMENT '复审人',
  `audit2_time` datetime COMMENT '复审时间',
  `report_time` datetime COMMENT '报告发布时间',
  `report_by` varchar(64) COMMENT '报告发布人',
  `cancel_time` datetime COMMENT '取消时间',
  `cancel_reason` varchar(200) COMMENT '取消原因',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检验记录';

-- biz_lab_result  检验结果
CREATE TABLE `biz_lab_result` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_id` bigint NOT NULL COMMENT '检验记录ID',
  `record_no` varchar(32) NOT NULL COMMENT '检验记录号',
  `laboratory_item_id` bigint NOT NULL COMMENT '检验项目ID',
  `laboratory_item_code` varchar(32) NOT NULL COMMENT '检验项目编码',
  `laboratory_item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `result_value` varchar(200) COMMENT '检验结果值',
  `result_unit` varchar(50) COMMENT '结果单位',
  `reference_range` varchar(100) COMMENT '参考范围',
  `abnormal_flag` tinyint DEFAULT 0 COMMENT '异常标志（0-正常 1-偏高 2-偏低 3-异常）',
  `abnormal_desc` varchar(200) COMMENT '异常描述',
  `judge_note` varchar(200) COMMENT '异常判定说明',
  `result_type` tinyint DEFAULT 1 COMMENT '结果类型（1-定量 2-定性 3-文字描述）',
  `sort_order` int DEFAULT 0 COMMENT '排序号',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检验结果';

-- biz_critical_value  检验危急值
CREATE TABLE `biz_critical_value` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `critical_no` varchar(32) NOT NULL COMMENT '危急值号',
  `record_id` bigint COMMENT '检验记录ID',
  `record_no` varchar(32) COMMENT '检验记录号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女）',
  `age` int COMMENT '年龄',
  `item_code` varchar(32) COMMENT '检验项目编码',
  `item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `result_value` varchar(200) NOT NULL COMMENT '危急值结果值',
  `result_unit` varchar(50) COMMENT '结果单位',
  `reference_range` varchar(100) COMMENT '参考范围',
  `critical_type` tinyint NOT NULL COMMENT '危急值类型（1-偏低 2-偏高）',
  `threshold_text` varchar(100) COMMENT '阈值说明',
  `critical_desc` varchar(300) NOT NULL COMMENT '危急值描述',
  `report_dept_id` bigint COMMENT '报告科室ID',
  `report_dept_name` varchar(100) COMMENT '报告科室',
  `report_by` varchar(64) COMMENT '报告人',
  `report_time` datetime NOT NULL COMMENT '报告时间',
  `deadline_time` datetime COMMENT '处置时限',
  `notify_status` tinyint NOT NULL DEFAULT 0 COMMENT '通知状态（0-未通知 1-已通知）',
  `notify_time` datetime COMMENT '通知时间',
  `escalate_status` tinyint NOT NULL DEFAULT 0 COMMENT '超时升级状态（0-未升级 1-已升级）',
  `escalate_time` datetime COMMENT '升级时间',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '闭环状态（1-待接收 2-已接收 3-已处置 4-已作废）',
  `receive_by` varchar(64) COMMENT '接收人',
  `receive_time` datetime COMMENT '接收时间',
  `handle_by` varchar(64) COMMENT '处置人',
  `handle_time` datetime COMMENT '处置时间',
  `handle_measure` varchar(500) COMMENT '处置措施',
  `source` varchar(16) NOT NULL DEFAULT 'RULE' COMMENT '来源',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_critical_no` (`critical_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检验危急值';

-- biz_lis_qc_plan  室内质控计划
CREATE TABLE `biz_lis_qc_plan` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_no` varchar(32) NOT NULL COMMENT '质控计划编号',
  `item_id` bigint COMMENT '检验项目ID',
  `item_code` varchar(32) COMMENT '检验项目编码',
  `item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `instrument_no` varchar(50) COMMENT '仪器编号',
  `instrument_name` varchar(100) COMMENT '仪器名称',
  `qc_level` tinyint DEFAULT 2 COMMENT '质控水平（1-低值 2-中值 3-高值）',
  `control_name` varchar(200) COMMENT '质控品名称',
  `control_lot_no` varchar(50) COMMENT '质控品批号',
  `manufacturer` varchar(100) COMMENT '生产厂家',
  `mean_value` decimal(18,4) COMMENT '靶值（均值）',
  `sd_value` decimal(18,4) COMMENT '标准差 SD',
  `cv_limit` decimal(8,2) COMMENT '允许 CV 上限（%）',
  `expire_date` date COMMENT '质控品效期',
  `status` tinyint DEFAULT 1 COMMENT '状态（1-启用 0-停用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_no` (`plan_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='室内质控计划';

-- biz_lis_qc_record  室内质控记录
CREATE TABLE `biz_lis_qc_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_id` bigint NOT NULL COMMENT '质控计划ID',
  `plan_no` varchar(32) COMMENT '质控计划编号',
  `item_code` varchar(32) COMMENT '检验项目编码',
  `item_name` varchar(200) COMMENT '检验项目名称',
  `instrument_name` varchar(100) COMMENT '仪器名称',
  `qc_level` tinyint COMMENT '质控水平（1-低值 2-中值 3-高值）',
  `qc_date` date COMMENT '质控日期',
  `qc_time` datetime COMMENT '质控时间',
  `result_value` decimal(18,4) COMMENT '质控测定值',
  `z_score` decimal(10,3) COMMENT 'Z 值',
  `status` tinyint DEFAULT 1 COMMENT '质控状态（1-在控 2-警告 3-失控）',
  `violated_rules` varchar(100) COMMENT '命中的 Westgard 规则',
  `operator` varchar(64) COMMENT '操作人',
  `handle_status` tinyint DEFAULT 0 COMMENT '失控处理（0-无需处理 1-待处理 2-已处理）',
  `handle_cause` varchar(500) COMMENT '失控原因分析',
  `handle_measure` varchar(500) COMMENT '纠正措施',
  `handle_by` varchar(64) COMMENT '处理人',
  `handle_time` datetime COMMENT '处理时间',
  `review_by` varchar(64) COMMENT '复核人',
  `review_time` datetime COMMENT '复核时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='室内质控记录';

-- biz_lis_eqa_plan  室间质评批次
CREATE TABLE `biz_lis_eqa_plan` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_no` varchar(32) NOT NULL COMMENT '质评批次号',
  `plan_year` smallint NOT NULL COMMENT '质评年度',
  `batch_no` tinyint NOT NULL COMMENT '本年度第几批（1-上半年 2-下半年）',
  `org_name` varchar(200) NOT NULL COMMENT '组织方（国家/省/市临床检验中心 或 第三方质评机构）',
  `plan_name` varchar(200) COMMENT '质评计划名称',
  `item_count` int DEFAULT 0 COMMENT '本次参加项目数',
  `sample_count` int DEFAULT 0 COMMENT '本次下发盲样数',
  `receive_date` date COMMENT '盲样接收日期',
  `receive_by` varchar(64) COMMENT '盲样接收人',
  `report_deadline` date COMMENT '结果上报截止日期',
  `return_date` date COMMENT '成绩回报日期',
  `status` tinyint DEFAULT 1 COMMENT '批次状态（1-待收样 2-检测中 3-已上报 4-已回报 5-已归档）',
  `pt_score` decimal(6,2) COMMENT 'PT 得分',
  `pass_flag` tinyint COMMENT '本次是否合格（1-合格 0-不合格）',
  `fail_count` int DEFAULT 0 COMMENT '判定为「不合格」的盲样项数',
  `archive_by` varchar(64) COMMENT '归档人',
  `archive_time` datetime COMMENT '归档时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plan_no` (`plan_no`),
  UNIQUE KEY `uk_year_batch_org` (`plan_year`, `batch_no`, `org_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='室间质评批次';

-- biz_lis_eqa_sample  室间质评盲样
CREATE TABLE `biz_lis_eqa_sample` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_id` bigint NOT NULL COMMENT '质评批次ID',
  `plan_no` varchar(32) COMMENT '质评批次号（冗余）',
  `sample_no` varchar(64) NOT NULL COMMENT '盲样编号',
  `sample_seq` tinyint NOT NULL COMMENT '第几个样品',
  `item_id` bigint COMMENT '检验项目ID',
  `item_code` varchar(32) COMMENT '检验项目编码',
  `item_name` varchar(200) NOT NULL COMMENT '检验项目名称',
  `instrument_name` varchar(100) NOT NULL DEFAULT '' COMMENT '检测仪器',
  `method_name` varchar(100) COMMENT '检测方法学',
  `receive_date` date COMMENT '盲样接收日期',
  `receive_by` varchar(64) COMMENT '盲样接收人',
  `test_value` decimal(18,4) COMMENT '本室测定值',
  `test_by` varchar(64) COMMENT '检测人',
  `test_time` datetime COMMENT '检测时间',
  `overdue_flag` tinyint DEFAULT 0 COMMENT '是否逾期上报',
  `target_value` decimal(18,4) COMMENT '回报靶值/组均值',
  `group_sd` decimal(18,4) COMMENT '回报组标准差',
  `tea` decimal(8,2) COMMENT '允许总误差 TEa（%）',
  `target_min` decimal(18,4) COMMENT '可接受范围下限',
  `target_max` decimal(18,4) COMMENT '可接受范围上限',
  `sdi` decimal(10,3) COMMENT '标准差指数（SDI）',
  `bias_rate` decimal(10,2) COMMENT '偏倚（%）',
  `judge_mode` tinyint DEFAULT 0 COMMENT '判定口径（0-无法判定 1-SDI 2-允许总误差 3-可接受范围）',
  `result_status` tinyint DEFAULT 0 COMMENT '判定结果（0-未判定 1-满意 2-尚可 3-不合格）',
  `status` tinyint DEFAULT 0 COMMENT '流转状态（0-待检测 1-已检测 2-已上报 3-已回报）',
  `handle_status` tinyint DEFAULT 0 COMMENT '整改状态（0-无需整改 1-待整改 2-已整改）',
  `handle_cause` varchar(500) COMMENT '不合格原因分析',
  `handle_measure` varchar(500) COMMENT '纠正措施',
  `handle_by` varchar(64) COMMENT '整改人',
  `handle_time` datetime COMMENT '整改时间',
  `review_by` varchar(64) COMMENT '整改复核人',
  `review_time` datetime COMMENT '复核时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sample` (`plan_id`, `sample_seq`, `item_code`, `instrument_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='室间质评盲样';

-- biz_lis_eqa_compare  室间质评仪器间比对
CREATE TABLE `biz_lis_eqa_compare` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `plan_id` bigint NOT NULL COMMENT '质评批次ID',
  `plan_no` varchar(32) COMMENT '质评批次号（冗余）',
  `item_code` varchar(32) COMMENT '检验项目编码',
  `item_name` varchar(200) COMMENT '检验项目名称',
  `sample_seq` tinyint COMMENT '第几个样品',
  `sample_no` varchar(64) COMMENT '盲样编号',
  `instrument_a` varchar(100) COMMENT 'A 组仪器',
  `method_a` varchar(100) COMMENT 'A 组方法学',
  `value_a` decimal(18,4) COMMENT 'A 组测定值',
  `instrument_b` varchar(100) COMMENT 'B 组仪器',
  `method_b` varchar(100) COMMENT 'B 组方法学',
  `value_b` decimal(18,4) COMMENT 'B 组测定值',
  `diff_value` decimal(18,4) COMMENT '互差绝对值 |A-B|',
  `diff_rate` decimal(10,2) COMMENT '相对互差% = |A-B| /(A+B)',
  `allow_rate` decimal(10,2) COMMENT '允许互差%',
  `allow_source` tinyint DEFAULT 1 COMMENT '允许限来源（1-由该批次 2-无）',
  `status` tinyint DEFAULT 1 COMMENT '比对结论（1-可接受 2-超差）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_compare` (`plan_id`, `sample_seq`, `item_code`, `instrument_a`, `instrument_b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='室间质评仪器间比对';

-- sys_lab_plain_item  检验项目白话词典（患者端报告解读的规则层地基，人工维护）
CREATE TABLE `sys_lab_plain_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `group_name` varchar(32) NOT NULL COMMENT '所属分组（血常规/肝功能/肾功能/血糖/血脂/炎症/凝血/心肌/电解质/尿常规/大便）',
  `item_name` varchar(64) NOT NULL COMMENT '检验项目名称（与 biz_lab_result.laboratory_item_name 精确匹配）',
  `plain_name` varchar(64) NOT NULL COMMENT '白话名（如：血色素、坏胆固醇、心肌损伤指标）',
  `what_is_it` varchar(200) NOT NULL COMMENT '这项查什么（给患者看的一句话，不含诊断/用药）',
  `high_text` varchar(200) NOT NULL COMMENT '结果偏高时的白话说明',
  `low_text` varchar(200) NOT NULL COMMENT '结果偏低时的白话说明',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `sort_order` int DEFAULT 0 COMMENT '排序号',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_item_name` (`item_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检验项目白话词典（患者端报告解读的规则层地基，人工维护）';

-- biz_appoint_info  挂号信息
CREATE TABLE `biz_appoint_info` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `regist_no` varchar(32) NOT NULL COMMENT '挂号单号（唯一）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别（1-男 2-女 3-未知）',
  `age` int COMMENT '年龄',
  `phone` varchar(20) COMMENT '手机号码',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `room_id` bigint COMMENT '诊室ID',
  `room_name` varchar(100) COMMENT '诊室名称',
  `doctor_id` bigint COMMENT '医生ID',
  `doctor_name` varchar(50) COMMENT '医生姓名',
  `schedule_id` bigint COMMENT '排班ID',
  `slot_id` bigint COMMENT '排班时间片段ID',
  `slot_start` char(5) COMMENT '就诊时段开始快照（HH:mm）',
  `slot_end` char(5) COMMENT '就诊时段结束快照（HH:mm）',
  `regist_type` tinyint DEFAULT 1 COMMENT '挂号类型（1-普通号 2-专家号 3-急诊号 4-免费号）',
  `regist_source` tinyint DEFAULT 1 COMMENT '挂号来源（1-窗口挂号 2-自助机挂号 3-网上挂号 4-预约挂号）',
  `regist_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '挂号时间',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `arrive_time` datetime COMMENT '到达时间',
  `schedule_type` tinyint COMMENT '时间段（1-上午 2-下午 3-全天 4-凌晨）',
  `slot_time` varchar(8) COMMENT '就诊时段',
  `visit_type` tinyint NOT NULL COMMENT '就诊类型（号别）（1-初诊 2-复诊）',
  `revisit_source` tinyint COMMENT '复诊来源（1-当日回诊 2-医嘱复诊预约 3-患者自助复诊 4-随访计划复诊）',
  `settlement_type` tinyint DEFAULT 1 COMMENT '结算方式（1-自费 2-城镇职工医保 3-城乡居民医保 4-公费 5-商业保险）',
  `medical_insurance_type` varchar(50) COMMENT '医保类型（如：在职职工、退休职工、城乡居民等）',
  `medical_insurance_no` varchar(50) COMMENT '医保卡号',
  `regist_status` tinyint DEFAULT 1 COMMENT '挂号状态（1-已挂号 2-已签到 3-已接诊 4-已就诊 5-已退号 6-已过号 7-爽约 8-未就诊）',
  `revisit_type` tinyint COMMENT '【已废置】改用 visit_type',
  `revisit_record_id` bigint COMMENT '复诊关联的病历ID',
  `refund_time` datetime COMMENT '退号时间',
  `refund_reason` varchar(200) COMMENT '退号原因',
  `bill_id` bigint COMMENT '挂号费结算账单ID',
  `bill_no` varchar(32) COMMENT '账单号（快照）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_by_id` bigint COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_by_id` bigint COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_regist_no` (`regist_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='挂号信息';

-- biz_compliance_audit_item  医保合规审核明细
CREATE TABLE `biz_compliance_audit_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `audit_id` bigint NOT NULL COMMENT '审核ID',
  `rule_code` varchar(16) NOT NULL COMMENT '规则编码',
  `rule_name` varchar(100) NOT NULL COMMENT '规则名称',
  `rule_group` char(1) NOT NULL COMMENT '规则分组',
  `result` tinyint NOT NULL COMMENT '结果（1-命中 2-通过 3-不适用）',
  `risk_level` tinyint NOT NULL DEFAULT 0 COMMENT '风险等级（1-提示 2-关注 3-高危）',
  `target_type` tinyint NOT NULL DEFAULT 0 COMMENT '对象（0-清单级 1-诊断 2-手术操作）',
  `target_id` bigint COMMENT '对象ID',
  `target_code` varchar(32) COMMENT '对象编码',
  `target_name` varchar(200) COMMENT '对象名称',
  `evidence` varchar(1000) COMMENT '判定依据',
  `suggestion` varchar(500) COMMENT '整改建议',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医保合规审核明细';

-- biz_emr_signature  电子签名证据
CREATE TABLE `biz_emr_signature` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `sign_no` varchar(32) NOT NULL COMMENT '签名流水号',
  `biz_type` tinyint NOT NULL COMMENT '签名对象类型',
  `biz_id` bigint NOT NULL COMMENT '签名对象ID',
  `biz_no` varchar(64) COMMENT '对象单号（快照）',
  `patient_id` bigint COMMENT '患者ID',
  `patient_name` varchar(50) COMMENT '患者姓名（快照）',
  `dept_id` bigint COMMENT '对象所属科室ID（快照）',
  `dept_name` varchar(64) COMMENT '对象所属科室名称（快照）',
  `sign_scene` tinyint NOT NULL COMMENT '签名场景',
  `chain_no` int NOT NULL DEFAULT 1 COMMENT '同对象第几次签名',
  `prev_sign_id` bigint COMMENT '前一次签名ID',
  `prev_digest` varchar(128) COMMENT '前一次签名摘要',
  `signer_id` bigint NOT NULL COMMENT '签名人员工ID',
  `signer_name` varchar(64) NOT NULL COMMENT '签名人姓名（快照）',
  `signer_dept_id` bigint COMMENT '签名人科室ID（快照）',
  `signer_dept_name` varchar(64) COMMENT '签名人科室名称（快照）',
  `signer_title` varchar(64) COMMENT '签名人职称',
  `cert_id` bigint NOT NULL COMMENT '所用证书ID',
  `cert_no` varchar(32) NOT NULL COMMENT '所用证书编号（快照）',
  `digest_algo` varchar(16) NOT NULL COMMENT '摘要算法',
  `sign_algo` varchar(32) NOT NULL COMMENT '签名算法',
  `content_digest` varchar(128) NOT NULL COMMENT '被签内容摘要',
  `sign_value` text NOT NULL COMMENT '签名值',
  `content_snapshot` mediumtext COMMENT '被签内容快照',
  `signed_time` datetime NOT NULL COMMENT '签名时刻',
  `time_source` tinyint NOT NULL DEFAULT 1 COMMENT '时间来源（1-本机时钟 2-院内授时服务器 3-第三方TSA）',
  `tsa_serial` varchar(64) COMMENT '第三方时间戳序列号',
  `tsa_time` datetime COMMENT 'TSA 授时时刻',
  `tsa_token` text COMMENT '时间戳令牌',
  `sign_status` tinyint NOT NULL DEFAULT 1 COMMENT '签名状态（1-有效 2-已作废）',
  `verify_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近一次验签结果（0-未校验 1-通过 2-失败）',
  `verify_time` datetime COMMENT '最近一次验签时间',
  `verify_count` int NOT NULL DEFAULT 0 COMMENT '累计验签次数',
  `invalid_reason` varchar(200) COMMENT '作废原因',
  `invalid_time` datetime COMMENT '作废时间',
  `invalid_by` bigint COMMENT '作废操作人员工ID',
  `invalid_by_name` varchar(64) COMMENT '作废操作人姓名',
  `client_ip` varchar(64) COMMENT '签名来源 IP（留痕）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sign_no` (`sign_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电子签名证据';

-- biz_medical_record  门诊病历
CREATE TABLE `biz_medical_record` (
  `id` bigint NOT NULL,
  `record_no` varchar(32) NOT NULL COMMENT '病历号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别',
  `age` int COMMENT '年龄',
  `regist_id` bigint NOT NULL COMMENT '挂号ID',
  `regist_no` varchar(32) NOT NULL COMMENT '挂号单号',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `visit_type` tinyint DEFAULT 1 COMMENT '就诊类型（1-初诊 2-复诊）',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '医生姓名',
  `chief_complaint` text COMMENT '主诉',
  `present_illness` text COMMENT '现病史',
  `past_history` text COMMENT '既往史',
  `personal_history` text COMMENT '个人史',
  `family_history` text COMMENT '家族史',
  `allergy_history` text COMMENT '过敏史',
  `temperature` varchar(10) COMMENT '体温（℃）',
  `pulse` varchar(10) COMMENT '脉搏（次/分）',
  `respiration` varchar(10) COMMENT '呼吸（次/分）',
  `systolic_pressure` varchar(10) COMMENT '收缩压（mmHg）',
  `diastolic_pressure` varchar(10) COMMENT '舒张压（mmHg）',
  `general_condition` text COMMENT '一般情况',
  `skin_mucosa` text COMMENT '皮肤黏膜',
  `head_neck` text COMMENT '头颈部',
  `chest_lung` text COMMENT '胸肺',
  `heart` text COMMENT '心脏',
  `abdomen` text COMMENT '腹部',
  `spine_limbs` text COMMENT '脊柱四肢',
  `nervous_system` text COMMENT '神经系统',
  `specialist_exam` text COMMENT '专科检查',
  `auxiliary_exam` text COMMENT '辅助检查',
  `diagnosis` text COMMENT '诊断',
  `diagnosis_code` varchar(100) COMMENT '诊断编码',
  `diagnosis_name` varchar(500) COMMENT '诊断名称',
  `treatment_plan` text COMMENT '处理意见',
  `record_status` tinyint DEFAULT 1 COMMENT '病历状态（1-草稿 2-已提交 3-已归档 4-已作废）',
  `review_status` tinyint DEFAULT 0 COMMENT '审核状态（0-待提交 1-待审核 2-审核通过 3-审核驳回）',
  `review_by` varchar(64) COMMENT '审核人',
  `review_time` datetime COMMENT '审核时间',
  `review_remark` varchar(500) COMMENT '审核意见',
  `guide_pdf_path` varchar(512) COMMENT '患者引导单文件路径',
  `submit_time` datetime COMMENT '提交时间',
  `archive_time` datetime COMMENT '归档时间',
  `sign_status` tinyint NOT NULL DEFAULT 0 COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint COMMENT '当前有效签名ID',
  `signed_time` datetime COMMENT '最近一次签名时刻',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门诊病历';

-- biz_patient  患者基本信息
CREATE TABLE `biz_patient` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `master_id` bigint COMMENT '主索引',
  `merge_status` tinyint NOT NULL DEFAULT 0 COMMENT '主索引状态（0-正常 1-已并入主档）',
  `merge_time` datetime COMMENT '并入主档的时间',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `birth_date` date COMMENT '出生日期',
  `age` int COMMENT '年龄',
  `id_card` varchar(18) COMMENT '身份证号',
  `phone` varchar(20) COMMENT '手机号码',
  `contact_name` varchar(50) COMMENT '联系人姓名',
  `contact_phone` varchar(20) COMMENT '联系人电话',
  `contact_relation` varchar(20) COMMENT '联系人关系（父母、配偶、子女等）',
  `address` varchar(200) COMMENT '家庭住址',
  `nation` varchar(20) COMMENT '民族',
  `occupation` varchar(50) COMMENT '职业',
  `marital_status` tinyint DEFAULT 0 COMMENT '婚姻状况（0-未婚 1-已婚 2-离异 3-丧偶）',
  `blood_type` varchar(10) COMMENT '血型（A/B/O/AB）',
  `allergy_history` text COMMENT '过敏史',
  `medical_history` text COMMENT '既往病史',
  `patient_type` tinyint DEFAULT 1 COMMENT '患者类型（1-自费 2-城镇职工医保 3-城乡居民医保 4-公费 5-其他）',
  `medical_insurance_no` varchar(50) COMMENT '医保卡号',
  `medical_insurance_type` varchar(50) COMMENT '医保类型',
  `card_type` tinyint DEFAULT 1 COMMENT '卡片类型（1-就诊卡 2-身份证 3-医保卡）',
  `card_no` varchar(50) COMMENT '卡片号码',
  `balance` decimal(10,2) DEFAULT 0.00 COMMENT '账户余额',
  `total_expense` decimal(10,2) DEFAULT 0.00 COMMENT '累计消费金额',
  `visit_count` int DEFAULT 0 COMMENT '就诊次数',
  `last_visit_time` datetime COMMENT '最后就诊时间',
  `last_visit_dept` bigint COMMENT '最后就诊科室',
  `last_visit_doctor` bigint COMMENT '最后就诊医生',
  `last_visit_dept_name` varchar(100) COMMENT '最近就诊科室名',
  `last_visit_doctor_name` varchar(50) COMMENT '最近接诊医生名',
  `first_visit_time` datetime COMMENT '首次就诊时间',
  `first_visit_dept_id` bigint COMMENT '首次就诊科室ID',
  `first_visit_dept_name` varchar(100) COMMENT '首次就诊科室名',
  `first_visit_doctor_id` bigint COMMENT '首次接诊医生ID',
  `first_visit_doctor_name` varchar(50) COMMENT '首次接诊医生名',
  `photo` varchar(200) COMMENT '患者照片',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_patient_no` (`patient_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='患者基本信息';

-- biz_report  报告单
CREATE TABLE `biz_report` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `report_no` varchar(32) NOT NULL COMMENT '报告编号（唯一）',
  `report_type` tinyint NOT NULL COMMENT '报告类型（1-检查报告 2-检验报告）',
  `record_id` bigint NOT NULL COMMENT '检查/检验记录ID',
  `record_no` varchar(32) NOT NULL COMMENT '检查/检验记录号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女）',
  `age` int COMMENT '年龄',
  `visit_date` date COMMENT '就诊日期',
  `item_name` varchar(200) NOT NULL COMMENT '项目名称',
  `exam_method` varchar(200) COMMENT '检查方法',
  `exam_dept_name` varchar(100) COMMENT '检查/检验科室',
  `apply_dept_name` varchar(100) COMMENT '申请科室',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) COMMENT '临床诊断',
  `report_content` text COMMENT '报告内容',
  `conclusion` text COMMENT '报告结论',
  `positive_flag` tinyint COMMENT '阴阳性（0-未判定 1-阴性 2-阳性 3-未见异常）',
  `is_critical` tinyint NOT NULL DEFAULT 0 COMMENT '是否危急（0-否 1-是）',
  `write_by` varchar(64) COMMENT '报告书写人',
  `write_by_id` bigint COMMENT '报告书写人员工ID',
  `write_time` datetime COMMENT '报告书写时间',
  `template_id` bigint COMMENT '使用的报告模板ID',
  `reject_reason` varchar(500) COMMENT '退回原因',
  `report_version` int NOT NULL DEFAULT 1 COMMENT '报告版本号',
  `film_count` int NOT NULL DEFAULT 0 COMMENT '已登记胶片张数',
  `suggestions` text COMMENT '建议',
  `report_status` tinyint DEFAULT 1 COMMENT '报告状态（1-待审核 2-初审通过 3-已审核 4-已发布 5-已作废）',
  `audit_by` varchar(64) COMMENT '审核人（初审）',
  `audit_time` datetime COMMENT '审核时间',
  `audit2_by` varchar(64) COMMENT '复审人',
  `audit2_time` datetime COMMENT '复审时间',
  `publish_time` datetime COMMENT '发布时间',
  `publish_by` varchar(64) COMMENT '发布人',
  `is_urgent` tinyint DEFAULT 0 COMMENT '是否加急（0-否 1-是）',
  `report_file_path` varchar(500) COMMENT '报告文件路径',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_no` (`report_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告单';

-- sys_department  科室
CREATE TABLE `sys_department` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `dept_code` varchar(32) NOT NULL COMMENT '科室编码（唯一）',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `dept_type` varchar(20) NOT NULL COMMENT '科室类型（1-门诊科室 2-医技科室 3-药房 4-住院科室 5-其他），多个类型逗号分隔',
  `parent_id` bigint NOT NULL DEFAULT 0 COMMENT '父科室ID',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序号',
  `dept_icon` varchar(200) COMMENT '科室图标',
  `dept_desc` varchar(500) COMMENT '科室描述',
  `contact_phone` varchar(20) COMMENT '联系电话',
  `location` varchar(200) COMMENT '科室位置',
  `dept_leader_id` bigint COMMENT '科室负责人（sys_employee.id)',
  `is_open` tinyint DEFAULT 1 COMMENT '是否开诊（0-否 1-是）',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dept_code` (`dept_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='科室';

-- sys_employee  员工
CREATE TABLE `sys_employee` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `emp_code` varchar(32) NOT NULL COMMENT '员工编号（唯一）',
  `emp_name` varchar(50) NOT NULL COMMENT '员工姓名',
  `emp_type` tinyint NOT NULL DEFAULT 1 COMMENT '员工类型（1-医生 2-护士 3-收费员 4-药剂师 5-管理员 6-其他）',
  `gender` tinyint DEFAULT 1 COMMENT '性别',
  `birth_date` date COMMENT '出生日期',
  `hire_date` date COMMENT '入职日期',
  `id_card` varchar(18) COMMENT '身份证号',
  `phone` varchar(20) COMMENT '手机号码',
  `email` varchar(100) COMMENT '电子邮箱',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(200) COMMENT '科室ID',
  `title` varchar(50) COMMENT '职称',
  `position` varchar(50) COMMENT '职位',
  `specialty` varchar(200) COMMENT '专业特长',
  `education` varchar(50) COMMENT '学历',
  `avatar` varchar(200) COMMENT '头像地址',
  `is_expert` tinyint DEFAULT 0 COMMENT '是否专家（0-否 1-是）',
  `expert_price` decimal(10,2) DEFAULT 0.00 COMMENT '专家号价格',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_emp_code` (`emp_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工';

-- sys_laboratory_item  检验项目字典
CREATE TABLE `sys_laboratory_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `item_code` varchar(32) NOT NULL COMMENT '项目编码（唯一）',
  `item_name` varchar(200) NOT NULL COMMENT '项目名称',
  `item_type` tinyint NOT NULL DEFAULT 1 COMMENT '项目类型（1-血液检验 2-尿液检验 3-生化检验 4-免疫检验 5-微生物检验 6-其他）',
  `dept_id` bigint COMMENT '检验科室ID',
  `specimen_type` varchar(50) COMMENT '标本类型（血液、尿液、粪便等）',
  `price` decimal(10,2) DEFAULT 0.00 COMMENT '检验价格',
  `duration` int DEFAULT 0 COMMENT '出报告时间（小时）',
  `reference_value` varchar(200) COMMENT '参考值范围',
  `unit` varchar(50) COMMENT '单位',
  `is_emergency` tinyint DEFAULT 0 COMMENT '是否支持急诊（0-否 1-是）',
  `is_fasting` tinyint DEFAULT 0 COMMENT '是否需要空腹（0-否 1-是）',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_item_code` (`item_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检验项目字典';
-- ---------------- 参照关系（E-R 连线） ----------------
ALTER TABLE `biz_critical_value` ADD CONSTRAINT `fk_biz_critical_value_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_laboratory_record` (`id`);
ALTER TABLE `biz_critical_value` ADD CONSTRAINT `fk_biz_critical_value_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_critical_value` ADD CONSTRAINT `fk_biz_critical_value_report_dept_id` FOREIGN KEY (`report_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_lab_result` ADD CONSTRAINT `fk_biz_lab_result_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_laboratory_record` (`id`);
ALTER TABLE `biz_lab_result` ADD CONSTRAINT `fk_biz_lab_result_laboratory_item_id` FOREIGN KEY (`laboratory_item_id`) REFERENCES `sys_laboratory_item` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_regist_id` FOREIGN KEY (`regist_id`) REFERENCES `biz_appoint_info` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_medical_record` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_laboratory_item_id` FOREIGN KEY (`laboratory_item_id`) REFERENCES `sys_laboratory_item` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_laboratory_dept_id` FOREIGN KEY (`laboratory_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_sign_id` FOREIGN KEY (`sign_id`) REFERENCES `biz_emr_signature` (`id`);
ALTER TABLE `biz_laboratory_apply` ADD CONSTRAINT `fk_biz_laboratory_apply_report_id` FOREIGN KEY (`report_id`) REFERENCES `biz_report` (`id`);
ALTER TABLE `biz_laboratory_record` ADD CONSTRAINT `fk_biz_laboratory_record_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_laboratory_apply` (`id`);
ALTER TABLE `biz_laboratory_record` ADD CONSTRAINT `fk_biz_laboratory_record_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_laboratory_record` ADD CONSTRAINT `fk_biz_laboratory_record_apply_dept_id` FOREIGN KEY (`apply_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_laboratory_record` ADD CONSTRAINT `fk_biz_laboratory_record_apply_doctor_id` FOREIGN KEY (`apply_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_laboratory_record` ADD CONSTRAINT `fk_biz_laboratory_record_laboratory_item_id` FOREIGN KEY (`laboratory_item_id`) REFERENCES `sys_laboratory_item` (`id`);
ALTER TABLE `biz_laboratory_record` ADD CONSTRAINT `fk_biz_laboratory_record_laboratory_dept_id` FOREIGN KEY (`laboratory_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_laboratory_record` ADD CONSTRAINT `fk_biz_laboratory_record_report_sign_id` FOREIGN KEY (`report_sign_id`) REFERENCES `biz_emr_signature` (`id`);
ALTER TABLE `biz_laboratory_record` ADD CONSTRAINT `fk_biz_laboratory_record_audit_sign_id` FOREIGN KEY (`audit_sign_id`) REFERENCES `biz_emr_signature` (`id`);
ALTER TABLE `biz_laboratory_template` ADD CONSTRAINT `fk_biz_laboratory_template_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_laboratory_template` ADD CONSTRAINT `fk_biz_laboratory_template_laboratory_item_id` FOREIGN KEY (`laboratory_item_id`) REFERENCES `sys_laboratory_item` (`id`);
ALTER TABLE `biz_lis_eqa_compare` ADD CONSTRAINT `fk_biz_lis_eqa_compare_plan_id` FOREIGN KEY (`plan_id`) REFERENCES `biz_lis_eqa_plan` (`id`);
ALTER TABLE `biz_lis_eqa_sample` ADD CONSTRAINT `fk_biz_lis_eqa_sample_plan_id` FOREIGN KEY (`plan_id`) REFERENCES `biz_lis_eqa_plan` (`id`);
ALTER TABLE `biz_lis_eqa_sample` ADD CONSTRAINT `fk_biz_lis_eqa_sample_item_id` FOREIGN KEY (`item_id`) REFERENCES `biz_compliance_audit_item` (`id`);
ALTER TABLE `biz_lis_qc_plan` ADD CONSTRAINT `fk_biz_lis_qc_plan_item_id` FOREIGN KEY (`item_id`) REFERENCES `biz_compliance_audit_item` (`id`);
ALTER TABLE `biz_lis_qc_record` ADD CONSTRAINT `fk_biz_lis_qc_record_plan_id` FOREIGN KEY (`plan_id`) REFERENCES `biz_lis_qc_plan` (`id`);
