-- ============================================================
-- 领域 13 检查影像与报告（PACS·预约·心电·病理·内镜）（本域 22 表 + 上游参照 10 表 / 65 条关系）
-- 由 workspace/_er/emit.mjs 从 dev 库 information_schema 反向生成，只用于建模，禁止在业务库执行。
-- 关系 = *_id 列命名推断 + 真实数据覆盖率验证，逐条证据见 docs/er/relationships.csv。
-- PowerDesigner：File → Reverse Engineer → Database → 模板选 MySQL 8.0 → 勾选 Script file 指向本文件。
-- ============================================================


-- biz_inspection_template  检查申请模板
CREATE TABLE `biz_inspection_template` (
  `id` bigint NOT NULL,
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `inspection_item_id` bigint NOT NULL COMMENT '检查项目ID',
  `inspection_item_code` varchar(32) NOT NULL COMMENT '检查项目编码',
  `inspection_item_name` varchar(200) NOT NULL COMMENT '检查项目名称',
  `body_part` varchar(100) COMMENT '检查部位',
  `inspection_purpose` varchar(200) COMMENT '检查目的',
  `is_emergency` tinyint DEFAULT 0 COMMENT '是否急诊（0-否 1-是）',
  `sort_order` int DEFAULT 0 COMMENT '排序',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查申请模板';

-- biz_inspection_apply  检查申请单
CREATE TABLE `biz_inspection_apply` (
  `id` bigint NOT NULL,
  `apply_no` varchar(32) NOT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别',
  `age` int COMMENT '年龄',
  `regist_id` bigint NOT NULL COMMENT '挂号ID',
  `record_id` bigint COMMENT '病历ID',
  `record_no` varchar(32) COMMENT '病历号',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `dept_id` bigint NOT NULL COMMENT '申请科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '申请科室名称',
  `doctor_id` bigint NOT NULL COMMENT '申请医生ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '申请医生姓名',
  `inspection_item_id` bigint NOT NULL COMMENT '检查项目ID',
  `inspection_item_code` varchar(32) NOT NULL COMMENT '检查项目编码',
  `inspection_item_name` varchar(200) NOT NULL COMMENT '检查项目名称',
  `inspection_dept_id` bigint COMMENT '检查科室ID',
  `inspection_dept_name` varchar(100) COMMENT '检查科室名称',
  `body_part` varchar(200) COMMENT '检查部位',
  `inspection_purpose` varchar(500) COMMENT '检查目的',
  `clinical_diagnosis` varchar(500) COMMENT '临床诊断',
  `disease_summary` text COMMENT '病史摘要',
  `special_requirements` varchar(500) COMMENT '特殊要求',
  `is_emergency` tinyint DEFAULT 0 COMMENT '是否急诊（0-否 1-是）',
  `price` decimal(10,2) DEFAULT 0.00 COMMENT '检查费用',
  `apply_status` tinyint DEFAULT 1 COMMENT '申请状态（1-已提交 2-已缴费 6-已取消）',
  `appointment_time` datetime COMMENT '预约时间',
  `sign_status` tinyint NOT NULL DEFAULT 0 COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint COMMENT '当前有效签名ID',
  `signed_time` datetime COMMENT '最近一次签名时刻',
  `submit_time` datetime COMMENT '提交时间',
  `pay_time` datetime COMMENT '缴费时间',
  `complete_time` datetime COMMENT '完成时间',
  `report_id` bigint COMMENT '报告ID',
  `cancel_time` datetime COMMENT '取消时间',
  `cancel_reason` varchar(200) COMMENT '取消原因',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_apply_no` (`apply_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查申请单';

-- biz_inspection_record  检查记录
CREATE TABLE `biz_inspection_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '检查记录号（唯一）',
  `apply_id` bigint NOT NULL COMMENT '申请单ID',
  `apply_no` varchar(32) NOT NULL COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女）',
  `age` int COMMENT '年龄',
  `phone` varchar(20) COMMENT '手机号码',
  `visit_date` date COMMENT '就诊日期',
  `apply_dept_id` bigint COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) COMMENT '申请科室',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) COMMENT '申请医生',
  `inspection_item_id` bigint NOT NULL COMMENT '检查项目ID',
  `inspection_item_code` varchar(32) NOT NULL COMMENT '检查项目编码',
  `inspection_item_name` varchar(200) NOT NULL COMMENT '检查项目名称',
  `inspection_dept_id` bigint COMMENT '检查科室ID',
  `inspection_dept_name` varchar(100) COMMENT '检查科室名称',
  `body_part` varchar(200) COMMENT '检查部位',
  `inspection_purpose` varchar(500) COMMENT '检查目的',
  `clinical_diagnosis` varchar(500) COMMENT '临床诊断',
  `price` decimal(10,2) DEFAULT 0.00 COMMENT '检查费用',
  `appointment_time` datetime COMMENT '预约时间',
  `check_in_time` datetime COMMENT '签到时间',
  `execute_time` datetime COMMENT '执行时间',
  `execute_by` varchar(64) COMMENT '执行人',
  `result_description` text COMMENT '检查描述',
  `result_conclusion` text COMMENT '检查结论',
  `report_sign_id` bigint COMMENT '报告医师签名ID',
  `report_signed_time` datetime COMMENT '报告签名时刻',
  `result_image` varchar(500) COMMENT '检查影像路径',
  `record_status` tinyint DEFAULT 1 COMMENT '记录状态（1-已登记 2-已签到 3-检查中 4-已出结果 5-已审核 6-已发布 7-已取消）',
  `audit_by` varchar(64) COMMENT '审核人（初审）',
  `audit_sign_id` bigint COMMENT '审核医师签名ID',
  `audit_signed_time` datetime COMMENT '审核签名时刻',
  `audit_time` datetime COMMENT '审核时间',
  `audit2_by` varchar(64) COMMENT '复审人',
  `audit2_time` datetime COMMENT '复审时间',
  `report_time` datetime COMMENT '报告发布时间',
  `report_by` varchar(64) COMMENT '报告发布人',
  `cancel_time` datetime COMMENT '取消时间',
  `cancel_reason` varchar(200) COMMENT '取消原因',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查记录';

-- biz_medicaltech_execution  医技执行记录
CREATE TABLE `biz_medicaltech_execution` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `execution_no` varchar(32) NOT NULL COMMENT '执行单号',
  `apply_type` tinyint NOT NULL COMMENT '申请类型（1-检查 2-检验）',
  `apply_id` bigint NOT NULL COMMENT '申请单ID',
  `apply_no` varchar(32) COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) COMMENT '患者姓名',
  `item_id` bigint COMMENT '项目ID',
  `item_code` varchar(32) COMMENT '项目编码',
  `item_name` varchar(100) NOT NULL COMMENT '项目名称',
  `execution_status` tinyint NOT NULL DEFAULT 1 COMMENT '执行状态（1-待执行 2-执行中 3-已完成 4-已审核）',
  `executor_id` bigint COMMENT '执行人ID',
  `executor_name` varchar(50) COMMENT '执行人姓名',
  `execute_time` datetime COMMENT '执行时间',
  `complete_time` datetime COMMENT '完成时间',
  `reviewer_id` bigint COMMENT '审核人ID',
  `reviewer_name` varchar(50) COMMENT '审核人姓名',
  `review_time` datetime COMMENT '审核时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_execution_no` (`execution_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医技执行记录';

-- biz_report  报告单
CREATE TABLE `biz_report` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `report_no` varchar(32) NOT NULL COMMENT '报告编号（唯一）',
  `report_type` tinyint NOT NULL COMMENT '报告类型（1-检查报告 2-检验报告）',
  `record_id` bigint NOT NULL COMMENT '检查/检验记录ID',
  `record_no` varchar(32) NOT NULL COMMENT '检查/检验记录号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女）',
  `age` int COMMENT '年龄',
  `visit_date` date COMMENT '就诊日期',
  `item_name` varchar(200) NOT NULL COMMENT '项目名称',
  `exam_method` varchar(200) COMMENT '检查方法',
  `exam_dept_name` varchar(100) COMMENT '检查/检验科室',
  `apply_dept_name` varchar(100) COMMENT '申请科室',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) COMMENT '临床诊断',
  `report_content` text COMMENT '报告内容',
  `conclusion` text COMMENT '报告结论',
  `positive_flag` tinyint COMMENT '阴阳性（0-未判定 1-阴性 2-阳性 3-未见异常）',
  `is_critical` tinyint NOT NULL DEFAULT 0 COMMENT '是否危急（0-否 1-是）',
  `write_by` varchar(64) COMMENT '报告书写人',
  `write_by_id` bigint COMMENT '报告书写人员工ID',
  `write_time` datetime COMMENT '报告书写时间',
  `template_id` bigint COMMENT '使用的报告模板ID',
  `reject_reason` varchar(500) COMMENT '退回原因',
  `report_version` int NOT NULL DEFAULT 1 COMMENT '报告版本号',
  `film_count` int NOT NULL DEFAULT 0 COMMENT '已登记胶片张数',
  `suggestions` text COMMENT '建议',
  `report_status` tinyint DEFAULT 1 COMMENT '报告状态（1-待审核 2-初审通过 3-已审核 4-已发布 5-已作废）',
  `audit_by` varchar(64) COMMENT '审核人（初审）',
  `audit_time` datetime COMMENT '审核时间',
  `audit2_by` varchar(64) COMMENT '复审人',
  `audit2_time` datetime COMMENT '复审时间',
  `publish_time` datetime COMMENT '发布时间',
  `publish_by` varchar(64) COMMENT '发布人',
  `is_urgent` tinyint DEFAULT 0 COMMENT '是否加急（0-否 1-是）',
  `report_file_path` varchar(500) COMMENT '报告文件路径',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_no` (`report_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报告单';

-- biz_exam_device  检查设备档位
CREATE TABLE `biz_exam_device` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `device_code` varchar(32) NOT NULL COMMENT '预约设备编码',
  `device_name` varchar(100) NOT NULL COMMENT '设备名称',
  `device_type` tinyint NOT NULL COMMENT '设备类别（1-CT 2-MR 3-DR 4-超声 5-心电 6-内镜 7-其他）',
  `equipment_id` bigint COMMENT '设备台账ID',
  `dept_id` bigint COMMENT '检查科室ID',
  `dept_name` varchar(100) COMMENT '检查科室名称',
  `room_name` varchar(100) COMMENT '检查室/机房位置',
  `am_start` char(5) NOT NULL DEFAULT '08:00' COMMENT '上午开放开始（HH:mm）',
  `am_end` char(5) NOT NULL DEFAULT '12:00' COMMENT '上午开放结束（HH:mm）',
  `pm_start` char(5) COMMENT '下午开放开始（HH:mm）',
  `pm_end` char(5) COMMENT '下午开放结束（HH:mm）',
  `slot_minutes` int NOT NULL DEFAULT 30 COMMENT '号源粒度',
  `parallel_count` int NOT NULL DEFAULT 1 COMMENT '单格子并行号数',
  `ahead_days` int NOT NULL DEFAULT 7 COMMENT '可提前预约天数',
  `max_slot_minutes` int NOT NULL DEFAULT 240 COMMENT '可占号最长时长（分钟）',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（1-开放预约 2-暂停预约）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_device_code` (`device_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查设备档位';

-- biz_exam_device_item  设备可开展项目
CREATE TABLE `biz_exam_device_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `device_id` bigint NOT NULL COMMENT '设备ID',
  `item_id` bigint NOT NULL COMMENT '检查项目ID',
  `item_code` varchar(32) COMMENT '项目编码',
  `item_name` varchar(200) COMMENT '项目名称',
  `exam_minutes` int COMMENT '该设备做该项目的时长（分钟）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_device_item` (`device_id`, `item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备可开展项目';

-- biz_exam_slot  检查设备号源时段
CREATE TABLE `biz_exam_slot` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `device_id` bigint NOT NULL COMMENT '设备ID',
  `slot_date` date NOT NULL COMMENT '号源日期',
  `seq` int COMMENT '段序',
  `start_time` char(5) NOT NULL COMMENT '段开始时间（HH:mm）',
  `end_time` char(5) NOT NULL COMMENT '段结束时间（HH:mm）',
  `total_source` int NOT NULL DEFAULT 1 COMMENT '段号源总数',
  `used_source` int NOT NULL DEFAULT 0 COMMENT '段已占号数',
  `available_source` int NOT NULL DEFAULT 1 COMMENT '段剩余号源',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '段状态（0-停用锁号 1-正常）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_slot` (`device_id`, `slot_date`, `start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查设备号源时段';

-- biz_exam_appointment  检查预约单
CREATE TABLE `biz_exam_appointment` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `appt_no` varchar(32) NOT NULL COMMENT '预约单号',
  `active_flag` tinyint DEFAULT 1 COMMENT '有效标记',
  `apply_id` bigint NOT NULL COMMENT '检查申请单ID',
  `apply_no` varchar(32) COMMENT '申请单号',
  `prev_apply_status` tinyint COMMENT '预约前申请状态',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女 9-未知）',
  `age` int COMMENT '年龄',
  `apply_dept_id` bigint COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) COMMENT '申请科室',
  `doctor_id` bigint COMMENT '申请医生ID',
  `doctor_name` varchar(50) COMMENT '申请医生',
  `item_id` bigint COMMENT '检查项目ID',
  `item_code` varchar(32) COMMENT '项目编码',
  `item_name` varchar(200) COMMENT '项目名称',
  `body_part` varchar(200) COMMENT '检查部位',
  `exam_minutes` int COMMENT '本次占用时长',
  `device_id` bigint NOT NULL COMMENT '设备ID',
  `device_code` varchar(32) COMMENT '设备编码',
  `device_name` varchar(100) COMMENT '设备名称',
  `exam_dept_id` bigint COMMENT '检查科室ID',
  `exam_dept_name` varchar(100) COMMENT '检查科室名称',
  `room_name` varchar(100) COMMENT '检查室',
  `exam_date` date NOT NULL COMMENT '检查日期',
  `start_time` char(5) NOT NULL COMMENT '开始时间（HH:mm）',
  `end_time` char(5) NOT NULL COMMENT '结束时间（HH:mm）',
  `is_emergency` tinyint DEFAULT 0 COMMENT '是否急诊（0-否 1-是）',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（1-已预约 2-已到检 3-已完成 4-已取消 5-爽约）',
  `book_by` varchar(64) COMMENT '预约操作人',
  `book_time` datetime COMMENT '预约操作时间',
  `arrive_time` datetime COMMENT '到检时间',
  `finish_time` datetime COMMENT '检查完成时间',
  `cancel_time` datetime COMMENT '取消时间',
  `cancel_reason` varchar(500) COMMENT '取消原因',
  `noshow_time` datetime COMMENT '爽约判定时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exam_appt_active` (`apply_id`, `active_flag`),
  UNIQUE KEY `uk_exam_appt_no` (`appt_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查预约单';

-- biz_exam_image  检查影像帧
CREATE TABLE `biz_exam_image` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `biz_type` tinyint NOT NULL DEFAULT 1 COMMENT '影像来源单据类型',
  `apply_id` bigint NOT NULL COMMENT '申请单ID',
  `apply_no` varchar(64) COMMENT '申请单号',
  `record_id` bigint COMMENT '执行记录ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_name` varchar(64) COMMENT '患者姓名',
  `item_name` varchar(200) COMMENT '检查/检验项目名称',
  `body_part` varchar(100) COMMENT '检查部位',
  `modality` tinyint COMMENT '影像模态（1-CT 2-MR 3-DR 4-超声 5-心电 6-内镜 7-其他）',
  `seq` int NOT NULL DEFAULT 1 COMMENT '本申请单内的帧序号',
  `file_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `file_url` varchar(500) NOT NULL COMMENT '访问路径',
  `file_size` bigint COMMENT '文件字节数',
  `mime_type` varchar(64) COMMENT '文件MIME类型',
  `source` tinyint NOT NULL DEFAULT 1 COMMENT '来源（1-工作站上传 2-模拟）',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '上传人',
  `create_time` datetime COMMENT '上传时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查影像帧';

-- biz_exam_film  检查胶片用量
CREATE TABLE `biz_exam_film` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `film_no` varchar(32) NOT NULL COMMENT '胶片单号',
  `record_id` bigint NOT NULL COMMENT '检查记录ID',
  `record_no` varchar(32) COMMENT '检查记录号',
  `apply_id` bigint COMMENT '检查申请单ID',
  `apply_no` varchar(32) COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(64) COMMENT '患者姓名',
  `visit_date` date COMMENT '就诊日期',
  `item_code` varchar(32) COMMENT '检查项目编码',
  `item_name` varchar(200) COMMENT '检查项目名称',
  `body_part` varchar(100) COMMENT '检查部位',
  `modality` tinyint COMMENT '影像模态（，快照）',
  `spec_id` bigint NOT NULL COMMENT '胶片规格ID',
  `spec_code` varchar(32) COMMENT '规格编码',
  `spec_name` varchar(100) NOT NULL COMMENT '规格名称',
  `unit_price` decimal(10,2) NOT NULL COMMENT '单价',
  `unit` varchar(20) COMMENT '计价单位',
  `quantity` int NOT NULL COMMENT '胶片张数',
  `amount` decimal(12,2) NOT NULL COMMENT '金额 = 单价 × 张数',
  `film_status` tinyint NOT NULL DEFAULT 1 COMMENT '胶片状态（1-已登记 2-已打印 3-已发放 4-已作废）',
  `charge_flag` tinyint NOT NULL DEFAULT 0 COMMENT '是否已记账（0-未记账 1-已记账）',
  `fee_id` bigint COMMENT '记账流水ID',
  `fee_no` varchar(32) COMMENT '记账流水号',
  `print_by` varchar(64) COMMENT '打印人',
  `print_time` datetime COMMENT '打印时间',
  `deliver_by` varchar(64) COMMENT '发放人',
  `deliver_time` datetime COMMENT '发放时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_film_no` (`film_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查胶片用量';

-- biz_film_spec  胶片规格价目
CREATE TABLE `biz_film_spec` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `spec_code` varchar(32) NOT NULL COMMENT '规格编码',
  `spec_name` varchar(100) NOT NULL COMMENT '规格名称',
  `unit_price` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '单价',
  `unit` varchar(20) NOT NULL DEFAULT '张' COMMENT '计价单位',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_spec_code` (`spec_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='胶片规格价目';

-- biz_radio_report_template  放射报告模板
CREATE TABLE `biz_radio_report_template` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `template_code` varchar(32) NOT NULL COMMENT '模板编码',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `modality` tinyint COMMENT '适用模态',
  `item_code` varchar(32) COMMENT '适用检查项目编码',
  `item_name` varchar(200) COMMENT '适用检查项目名称',
  `body_part` varchar(100) COMMENT '适用检查部位',
  `exam_method` varchar(200) COMMENT '检查方法模板',
  `finding_tpl` text COMMENT '影像所见模板',
  `impression_tpl` text COMMENT '影像诊断/印象模板',
  `suggestion_tpl` text COMMENT '建议模板',
  `is_public` tinyint NOT NULL DEFAULT 1 COMMENT '是否公用（1-科室公用 0-个人模板）',
  `doctor_id` bigint COMMENT '归属医生',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_code` (`template_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='放射报告模板';

-- biz_ultrasound_record  超声检查记录
CREATE TABLE `biz_ultrasound_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '超声检查号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女 9-未知）',
  `age` int COMMENT '年龄',
  `visit_date` date COMMENT '就诊日期',
  `apply_dept_id` bigint COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) COMMENT '申请科室',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) COMMENT '临床诊断',
  `us_type` tinyint DEFAULT 1 COMMENT '超声类型（1-腹部 2-心脏 3-妇产 4-血管 5-浅表器官 6-肌骨 7-腔内）',
  `body_part` varchar(200) COMMENT '检查部位',
  `exam_purpose` varchar(500) COMMENT '检查目的',
  `findings` text COMMENT '超声所见',
  `conclusion` text COMMENT '超声提示（结论）',
  `suggestion` varchar(1000) COMMENT '建议',
  `sonographer` varchar(64) COMMENT '检查医师',
  `execute_time` datetime COMMENT '检查时间',
  `status` tinyint DEFAULT 1 COMMENT '状态（1-已登记 2-已签到 3-检查中 4-已出报告 5-已审核 6-已发布 7-已取消）',
  `report_by` varchar(64) COMMENT '报告医师',
  `report_time` datetime COMMENT '报告时间',
  `audit_by` varchar(64) COMMENT '审核医师',
  `audit_time` datetime COMMENT '审核时间',
  `publish_by` varchar(64) COMMENT '发布人',
  `publish_time` datetime COMMENT '发布时间',
  `cancel_time` datetime COMMENT '取消时间',
  `cancel_reason` varchar(500) COMMENT '取消原因',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='超声检查记录';

-- biz_ultrasound_measure  超声测量值
CREATE TABLE `biz_ultrasound_measure` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_id` bigint NOT NULL COMMENT '超声记录ID',
  `record_no` varchar(32) NOT NULL COMMENT '超声检查号',
  `measure_name` varchar(100) NOT NULL COMMENT '测量项',
  `measure_value` varchar(100) COMMENT '测量值',
  `unit` varchar(20) COMMENT '单位',
  `reference_range` varchar(100) COMMENT '参考范围',
  `abnormal_flag` tinyint DEFAULT 0 COMMENT '异常标志（0-正常 1-偏高 2-偏低 3-异常）',
  `sort_order` int DEFAULT 0 COMMENT '排序号',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='超声测量值';

-- biz_pathology_order  病理检查主单
CREATE TABLE `biz_pathology_order` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_no` varchar(32) NOT NULL COMMENT '病理号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女 9-未知）',
  `age` int COMMENT '年龄',
  `visit_date` date COMMENT '就诊日期',
  `apply_dept_id` bigint COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) COMMENT '申请科室',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) COMMENT '临床诊断',
  `exam_type` tinyint DEFAULT 1 COMMENT '病理检查类型（1-常规石蜡 2-术中冰冻 3-细胞学 4-免疫组化 5-疑难会诊）',
  `specimen_type` varchar(100) COMMENT '标本类型（活检/切除/穿刺/脱落细胞等）',
  `specimen_part` varchar(200) COMMENT '取材部位',
  `is_frozen` tinyint DEFAULT 0 COMMENT '是否冰冻（0-否 1-是）',
  `frozen_result` varchar(500) COMMENT '术中冰冻快速诊断结果',
  `receive_time` datetime COMMENT '标本接收时间',
  `receive_by` varchar(64) COMMENT '标本接收人',
  `sampling_time` datetime COMMENT '取材时间',
  `sampling_by` varchar(64) COMMENT '取材人',
  `embedding_time` datetime COMMENT '包埋时间',
  `embedding_by` varchar(64) COMMENT '包埋人',
  `slice_time` datetime COMMENT '制片（切片）',
  `slice_by` varchar(64) COMMENT '制片人',
  `gross_findings` text COMMENT '肉眼所见',
  `microscopy_findings` text COMMENT '镜下所见',
  `ihc_result` varchar(1000) COMMENT '免疫组化 / 特殊染色结果',
  `diagnosis` text COMMENT '病理诊断',
  `suggestion` varchar(1000) COMMENT '建议',
  `status` tinyint DEFAULT 1 COMMENT '状态',
  `report_by` varchar(64) COMMENT '初诊医师',
  `report_time` datetime COMMENT '初诊时间',
  `audit_by` varchar(64) COMMENT '审核医师',
  `audit_time` datetime COMMENT '审核时间',
  `publish_by` varchar(64) COMMENT '发布人',
  `publish_time` datetime COMMENT '发布时间',
  `cancel_time` datetime COMMENT '取消时间',
  `cancel_reason` varchar(500) COMMENT '取消原因',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病理检查主单';

-- biz_pathology_block  病理蜡块与切片
CREATE TABLE `biz_pathology_block` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `order_id` bigint NOT NULL COMMENT '病理主单ID',
  `order_no` varchar(32) NOT NULL COMMENT '病理号',
  `block_no` varchar(32) NOT NULL COMMENT '蜡块号',
  `part_desc` varchar(200) COMMENT '取材部位描述',
  `block_count` int DEFAULT 1 COMMENT '蜡块数',
  `slice_count` int DEFAULT 0 COMMENT '切片数',
  `slide_no` varchar(50) COMMENT '切片号',
  `status` tinyint DEFAULT 1 COMMENT '状态（1-待取材 2-已取材 3-已包埋 4-已切片）',
  `sampling_by` varchar(64) COMMENT '取材人',
  `sampling_time` datetime COMMENT '取材时间',
  `embedding_by` varchar(64) COMMENT '包埋人',
  `embedding_time` datetime COMMENT '包埋时间',
  `slice_by` varchar(64) COMMENT '切片人',
  `slice_time` datetime COMMENT '切片时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病理蜡块与切片';

-- biz_endoscopy_record  内镜检查记录
CREATE TABLE `biz_endoscopy_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '内镜检查号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女 9-未知）',
  `age` int COMMENT '年龄',
  `visit_date` date COMMENT '就诊日期',
  `apply_dept_id` bigint COMMENT '申请科室ID',
  `apply_dept_name` varchar(100) COMMENT '申请科室',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(50) COMMENT '申请医生',
  `clinical_diagnosis` varchar(500) COMMENT '临床诊断',
  `endo_type` tinyint DEFAULT 1 COMMENT '内镜类型（1-胃镜 2-肠镜 3-支气管镜 4-膀胱镜 5-宫腔镜 6-喉镜 7-ERCP 8-胶囊内镜）',
  `anesthesia_method` tinyint DEFAULT 1 COMMENT '麻醉方式（1-无麻醉 2-表面麻醉 3-静脉麻醉 4-全身麻醉）',
  `body_part` varchar(200) COMMENT '检查部位 / 到达范围',
  `exam_purpose` varchar(500) COMMENT '检查目的',
  `bowel_prep_score` tinyint COMMENT '肠道准备质量 Boston 评分',
  `hp_result` tinyint DEFAULT 0 COMMENT '幽门螺杆菌（0-未查 1-阴性 2-阳性）',
  `findings` text COMMENT '内镜所见',
  `diagnosis` text COMMENT '内镜诊断',
  `suggestion` varchar(1000) COMMENT '建议',
  `biopsy_flag` tinyint DEFAULT 0 COMMENT '是否活检（0-否 1-是）',
  `biopsy_part` varchar(200) COMMENT '活检部位',
  `biopsy_count` int DEFAULT 0 COMMENT '活检块数',
  `pathology_order_no` varchar(32) COMMENT '关联病理号',
  `endoscopist` varchar(64) COMMENT '内镜医师',
  `execute_time` datetime COMMENT '检查时间',
  `status` tinyint DEFAULT 1 COMMENT '状态（1-已登记 2-已签到 3-检查中 4-已出报告 5-已审核 6-已发布 7-已取消）',
  `report_by` varchar(64) COMMENT '报告医师',
  `report_time` datetime COMMENT '报告时间',
  `audit_by` varchar(64) COMMENT '审核医师',
  `audit_time` datetime COMMENT '审核时间',
  `publish_by` varchar(64) COMMENT '发布人',
  `publish_time` datetime COMMENT '发布时间',
  `cancel_time` datetime COMMENT '取消时间',
  `cancel_reason` varchar(500) COMMENT '取消原因',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内镜检查记录';

-- biz_ecg_waveform  心电波形采集
CREATE TABLE `biz_ecg_waveform` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `wave_no` varchar(32) NOT NULL COMMENT '波形号',
  `record_id` bigint NOT NULL COMMENT '检查记录ID',
  `record_no` varchar(32) COMMENT '检查记录号',
  `apply_id` bigint COMMENT '检查申请单ID（冗余）',
  `apply_no` varchar(32) COMMENT '申请单号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(64) COMMENT '患者姓名',
  `ecg_type` tinyint NOT NULL DEFAULT 1 COMMENT '心电类型（1-常规静息心电图 2-24小时动态心电图）',
  `wave_data` longtext COMMENT '波形数据',
  `device_no` varchar(64) COMMENT '采集设备号',
  `collect_by` varchar(64) COMMENT '采集人',
  `collect_time` datetime COMMENT '采集时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wave_no` (`wave_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='心电波形采集';

-- biz_ecg_measure  心电测量参数
CREATE TABLE `biz_ecg_measure` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `record_id` bigint NOT NULL COMMENT '检查记录ID',
  `waveform_id` bigint COMMENT '波形ID',
  `hr` int COMMENT '心率（次/分）',
  `pr_ms` int COMMENT 'PR间期',
  `qrs_ms` int COMMENT 'QRS时限',
  `qt_ms` int COMMENT 'QT间期（ms）',
  `qtc_ms` int COMMENT 'QTc校正间期',
  `p_axis` int COMMENT 'P电轴（°）',
  `qrs_axis` int COMMENT 'QRS电轴',
  `t_axis` int COMMENT 'T电轴（°）',
  `rhythm_text` varchar(100) COMMENT '节律描述',
  `measure_by` varchar(64) COMMENT '测量人',
  `measure_time` datetime COMMENT '测量时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='心电测量参数';

-- biz_ecg_holter  Holter 动态心电
CREATE TABLE `biz_ecg_holter` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `record_id` bigint NOT NULL COMMENT '检查记录ID',
  `waveform_id` bigint COMMENT '波形ID',
  `wear_start_time` datetime COMMENT '开始佩戴时间',
  `wear_end_time` datetime COMMENT '结束佩戴时间',
  `total_beats` int COMMENT '总心搏数',
  `avg_hr` int COMMENT '平均心率（次/分）',
  `max_hr` int COMMENT '最快心率（次/分）',
  `max_hr_time` varchar(16) COMMENT '最快心率时刻（HH:mm）',
  `min_hr` int COMMENT '最慢心率（次/分）',
  `min_hr_time` varchar(16) COMMENT '最慢心率时刻（HH:mm）',
  `afib_flag` tinyint COMMENT '是否检出房颤（0-否 1-是）',
  `afib_beats` int COMMENT '房颤心搏数',
  `svc_count` int COMMENT '室上性早搏总数',
  `pvc_count` int COMMENT '室性早搏总数',
  `vt_count` int COMMENT '室性心动过速阵数',
  `pause_count` int COMMENT '停搏',
  `longest_pause_ms` int COMMENT '最长停搏时长',
  `st_episode_count` int COMMENT 'ST段异常发作阵数',
  `hourly_hr_json` text COMMENT '24小时逐时平均心率',
  `analysis_by` varchar(64) COMMENT '分析人',
  `analysis_time` datetime COMMENT '分析时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Holter 动态心电';

-- biz_ecg_template  心电报告模板
CREATE TABLE `biz_ecg_template` (
  `id` bigint NOT NULL COMMENT '主键ID（雪花）',
  `template_code` varchar(32) NOT NULL COMMENT '模板编码',
  `template_name` varchar(100) NOT NULL COMMENT '模板名称',
  `ecg_type` tinyint COMMENT '适用心电类型',
  `finding_tpl` text COMMENT '心电图所见模板',
  `conclusion_tpl` text COMMENT '心电图诊断模板',
  `suggestion_tpl` text COMMENT '建议模板',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ecg_tpl_code` (`template_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='心电报告模板';

-- biz_appoint_info  挂号信息
CREATE TABLE `biz_appoint_info` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `regist_no` varchar(32) NOT NULL COMMENT '挂号单号（唯一）',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别（1-男 2-女 3-未知）',
  `age` int COMMENT '年龄',
  `phone` varchar(20) COMMENT '手机号码',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `room_id` bigint COMMENT '诊室ID',
  `room_name` varchar(100) COMMENT '诊室名称',
  `doctor_id` bigint COMMENT '医生ID',
  `doctor_name` varchar(50) COMMENT '医生姓名',
  `schedule_id` bigint COMMENT '排班ID',
  `slot_id` bigint COMMENT '排班时间片段ID',
  `slot_start` char(5) COMMENT '就诊时段开始快照（HH:mm）',
  `slot_end` char(5) COMMENT '就诊时段结束快照（HH:mm）',
  `regist_type` tinyint DEFAULT 1 COMMENT '挂号类型（1-普通号 2-专家号 3-急诊号 4-免费号）',
  `regist_source` tinyint DEFAULT 1 COMMENT '挂号来源（1-窗口挂号 2-自助机挂号 3-网上挂号 4-预约挂号）',
  `regist_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '挂号时间',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `arrive_time` datetime COMMENT '到达时间',
  `schedule_type` tinyint COMMENT '时间段（1-上午 2-下午 3-全天 4-凌晨）',
  `slot_time` varchar(8) COMMENT '就诊时段',
  `visit_type` tinyint NOT NULL COMMENT '就诊类型（号别）（1-初诊 2-复诊）',
  `revisit_source` tinyint COMMENT '复诊来源（1-当日回诊 2-医嘱复诊预约 3-患者自助复诊 4-随访计划复诊）',
  `settlement_type` tinyint DEFAULT 1 COMMENT '结算方式（1-自费 2-城镇职工医保 3-城乡居民医保 4-公费 5-商业保险）',
  `medical_insurance_type` varchar(50) COMMENT '医保类型（如：在职职工、退休职工、城乡居民等）',
  `medical_insurance_no` varchar(50) COMMENT '医保卡号',
  `regist_status` tinyint DEFAULT 1 COMMENT '挂号状态（1-已挂号 2-已签到 3-已接诊 4-已就诊 5-已退号 6-已过号 7-爽约 8-未就诊）',
  `revisit_type` tinyint COMMENT '【已废置】改用 visit_type',
  `revisit_record_id` bigint COMMENT '复诊关联的病历ID',
  `refund_time` datetime COMMENT '退号时间',
  `refund_reason` varchar(200) COMMENT '退号原因',
  `bill_id` bigint COMMENT '挂号费结算账单ID',
  `bill_no` varchar(32) COMMENT '账单号',
  `create_by` varchar(64) COMMENT '创建人',
  `create_by_id` bigint COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_by_id` bigint COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_regist_no` (`regist_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='挂号信息';

-- biz_compliance_audit_item  医保合规审核明细
CREATE TABLE `biz_compliance_audit_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `audit_id` bigint NOT NULL COMMENT '审核ID',
  `rule_code` varchar(16) NOT NULL COMMENT '规则编码',
  `rule_name` varchar(100) NOT NULL COMMENT '规则名称',
  `rule_group` char(1) NOT NULL COMMENT '规则分组',
  `result` tinyint NOT NULL COMMENT '结果（1-命中 2-通过 3-不适用）',
  `risk_level` tinyint NOT NULL DEFAULT 0 COMMENT '风险等级（1-提示 2-关注 3-高危）',
  `target_type` tinyint NOT NULL DEFAULT 0 COMMENT '对象（0-清单级 1-诊断 2-手术操作）',
  `target_id` bigint COMMENT '对象ID',
  `target_code` varchar(32) COMMENT '对象编码',
  `target_name` varchar(200) COMMENT '对象名称',
  `evidence` varchar(1000) COMMENT '判定依据',
  `suggestion` varchar(500) COMMENT '整改建议',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医保合规审核明细';

-- biz_emr_signature  电子签名证据
CREATE TABLE `biz_emr_signature` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `sign_no` varchar(32) NOT NULL COMMENT '签名流水号',
  `biz_type` tinyint NOT NULL COMMENT '签名对象类型',
  `biz_id` bigint NOT NULL COMMENT '签名对象ID',
  `biz_no` varchar(64) COMMENT '对象单号',
  `patient_id` bigint COMMENT '患者ID',
  `patient_name` varchar(50) COMMENT '患者姓名',
  `dept_id` bigint COMMENT '对象所属科室ID',
  `dept_name` varchar(64) COMMENT '对象所属科室名称',
  `sign_scene` tinyint NOT NULL COMMENT '签名场景',
  `chain_no` int NOT NULL DEFAULT 1 COMMENT '同对象第几次签名',
  `prev_sign_id` bigint COMMENT '前一次签名ID',
  `prev_digest` varchar(128) COMMENT '前一次签名摘要',
  `signer_id` bigint NOT NULL COMMENT '签名人员工ID',
  `signer_name` varchar(64) NOT NULL COMMENT '签名人姓名',
  `signer_dept_id` bigint COMMENT '签名人科室ID',
  `signer_dept_name` varchar(64) COMMENT '签名人科室名称',
  `signer_title` varchar(64) COMMENT '签名人职称',
  `cert_id` bigint NOT NULL COMMENT '所用证书ID',
  `cert_no` varchar(32) NOT NULL COMMENT '所用证书编号',
  `digest_algo` varchar(16) NOT NULL COMMENT '摘要算法',
  `sign_algo` varchar(32) NOT NULL COMMENT '签名算法',
  `content_digest` varchar(128) NOT NULL COMMENT '被签内容摘要',
  `sign_value` text NOT NULL COMMENT '签名值',
  `content_snapshot` mediumtext COMMENT '被签内容快照',
  `signed_time` datetime NOT NULL COMMENT '签名时刻',
  `time_source` tinyint NOT NULL DEFAULT 1 COMMENT '时间来源（1-本机时钟 2-院内授时服务器 3-第三方TSA）',
  `tsa_serial` varchar(64) COMMENT '第三方时间戳序列号',
  `tsa_time` datetime COMMENT 'TSA 授时时刻',
  `tsa_token` text COMMENT '时间戳令牌',
  `sign_status` tinyint NOT NULL DEFAULT 1 COMMENT '签名状态（1-有效 2-已作废）',
  `verify_status` tinyint NOT NULL DEFAULT 0 COMMENT '最近一次验签结果（0-未校验 1-通过 2-失败）',
  `verify_time` datetime COMMENT '最近一次验签时间',
  `verify_count` int NOT NULL DEFAULT 0 COMMENT '累计验签次数',
  `invalid_reason` varchar(200) COMMENT '作废原因',
  `invalid_time` datetime COMMENT '作废时间',
  `invalid_by` bigint COMMENT '作废操作人员工ID',
  `invalid_by_name` varchar(64) COMMENT '作废操作人姓名',
  `client_ip` varchar(64) COMMENT '签名来源 IP（留痕）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sign_no` (`sign_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电子签名证据';

-- biz_fee_record  费用记账流水
CREATE TABLE `biz_fee_record` (
  `id` bigint NOT NULL COMMENT '主键（雪花）',
  `fee_no` varchar(32) NOT NULL COMMENT '记账流水号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `encounter_type` tinyint NOT NULL COMMENT '就诊类型（1-门诊 2-住院）',
  `encounter_id` bigint NOT NULL COMMENT '就诊标识',
  `encounter_no` varchar(32) COMMENT '就诊标识单号',
  `dept_id` bigint COMMENT '费用归属科室',
  `dept_name` varchar(100) COMMENT '科室名称',
  `doctor_id` bigint COMMENT '开单/执行人员工ID',
  `doctor_name` varchar(50) COMMENT '开单人姓名',
  `item_type` tinyint NOT NULL COMMENT '项目类型（1-挂号费 2-西药 3-中成药 4-中药饮片 5-检查 6-检验 7-治疗 8-耗材）',
  `item_code` varchar(32) COMMENT '项目/药品编码',
  `item_name` varchar(200) NOT NULL COMMENT '项目名称',
  `specification` varchar(100) COMMENT '规格',
  `unit` varchar(20) COMMENT '单位',
  `catalog_type` tinyint COMMENT '医保目录类别（0-自费 1-甲类 2-乙类 3-丙类）',
  `price` decimal(10,4) NOT NULL COMMENT '单价',
  `quantity` decimal(10,2) NOT NULL COMMENT '数量',
  `amount` decimal(12,2) NOT NULL COMMENT '金额=单价×数量',
  `fee_status` tinyint NOT NULL DEFAULT 1 COMMENT '记账状态（1-待结算 2-已锁定 3-已结算 4-已红冲）',
  `source_type` tinyint NOT NULL COMMENT '费用来源',
  `source_id` bigint COMMENT '来源单据ID（处方明细ID/申请ID/医嘱ID…）',
  `source_no` varchar(64) COMMENT '来源单据号',
  `orig_fee_id` bigint COMMENT '红冲双向指针',
  `refunded_amount` decimal(12,2) NOT NULL DEFAULT 0.00 COMMENT '累计已冲金额',
  `book_time` datetime NOT NULL COMMENT '记账时间',
  `book_by_id` bigint COMMENT '记账人员工ID',
  `book_by_name` varchar(64) COMMENT '记账人姓名',
  `bill_id` bigint COMMENT '所属结算账单ID',
  `create_by` varchar(64),
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `update_by` varchar(64),
  `update_time` datetime,
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fee_no` (`fee_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='费用记账流水';

-- biz_medical_record  门诊病历
CREATE TABLE `biz_medical_record` (
  `id` bigint NOT NULL,
  `record_no` varchar(32) NOT NULL COMMENT '病历号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别',
  `age` int COMMENT '年龄',
  `regist_id` bigint NOT NULL COMMENT '挂号ID',
  `regist_no` varchar(32) NOT NULL COMMENT '挂号单号',
  `visit_date` date NOT NULL COMMENT '就诊日期',
  `visit_type` tinyint DEFAULT 1 COMMENT '就诊类型（1-初诊 2-复诊）',
  `dept_id` bigint NOT NULL COMMENT '科室ID',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `doctor_id` bigint NOT NULL COMMENT '医生ID',
  `doctor_name` varchar(50) NOT NULL COMMENT '医生姓名',
  `chief_complaint` text COMMENT '主诉',
  `present_illness` text COMMENT '现病史',
  `past_history` text COMMENT '既往史',
  `personal_history` text COMMENT '个人史',
  `family_history` text COMMENT '家族史',
  `allergy_history` text COMMENT '过敏史',
  `temperature` varchar(10) COMMENT '体温（℃）',
  `pulse` varchar(10) COMMENT '脉搏（次/分）',
  `respiration` varchar(10) COMMENT '呼吸（次/分）',
  `systolic_pressure` varchar(10) COMMENT '收缩压（mmHg）',
  `diastolic_pressure` varchar(10) COMMENT '舒张压（mmHg）',
  `general_condition` text COMMENT '一般情况',
  `skin_mucosa` text COMMENT '皮肤黏膜',
  `head_neck` text COMMENT '头颈部',
  `chest_lung` text COMMENT '胸肺',
  `heart` text COMMENT '心脏',
  `abdomen` text COMMENT '腹部',
  `spine_limbs` text COMMENT '脊柱四肢',
  `nervous_system` text COMMENT '神经系统',
  `specialist_exam` text COMMENT '专科检查',
  `auxiliary_exam` text COMMENT '辅助检查',
  `diagnosis` text COMMENT '诊断',
  `diagnosis_code` varchar(100) COMMENT '诊断编码',
  `diagnosis_name` varchar(500) COMMENT '诊断名称',
  `treatment_plan` text COMMENT '处理意见',
  `record_status` tinyint DEFAULT 1 COMMENT '病历状态（1-草稿 2-已提交 3-已归档 4-已作废）',
  `review_status` tinyint DEFAULT 0 COMMENT '审核状态（0-待提交 1-待审核 2-审核通过 3-审核驳回）',
  `review_by` varchar(64) COMMENT '审核人',
  `review_time` datetime COMMENT '审核时间',
  `review_remark` varchar(500) COMMENT '审核意见',
  `guide_pdf_path` varchar(512) COMMENT '患者引导单文件路径',
  `submit_time` datetime COMMENT '提交时间',
  `archive_time` datetime COMMENT '归档时间',
  `sign_status` tinyint NOT NULL DEFAULT 0 COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint COMMENT '当前有效签名ID',
  `signed_time` datetime COMMENT '最近一次签名时刻',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门诊病历';

-- biz_patient  患者基本信息
CREATE TABLE `biz_patient` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `master_id` bigint COMMENT '主索引',
  `merge_status` tinyint NOT NULL DEFAULT 0 COMMENT '主索引状态（0-正常 1-已并入主档）',
  `merge_time` datetime COMMENT '并入主档的时间',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `birth_date` date COMMENT '出生日期',
  `age` int COMMENT '年龄',
  `id_card` varchar(18) COMMENT '身份证号',
  `phone` varchar(20) COMMENT '手机号码',
  `contact_name` varchar(50) COMMENT '联系人姓名',
  `contact_phone` varchar(20) COMMENT '联系人电话',
  `contact_relation` varchar(20) COMMENT '联系人关系（父母、配偶、子女等）',
  `address` varchar(200) COMMENT '家庭住址',
  `nation` varchar(20) COMMENT '民族',
  `occupation` varchar(50) COMMENT '职业',
  `marital_status` tinyint DEFAULT 0 COMMENT '婚姻状况（0-未婚 1-已婚 2-离异 3-丧偶）',
  `blood_type` varchar(10) COMMENT '血型（A/B/O/AB）',
  `allergy_history` text COMMENT '过敏史',
  `medical_history` text COMMENT '既往病史',
  `patient_type` tinyint DEFAULT 1 COMMENT '患者类型（1-自费 2-城镇职工医保 3-城乡居民医保 4-公费 5-其他）',
  `medical_insurance_no` varchar(50) COMMENT '医保卡号',
  `medical_insurance_type` varchar(50) COMMENT '医保类型',
  `card_type` tinyint DEFAULT 1 COMMENT '卡片类型（1-就诊卡 2-身份证 3-医保卡）',
  `card_no` varchar(50) COMMENT '卡片号码',
  `balance` decimal(10,2) DEFAULT 0.00 COMMENT '账户余额',
  `total_expense` decimal(10,2) DEFAULT 0.00 COMMENT '累计消费金额',
  `visit_count` int DEFAULT 0 COMMENT '就诊次数',
  `last_visit_time` datetime COMMENT '最后就诊时间',
  `last_visit_dept` bigint COMMENT '最后就诊科室',
  `last_visit_doctor` bigint COMMENT '最后就诊医生',
  `last_visit_dept_name` varchar(100) COMMENT '最近就诊科室名',
  `last_visit_doctor_name` varchar(50) COMMENT '最近接诊医生名',
  `first_visit_time` datetime COMMENT '首次就诊时间',
  `first_visit_dept_id` bigint COMMENT '首次就诊科室ID',
  `first_visit_dept_name` varchar(100) COMMENT '首次就诊科室名',
  `first_visit_doctor_id` bigint COMMENT '首次接诊医生ID',
  `first_visit_doctor_name` varchar(50) COMMENT '首次接诊医生名',
  `photo` varchar(200) COMMENT '患者照片',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_patient_no` (`patient_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='患者基本信息';

-- sys_department  科室
CREATE TABLE `sys_department` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `dept_code` varchar(32) NOT NULL COMMENT '科室编码（唯一）',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `dept_type` tinyint NOT NULL DEFAULT 1 COMMENT '科室类型（1-门诊科室 2-医技科室 3-药房 4-住院科室 5-其他）',
  `parent_id` bigint NOT NULL DEFAULT 0 COMMENT '父科室ID',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序号',
  `dept_icon` varchar(200) COMMENT '科室图标',
  `dept_desc` varchar(500) COMMENT '科室描述',
  `contact_phone` varchar(20) COMMENT '联系电话',
  `location` varchar(200) COMMENT '科室位置',
  `is_open` tinyint DEFAULT 1 COMMENT '是否开诊（0-否 1-是）',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dept_code` (`dept_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='科室';

-- sys_employee  员工
CREATE TABLE `sys_employee` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `emp_code` varchar(32) NOT NULL COMMENT '员工编号（唯一）',
  `emp_name` varchar(50) NOT NULL COMMENT '员工姓名',
  `emp_type` tinyint NOT NULL DEFAULT 1 COMMENT '员工类型（1-医生 2-护士 3-收费员 4-药剂师 5-管理员 6-其他）',
  `gender` tinyint DEFAULT 1 COMMENT '性别',
  `birth_date` date COMMENT '出生日期',
  `hire_date` date COMMENT '入职日期',
  `id_card` varchar(18) COMMENT '身份证号',
  `phone` varchar(20) COMMENT '手机号码',
  `email` varchar(100) COMMENT '电子邮箱',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(200) COMMENT '科室ID',
  `title` varchar(50) COMMENT '职称',
  `position` varchar(50) COMMENT '职位',
  `specialty` varchar(200) COMMENT '专业特长',
  `education` varchar(50) COMMENT '学历',
  `avatar` varchar(200) COMMENT '头像地址',
  `is_expert` tinyint DEFAULT 0 COMMENT '是否专家（0-否 1-是）',
  `expert_price` decimal(10,2) DEFAULT 0.00 COMMENT '专家号价格',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_emp_code` (`emp_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工';

-- sys_equipment  医疗设备台账
CREATE TABLE `sys_equipment` (
  `id` bigint NOT NULL COMMENT '主键',
  `equipment_code` varchar(32) NOT NULL COMMENT '设备编码',
  `equipment_name` varchar(200) NOT NULL COMMENT '设备名称',
  `category` tinyint NOT NULL COMMENT '设备类别',
  `dept_id` bigint COMMENT '使用科室ID',
  `dept_name` varchar(100) COMMENT '使用科室名称',
  `brand` varchar(100) COMMENT '品牌',
  `model` varchar(100) COMMENT '型号',
  `purchase_date` date COMMENT '购置日期',
  `purchase_price` decimal(14,2) COMMENT '购置价格(元)',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（1-在用 2-停用 3-维修中 4-报废）',
  `maintain_cycle_days` int DEFAULT 365 COMMENT '维保周期(天)',
  `last_maintain_date` date COMMENT '最近维保日期',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_equipment_code` (`equipment_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医疗设备台账';

-- sys_inspection_item  检查项目字典
CREATE TABLE `sys_inspection_item` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `item_code` varchar(32) NOT NULL COMMENT '项目编码（唯一）',
  `item_name` varchar(200) NOT NULL COMMENT '项目名称',
  `item_type` tinyint NOT NULL DEFAULT 1 COMMENT '项目类型（1-放射检查 2-超声检查 3-心电图 4-内镜检查 5-其他）',
  `dept_id` bigint COMMENT '检查科室ID',
  `body_part` varchar(200) COMMENT '检查部位',
  `price` decimal(10,2) DEFAULT 0.00 COMMENT '检查价格',
  `duration` int DEFAULT 0 COMMENT '检查时长（分钟）',
  `preparation` varchar(500) COMMENT '检查前准备',
  `contraindication` varchar(500) COMMENT '检查禁忌',
  `report_template` text COMMENT '报告模板',
  `is_emergency` tinyint DEFAULT 0 COMMENT '是否支持急诊（0-否 1-是）',
  `is_appointment` tinyint DEFAULT 1 COMMENT '是否需要预约（0-否 1-是）',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_item_code` (`item_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查项目字典';

-- ---------------- 参照关系（E-R 连线） ----------------
ALTER TABLE `biz_ecg_holter` ADD CONSTRAINT `fk_biz_ecg_holter_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inspection_record` (`id`);
ALTER TABLE `biz_ecg_holter` ADD CONSTRAINT `fk_biz_ecg_holter_waveform_id` FOREIGN KEY (`waveform_id`) REFERENCES `biz_ecg_waveform` (`id`);
ALTER TABLE `biz_ecg_measure` ADD CONSTRAINT `fk_biz_ecg_measure_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inspection_record` (`id`);
ALTER TABLE `biz_ecg_measure` ADD CONSTRAINT `fk_biz_ecg_measure_waveform_id` FOREIGN KEY (`waveform_id`) REFERENCES `biz_ecg_waveform` (`id`);
ALTER TABLE `biz_ecg_waveform` ADD CONSTRAINT `fk_biz_ecg_waveform_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inspection_record` (`id`);
ALTER TABLE `biz_ecg_waveform` ADD CONSTRAINT `fk_biz_ecg_waveform_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_inspection_apply` (`id`);
ALTER TABLE `biz_ecg_waveform` ADD CONSTRAINT `fk_biz_ecg_waveform_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_endoscopy_record` ADD CONSTRAINT `fk_biz_endoscopy_record_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_endoscopy_record` ADD CONSTRAINT `fk_biz_endoscopy_record_apply_dept_id` FOREIGN KEY (`apply_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_endoscopy_record` ADD CONSTRAINT `fk_biz_endoscopy_record_apply_doctor_id` FOREIGN KEY (`apply_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_exam_appointment` ADD CONSTRAINT `fk_biz_exam_appointment_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_inspection_apply` (`id`);
ALTER TABLE `biz_exam_appointment` ADD CONSTRAINT `fk_biz_exam_appointment_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_exam_appointment` ADD CONSTRAINT `fk_biz_exam_appointment_apply_dept_id` FOREIGN KEY (`apply_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_exam_appointment` ADD CONSTRAINT `fk_biz_exam_appointment_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_exam_appointment` ADD CONSTRAINT `fk_biz_exam_appointment_item_id` FOREIGN KEY (`item_id`) REFERENCES `biz_compliance_audit_item` (`id`);
ALTER TABLE `biz_exam_appointment` ADD CONSTRAINT `fk_biz_exam_appointment_device_id` FOREIGN KEY (`device_id`) REFERENCES `biz_exam_device` (`id`);
ALTER TABLE `biz_exam_appointment` ADD CONSTRAINT `fk_biz_exam_appointment_exam_dept_id` FOREIGN KEY (`exam_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_exam_device` ADD CONSTRAINT `fk_biz_exam_device_equipment_id` FOREIGN KEY (`equipment_id`) REFERENCES `sys_equipment` (`id`);
ALTER TABLE `biz_exam_device` ADD CONSTRAINT `fk_biz_exam_device_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_exam_device_item` ADD CONSTRAINT `fk_biz_exam_device_item_device_id` FOREIGN KEY (`device_id`) REFERENCES `biz_exam_device` (`id`);
ALTER TABLE `biz_exam_device_item` ADD CONSTRAINT `fk_biz_exam_device_item_item_id` FOREIGN KEY (`item_id`) REFERENCES `sys_inspection_item` (`id`);
ALTER TABLE `biz_exam_film` ADD CONSTRAINT `fk_biz_exam_film_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inspection_record` (`id`);
ALTER TABLE `biz_exam_film` ADD CONSTRAINT `fk_biz_exam_film_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_inspection_apply` (`id`);
ALTER TABLE `biz_exam_film` ADD CONSTRAINT `fk_biz_exam_film_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_exam_film` ADD CONSTRAINT `fk_biz_exam_film_spec_id` FOREIGN KEY (`spec_id`) REFERENCES `biz_film_spec` (`id`);
ALTER TABLE `biz_exam_film` ADD CONSTRAINT `fk_biz_exam_film_fee_id` FOREIGN KEY (`fee_id`) REFERENCES `biz_fee_record` (`id`);
ALTER TABLE `biz_exam_image` ADD CONSTRAINT `fk_biz_exam_image_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_inspection_apply` (`id`);
ALTER TABLE `biz_exam_image` ADD CONSTRAINT `fk_biz_exam_image_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inspection_record` (`id`);
ALTER TABLE `biz_exam_image` ADD CONSTRAINT `fk_biz_exam_image_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_exam_slot` ADD CONSTRAINT `fk_biz_exam_slot_device_id` FOREIGN KEY (`device_id`) REFERENCES `biz_exam_device` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_regist_id` FOREIGN KEY (`regist_id`) REFERENCES `biz_appoint_info` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_medical_record` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_dept_id` FOREIGN KEY (`dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_inspection_item_id` FOREIGN KEY (`inspection_item_id`) REFERENCES `sys_inspection_item` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_inspection_dept_id` FOREIGN KEY (`inspection_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_sign_id` FOREIGN KEY (`sign_id`) REFERENCES `biz_emr_signature` (`id`);
ALTER TABLE `biz_inspection_apply` ADD CONSTRAINT `fk_biz_inspection_apply_report_id` FOREIGN KEY (`report_id`) REFERENCES `biz_report` (`id`);
ALTER TABLE `biz_inspection_record` ADD CONSTRAINT `fk_biz_inspection_record_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_inspection_apply` (`id`);
ALTER TABLE `biz_inspection_record` ADD CONSTRAINT `fk_biz_inspection_record_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_inspection_record` ADD CONSTRAINT `fk_biz_inspection_record_apply_dept_id` FOREIGN KEY (`apply_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_inspection_record` ADD CONSTRAINT `fk_biz_inspection_record_apply_doctor_id` FOREIGN KEY (`apply_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_inspection_record` ADD CONSTRAINT `fk_biz_inspection_record_inspection_item_id` FOREIGN KEY (`inspection_item_id`) REFERENCES `sys_inspection_item` (`id`);
ALTER TABLE `biz_inspection_record` ADD CONSTRAINT `fk_biz_inspection_record_inspection_dept_id` FOREIGN KEY (`inspection_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_inspection_record` ADD CONSTRAINT `fk_biz_inspection_record_report_sign_id` FOREIGN KEY (`report_sign_id`) REFERENCES `biz_emr_signature` (`id`);
ALTER TABLE `biz_inspection_record` ADD CONSTRAINT `fk_biz_inspection_record_audit_sign_id` FOREIGN KEY (`audit_sign_id`) REFERENCES `biz_emr_signature` (`id`);
ALTER TABLE `biz_inspection_template` ADD CONSTRAINT `fk_biz_inspection_template_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_inspection_template` ADD CONSTRAINT `fk_biz_inspection_template_inspection_item_id` FOREIGN KEY (`inspection_item_id`) REFERENCES `sys_inspection_item` (`id`);
ALTER TABLE `biz_medicaltech_execution` ADD CONSTRAINT `fk_biz_medicaltech_execution_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_medicaltech_execution` ADD CONSTRAINT `fk_biz_medicaltech_execution_item_id` FOREIGN KEY (`item_id`) REFERENCES `biz_compliance_audit_item` (`id`);
ALTER TABLE `biz_medicaltech_execution` ADD CONSTRAINT `fk_biz_medicaltech_execution_executor_id` FOREIGN KEY (`executor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_medicaltech_execution` ADD CONSTRAINT `fk_biz_medicaltech_execution_reviewer_id` FOREIGN KEY (`reviewer_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_pathology_block` ADD CONSTRAINT `fk_biz_pathology_block_order_id` FOREIGN KEY (`order_id`) REFERENCES `biz_pathology_order` (`id`);
ALTER TABLE `biz_pathology_order` ADD CONSTRAINT `fk_biz_pathology_order_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_pathology_order` ADD CONSTRAINT `fk_biz_pathology_order_apply_dept_id` FOREIGN KEY (`apply_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_pathology_order` ADD CONSTRAINT `fk_biz_pathology_order_apply_doctor_id` FOREIGN KEY (`apply_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_radio_report_template` ADD CONSTRAINT `fk_biz_radio_report_template_doctor_id` FOREIGN KEY (`doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_report` ADD CONSTRAINT `fk_biz_report_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_report` ADD CONSTRAINT `fk_biz_report_apply_doctor_id` FOREIGN KEY (`apply_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_report` ADD CONSTRAINT `fk_biz_report_write_by_id` FOREIGN KEY (`write_by_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_ultrasound_measure` ADD CONSTRAINT `fk_biz_ultrasound_measure_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_ultrasound_record` (`id`);
ALTER TABLE `biz_ultrasound_record` ADD CONSTRAINT `fk_biz_ultrasound_record_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_ultrasound_record` ADD CONSTRAINT `fk_biz_ultrasound_record_apply_dept_id` FOREIGN KEY (`apply_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_ultrasound_record` ADD CONSTRAINT `fk_biz_ultrasound_record_apply_doctor_id` FOREIGN KEY (`apply_doctor_id`) REFERENCES `sys_employee` (`id`);
