-- ============================================================
-- 领域 15 输血与血库（本域 6 表 + 上游参照 5 表 / 20 条关系）
-- 由 workspace/_er/emit.mjs 从 dev 库 information_schema 反向生成，只用于建模，禁止在业务库执行。
-- 关系 = *_id 列命名推断 + 真实数据覆盖率验证，逐条证据见 docs/er/relationships.csv。
-- PowerDesigner：File → Reverse Engineer → Database → 模板选 MySQL 8.0 → 勾选 Script file 指向本文件。
-- ============================================================


-- biz_transfusion_apply  输血申请单
CREATE TABLE `biz_transfusion_apply` (
  `id` bigint NOT NULL COMMENT '输血申请单ID（雪花）',
  `apply_no` varchar(32) NOT NULL COMMENT '输血申请单号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `admission_no` varchar(32) COMMENT '入院号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女）',
  `age` int COMMENT '年龄',
  `apply_dept_id` bigint COMMENT '申请科室ID',
  `apply_dept_name` varchar(64) COMMENT '申请科室名称',
  `apply_ward_name` varchar(64) COMMENT '申请时所在病区名称',
  `apply_bed_no` varchar(32) COMMENT '申请时床号',
  `apply_doctor_id` bigint COMMENT '申请医生ID',
  `apply_doctor_name` varchar(64) COMMENT '申请医生姓名',
  `apply_time` datetime COMMENT '申请时间',
  `patient_abo` varchar(4) NOT NULL COMMENT '受血者ABO血型',
  `patient_rh` varchar(4) NOT NULL COMMENT '受血者Rh血型',
  `blood_component` tinyint NOT NULL COMMENT '血液品种（1-红细胞悬液 2-血浆 3-血小板 4-冷沉淀 5-全血 6-其他）',
  `component_spec` varchar(64) COMMENT '规格',
  `bag_count` int NOT NULL DEFAULT 1 COMMENT '申请袋数',
  `planned_amount` decimal(10,2) COMMENT '申请总量',
  `amount_ml` int COMMENT '申请量折算毫升数',
  `approve_level` tinyint NOT NULL DEFAULT 1 COMMENT '审批级别（1-上级医师 400-799ml）',
  `approve_status` tinyint NOT NULL DEFAULT 0 COMMENT '审批状态（0-待审批 1-已通过 2-已驳回 3-急诊待补审）',
  `approve_reject_reason` varchar(200) COMMENT '最近一次驳回原因',
  `approve_time` datetime COMMENT '审批通过时间',
  `approve_makeup` tinyint NOT NULL DEFAULT 0 COMMENT '是否急诊补审（0-常规审批 1-急诊后补）',
  `amount_unit` varchar(16) COMMENT '总量单位',
  `transfusion_purpose` varchar(200) COMMENT '输血目的（纠正贫血/补充凝血因子/提升血小板…）',
  `indication` varchar(500) NOT NULL COMMENT '输血指征（Hb/HCT/PLT 指标 + 临床症状，缺了就是无指征用血）',
  `pre_hb` decimal(6,2) COMMENT '输血前血红蛋白 Hb（g/L）',
  `pre_hct` decimal(5,2) COMMENT '输血前红细胞压积 HCT（%）',
  `pre_plt` int COMMENT '输血前血小板 PLT',
  `transfusion_history` varchar(500) COMMENT '既往输血史',
  `reaction_history` varchar(500) COMMENT '既往输血反应史',
  `pregnancy_history` varchar(200) COMMENT '妊娠史',
  `is_emergency` tinyint NOT NULL DEFAULT 0 COMMENT '是否紧急用血（0-否 1-是）',
  `crossmatch_status` tinyint NOT NULL DEFAULT 0 COMMENT '配血状态（0-待配血 1-配血中 3-存在配血不合）',
  `crossmatch_doctor_id` bigint COMMENT '配血人ID',
  `crossmatch_doctor_name` varchar(64) COMMENT '配血人姓名',
  `crossmatch_time` datetime COMMENT '配血完成时间',
  `issue_doctor_id` bigint COMMENT '发血人ID（员工ID）',
  `issue_doctor_name` varchar(64) COMMENT '发血人姓名',
  `issue_time` datetime COMMENT '发血时间',
  `check_items` varchar(200) COMMENT '输血前核对要点码',
  `check_note` varchar(1000) COMMENT '核对补充说明',
  `check_nurse_id` bigint COMMENT '核对护士1 ID（员工ID）',
  `check_nurse_name` varchar(64) COMMENT '核对护士1 姓名',
  `check_nurse2_id` bigint COMMENT '核对护士2 ID',
  `check_nurse2_name` varchar(64) COMMENT '核对护士2 姓名',
  `check_time` datetime COMMENT '双人核对时间',
  `infusion_nurse_id` bigint COMMENT '输注执行护士ID（员工ID）',
  `infusion_nurse_name` varchar(64) COMMENT '输注执行护士姓名',
  `infusion_start_time` datetime COMMENT '输注开始时间',
  `infusion_end_time` datetime COMMENT '输注结束时间',
  `actual_amount` decimal(10,2) COMMENT '实际输注量',
  `infusion_speed` varchar(32) COMMENT '滴速',
  `observation` varchar(1000) COMMENT '输注过程观察',
  `has_reaction` tinyint NOT NULL DEFAULT 0 COMMENT '有无输血反应（0-未上报 1-已上报有反应）',
  `reaction_type` varchar(100) COMMENT '反应类型',
  `reaction_desc` varchar(1000) COMMENT '反应描述',
  `reaction_handle` varchar(1000) COMMENT '处理措施',
  `reaction_reporter_id` bigint COMMENT '上报人ID（员工ID）',
  `reaction_reporter_name` varchar(64) COMMENT '上报人姓名',
  `reaction_time` datetime COMMENT '上报时间',
  `efficacy_eval` varchar(1000) COMMENT '输注后疗效评估',
  `post_hb` decimal(6,2) COMMENT '输血后血红蛋白 Hb（g/L）',
  `post_hct` decimal(5,2) COMMENT '输血后红细胞压积 HCT（%）',
  `post_plt` int COMMENT '输血后血小板 PLT',
  `finish_doctor_id` bigint COMMENT '完成录入人ID（员工ID）',
  `finish_doctor_name` varchar(64) COMMENT '完成录入人姓名',
  `finish_time` datetime COMMENT '完成时间',
  `record_id` bigint COMMENT '回写住院病历ID',
  `transfusion_status` tinyint NOT NULL DEFAULT 0 COMMENT '状态（0-待配血 1-已配血 2-已发血 3-输注中 4-已完成 5-已取消）',
  `cancel_reason` varchar(500) COMMENT '取消原因（仅待配血/已配血/已发血可取消）',
  `cancel_doctor_id` bigint COMMENT '取消人ID（员工ID）',
  `cancel_doctor_name` varchar(64) COMMENT '取消人姓名',
  `cancel_time` datetime COMMENT '取消时间',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='输血申请单';

-- biz_transfusion_approve  用血分级审批流水
CREATE TABLE `biz_transfusion_approve` (
  `id` bigint NOT NULL COMMENT '审批记录ID（雪花）',
  `apply_id` bigint NOT NULL COMMENT '输血申请单ID',
  `apply_no` varchar(32) COMMENT '输血申请单号',
  `approve_level` tinyint NOT NULL COMMENT '审批级别（1-上级医师 2-科主任 3-医务科）',
  `approve_result` tinyint NOT NULL COMMENT '审批结论（1-通过 2-驳回）',
  `approver_id` bigint COMMENT '审批人ID（员工ID）',
  `approver_name` varchar(64) COMMENT '审批人姓名',
  `approver_title` varchar(32) COMMENT '审批人职称',
  `opinion` varchar(200) COMMENT '审批意见',
  `is_makeup` tinyint NOT NULL DEFAULT 0 COMMENT '是否急诊补审（0-常规 1-补审）',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用血分级审批流水';

-- biz_transfusion_bag  输血血袋明细
CREATE TABLE `biz_transfusion_bag` (
  `id` bigint NOT NULL COMMENT '血袋明细ID（雪花）',
  `apply_id` bigint NOT NULL COMMENT '输血申请单ID',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint COMMENT '患者ID（冗余）',
  `bag_no` varchar(64) NOT NULL COMMENT '血袋号',
  `donor_no` varchar(64) COMMENT '献血编号',
  `bag_abo` varchar(4) NOT NULL COMMENT '血袋ABO血型',
  `bag_rh` varchar(4) NOT NULL COMMENT '血袋Rh血型',
  `blood_component` tinyint COMMENT '血液品种',
  `spec` varchar(64) COMMENT '规格',
  `amount` decimal(10,2) COMMENT '血量',
  `amount_unit` varchar(16) COMMENT '血量单位',
  `source_bank` varchar(100) COMMENT '来源血站',
  `collect_date` date COMMENT '采集日期',
  `expire_date` date COMMENT '有效期至',
  `crossmatch_main` varchar(16) COMMENT '主侧配血结果（阴性=相合）',
  `crossmatch_side` varchar(16) COMMENT '次侧配血结果',
  `crossmatch_result` tinyint COMMENT '配血结论（1-相合 2-不合）',
  `crossmatch_time` datetime COMMENT '配血时间',
  `crossmatch_doctor_id` bigint COMMENT '配血人ID（员工ID）',
  `crossmatch_doctor_name` varchar(64) COMMENT '配血人姓名',
  `bag_status` tinyint NOT NULL DEFAULT 0 COMMENT '血袋状态（0-待配血 1-已配血 2-已发血 3-已输注）',
  `issue_time` datetime COMMENT '发血时间',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='输血血袋明细';

-- biz_blood_inventory  血库血袋库存
CREATE TABLE `biz_blood_inventory` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `bag_no` varchar(50) NOT NULL COMMENT '血袋号（唯一）',
  `blood_type` tinyint NOT NULL COMMENT '血型（1-A 2-B 3-O 4-AB）',
  `rh_type` tinyint DEFAULT 1 COMMENT 'Rh 血型（1-阳性 2-阴性）',
  `component_type` tinyint NOT NULL COMMENT '血液成分（1-全血 2-红细胞悬液 3-洗涤红细胞 4-冰冻血浆 5-血小板 6-冷沉淀）',
  `volume` int DEFAULT 0 COMMENT '血量（ml）',
  `unit_amount` decimal(6,2) DEFAULT 0.00 COMMENT '单位（U）',
  `collect_date` date COMMENT '采集日期',
  `expire_date` date COMMENT '失效日期',
  `source_type` tinyint DEFAULT 1 COMMENT '血液来源（1-血站 2-自体储血 3-互助献血）',
  `source_name` varchar(100) COMMENT '来源单位 / 献血人',
  `donor_no` varchar(50) COMMENT '献血码',
  `abo_verify` tinyint DEFAULT 0 COMMENT '血型复核（0-未复核 1-已复核）',
  `storage_loc` varchar(100) COMMENT '存放位置',
  `status` tinyint DEFAULT 1 COMMENT '状态（1-在库 2-已预留 3-已发血 4-已报废 5-已退回）',
  `inbound_by` varchar(64) COMMENT '入库人',
  `inbound_time` datetime COMMENT '入库时间',
  `outbound_by` varchar(64) COMMENT '出库人',
  `outbound_time` datetime COMMENT '出库时间',
  `apply_no` varchar(32) COMMENT '关联用血申请单号',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bag_no` (`bag_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='血库血袋库存';

-- biz_blood_crossmatch  交叉配血记录
CREATE TABLE `biz_blood_crossmatch` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `match_no` varchar(32) NOT NULL COMMENT '配血编号',
  `apply_no` varchar(32) COMMENT '用血申请单号',
  `patient_id` bigint COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者号',
  `patient_name` varchar(50) COMMENT '患者姓名',
  `patient_blood_type` tinyint COMMENT '患者血型（1-A 2-B 3-O 4-AB）',
  `patient_rh_type` tinyint COMMENT '患者 Rh（1-阳性 2-阴性）',
  `bag_no` varchar(50) NOT NULL COMMENT '血袋号',
  `bag_blood_type` tinyint COMMENT '血袋血型',
  `bag_rh_type` tinyint COMMENT '血袋 Rh',
  `component_type` tinyint COMMENT '血液成分',
  `volume` int DEFAULT 0 COMMENT '血量（ml）',
  `method` tinyint DEFAULT 2 COMMENT '配血方法（1-盐水法 2-凝聚胺法 3-抗人球蛋白法 4-微柱凝胶法）',
  `result` tinyint DEFAULT 1 COMMENT '配血结果（1-相合 2-不相合 3-可疑凝集）',
  `conclusion` varchar(500) COMMENT '配血结论',
  `status` tinyint DEFAULT 1 COMMENT '状态（1-待配血 2-已配血 3-已复核 4-已作废）',
  `operator` varchar(64) COMMENT '配血人',
  `match_time` datetime COMMENT '配血时间',
  `verifier` varchar(64) COMMENT '复核人',
  `verify_time` datetime COMMENT '复核时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_match_no` (`match_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交叉配血记录';

-- biz_blood_stock_log  血库出入库流水
CREATE TABLE `biz_blood_stock_log` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `bag_no` varchar(50) NOT NULL COMMENT '血袋号',
  `biz_type` tinyint NOT NULL COMMENT '业务类型（1-入库 2-发血 3-退回 4-报废 5-预留 6-取消预留）',
  `from_status` tinyint COMMENT '变更前状态',
  `to_status` tinyint COMMENT '变更后状态',
  `apply_no` varchar(32) COMMENT '关联用血申请单号',
  `reason` varchar(500) COMMENT '原因',
  `operator` varchar(64) COMMENT '操作人',
  `operate_time` datetime COMMENT '操作时间',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='血库出入库流水';

-- biz_admission  入院记录
CREATE TABLE `biz_admission` (
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `admission_no` varchar(32) NOT NULL COMMENT '入院记录号',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `visit_id` bigint COMMENT '就诊次ID',
  `regist_id` bigint COMMENT '来源挂号ID',
  `regist_no` varchar(32) COMMENT '来源挂号号',
  `admission_order_id` bigint COMMENT '来源住院证ID',
  `admit_dept_id` bigint COMMENT '入院科室ID',
  `dept_id` bigint COMMENT '入院科室ID',
  `ward_id` bigint NOT NULL COMMENT '病区ID',
  `bed_id` bigint NOT NULL COMMENT '床位ID',
  `admit_doctor_id` bigint NOT NULL COMMENT '入院医生ID',
  `admit_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入院时间',
  `admit_way` tinyint COMMENT '入院途径（1-门诊 2-急诊 3-转院 4-其他）',
  `diagnosis` varchar(500) COMMENT '入院诊断',
  `admit_diagnosis_code` varchar(32) COMMENT '入院诊断ICD编码',
  `admit_diagnosis_name` varchar(200) COMMENT '入院诊断名称',
  `discharge_time` datetime COMMENT '出院时间',
  `admit_status` tinyint NOT NULL DEFAULT 1 COMMENT '状态（0-已出院 1-在院）',
  `remark` varchar(500) COMMENT '备注',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  PRIMARY KEY (`admission_id`),
  UNIQUE KEY `uk_admission_no` (`admission_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='入院记录';

-- biz_inpatient_record  住院病历文书
CREATE TABLE `biz_inpatient_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `record_no` varchar(32) NOT NULL COMMENT '病历文书号',
  `admission_id` bigint NOT NULL COMMENT '入院ID',
  `patient_id` bigint NOT NULL COMMENT '患者ID',
  `patient_no` varchar(32) COMMENT '患者编号',
  `patient_name` varchar(50) COMMENT '患者姓名',
  `gender` tinyint COMMENT '性别（1-男 2-女）',
  `age` int COMMENT '年龄',
  `age_unit` tinyint COMMENT '年龄单位（1-岁 2-月 3-天）',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(64) COMMENT '科室名称',
  `ward_id` bigint COMMENT '病区ID',
  `ward_name` varchar(64) COMMENT '病区名称',
  `bed_no` varchar(32) COMMENT '床号',
  `record_type` tinyint NOT NULL COMMENT '文书类型',
  `record_title` varchar(200) COMMENT '文书标题',
  `record_time` datetime NOT NULL COMMENT '记录时间',
  `chief_complaint` varchar(500) COMMENT '主诉',
  `present_illness` text COMMENT '现病史',
  `past_history` text COMMENT '既往史',
  `personal_history` text COMMENT '个人史（含婚育、烟酒、职业）',
  `family_history` text COMMENT '家族史',
  `allergy_history` varchar(500) COMMENT '过敏史',
  `temperature` decimal(4,1) COMMENT '体温（℃）',
  `pulse` int COMMENT '脉搏（次/分）',
  `respiration` int COMMENT '呼吸（次/分）',
  `systolic_pressure` int COMMENT '收缩压（mmHg）',
  `diastolic_pressure` int COMMENT '舒张压（mmHg）',
  `height` decimal(5,1) COMMENT '身高（cm）',
  `weight` decimal(5,1) COMMENT '体重（kg）',
  `general_condition` varchar(500) COMMENT '一般情况（神志/发育/营养/体位/面容）',
  `skin_mucosa` varchar(500) COMMENT '皮肤黏膜',
  `head_neck` varchar(500) COMMENT '头颈部',
  `chest_lung` varchar(500) COMMENT '胸部及肺',
  `heart` varchar(500) COMMENT '心脏',
  `abdomen` varchar(500) COMMENT '腹部',
  `spine_limbs` varchar(500) COMMENT '脊柱四肢',
  `nervous_system` varchar(500) COMMENT '神经系统',
  `specialist_exam` text COMMENT '专科检查',
  `auxiliary_exam` text COMMENT '辅助检查',
  `diagnosis_name` varchar(500) COMMENT '诊断名称',
  `diagnosis_code` varchar(100) COMMENT '诊断编码',
  `treatment_plan` text COMMENT '诊疗计划 / 处理意见',
  `course_note` text COMMENT '病程记录正文',
  `record_status` tinyint NOT NULL DEFAULT 1 COMMENT '文书状态（1-草稿 2-已提交 3-已归档）',
  `doctor_id` bigint COMMENT '书写医生ID',
  `doctor_name` varchar(64) COMMENT '书写医生姓名',
  `submit_time` datetime COMMENT '提交时间',
  `archive_time` datetime COMMENT '归档时间',
  `archive_by` bigint COMMENT '归档人ID（员工ID）',
  `archive_by_name` varchar(64) COMMENT '归档人姓名',
  `sign_status` tinyint NOT NULL DEFAULT 0 COMMENT '签名状态（0-未签名 1-已签名 2-签名已失效）',
  `sign_id` bigint COMMENT '当前有效签名ID',
  `signed_time` datetime COMMENT '最近一次签名时刻',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint NOT NULL DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='住院病历文书';

-- biz_patient  患者基本信息
CREATE TABLE `biz_patient` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `patient_no` varchar(32) NOT NULL COMMENT '患者号',
  `master_id` bigint COMMENT '主索引',
  `merge_status` tinyint NOT NULL DEFAULT 0 COMMENT '主索引状态（0-正常 1-已并入主档）',
  `merge_time` datetime COMMENT '并入主档的时间',
  `patient_name` varchar(50) NOT NULL COMMENT '患者姓名',
  `gender` tinyint NOT NULL COMMENT '性别（1-男 2-女 9-未知）',
  `birth_date` date COMMENT '出生日期',
  `age` int COMMENT '年龄',
  `id_card` varchar(18) COMMENT '身份证号',
  `phone` varchar(20) COMMENT '手机号码',
  `contact_name` varchar(50) COMMENT '联系人姓名',
  `contact_phone` varchar(20) COMMENT '联系人电话',
  `contact_relation` varchar(20) COMMENT '联系人关系（父母、配偶、子女等）',
  `address` varchar(200) COMMENT '家庭住址',
  `nation` varchar(20) COMMENT '民族',
  `occupation` varchar(50) COMMENT '职业',
  `marital_status` tinyint DEFAULT 0 COMMENT '婚姻状况（0-未婚 1-已婚 2-离异 3-丧偶）',
  `blood_type` varchar(10) COMMENT '血型（A/B/O/AB）',
  `allergy_history` text COMMENT '过敏史',
  `medical_history` text COMMENT '既往病史',
  `patient_type` tinyint DEFAULT 1 COMMENT '患者类型（1-自费 2-城镇职工医保 3-城乡居民医保 4-公费 5-其他）',
  `medical_insurance_no` varchar(50) COMMENT '医保卡号',
  `medical_insurance_type` varchar(50) COMMENT '医保类型',
  `card_type` tinyint DEFAULT 1 COMMENT '卡片类型（1-就诊卡 2-身份证 3-医保卡）',
  `card_no` varchar(50) COMMENT '卡片号码',
  `balance` decimal(10,2) DEFAULT 0.00 COMMENT '账户余额',
  `total_expense` decimal(10,2) DEFAULT 0.00 COMMENT '累计消费金额',
  `visit_count` int DEFAULT 0 COMMENT '就诊次数',
  `last_visit_time` datetime COMMENT '最后就诊时间',
  `last_visit_dept` bigint COMMENT '最后就诊科室',
  `last_visit_doctor` bigint COMMENT '最后就诊医生',
  `last_visit_dept_name` varchar(100) COMMENT '最近就诊科室名',
  `last_visit_doctor_name` varchar(50) COMMENT '最近接诊医生名',
  `first_visit_time` datetime COMMENT '首次就诊时间',
  `first_visit_dept_id` bigint COMMENT '首次就诊科室ID',
  `first_visit_dept_name` varchar(100) COMMENT '首次就诊科室名',
  `first_visit_doctor_id` bigint COMMENT '首次接诊医生ID',
  `first_visit_doctor_name` varchar(50) COMMENT '首次接诊医生名',
  `photo` varchar(200) COMMENT '患者照片',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_patient_no` (`patient_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='患者基本信息';

-- sys_department  科室
CREATE TABLE `sys_department` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `dept_code` varchar(32) NOT NULL COMMENT '科室编码（唯一）',
  `dept_name` varchar(100) NOT NULL COMMENT '科室名称',
  `dept_type` tinyint NOT NULL DEFAULT 1 COMMENT '科室类型（1-门诊科室 2-医技科室 3-药房 4-住院科室 5-其他）',
  `parent_id` bigint NOT NULL DEFAULT 0 COMMENT '父科室ID',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序号',
  `dept_icon` varchar(200) COMMENT '科室图标',
  `dept_desc` varchar(500) COMMENT '科室描述',
  `contact_phone` varchar(20) COMMENT '联系电话',
  `location` varchar(200) COMMENT '科室位置',
  `is_open` tinyint DEFAULT 1 COMMENT '是否开诊（0-否 1-是）',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dept_code` (`dept_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='科室';

-- sys_employee  员工
CREATE TABLE `sys_employee` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `emp_code` varchar(32) NOT NULL COMMENT '员工编号（唯一）',
  `emp_name` varchar(50) NOT NULL COMMENT '员工姓名',
  `emp_type` tinyint NOT NULL DEFAULT 1 COMMENT '员工类型（1-医生 2-护士 3-收费员 4-药剂师 5-管理员 6-其他）',
  `gender` tinyint DEFAULT 1 COMMENT '性别',
  `birth_date` date COMMENT '出生日期',
  `hire_date` date COMMENT '入职日期',
  `id_card` varchar(18) COMMENT '身份证号',
  `phone` varchar(20) COMMENT '手机号码',
  `email` varchar(100) COMMENT '电子邮箱',
  `dept_id` bigint COMMENT '科室ID',
  `dept_name` varchar(200) COMMENT '科室ID',
  `title` varchar(50) COMMENT '职称',
  `position` varchar(50) COMMENT '职位',
  `specialty` varchar(200) COMMENT '专业特长',
  `education` varchar(50) COMMENT '学历',
  `avatar` varchar(200) COMMENT '头像地址',
  `is_expert` tinyint DEFAULT 0 COMMENT '是否专家（0-否 1-是）',
  `expert_price` decimal(10,2) DEFAULT 0.00 COMMENT '专家号价格',
  `status` tinyint DEFAULT 1 COMMENT '状态（0-停用 1-启用）',
  `create_by` varchar(64) COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) COMMENT '更新人',
  `update_time` datetime COMMENT '更新时间',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常 1-删除）',
  `remark` varchar(500) COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_emp_code` (`emp_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工';

-- ---------------- 参照关系（E-R 连线） ----------------
ALTER TABLE `biz_blood_crossmatch` ADD CONSTRAINT `fk_biz_blood_crossmatch_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_admission_id` FOREIGN KEY (`admission_id`) REFERENCES `biz_admission` (`admission_id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_apply_dept_id` FOREIGN KEY (`apply_dept_id`) REFERENCES `sys_department` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_apply_doctor_id` FOREIGN KEY (`apply_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_crossmatch_doctor_id` FOREIGN KEY (`crossmatch_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_issue_doctor_id` FOREIGN KEY (`issue_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_check_nurse_id` FOREIGN KEY (`check_nurse_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_check_nurse2_id` FOREIGN KEY (`check_nurse2_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_infusion_nurse_id` FOREIGN KEY (`infusion_nurse_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_reaction_reporter_id` FOREIGN KEY (`reaction_reporter_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_finish_doctor_id` FOREIGN KEY (`finish_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_record_id` FOREIGN KEY (`record_id`) REFERENCES `biz_inpatient_record` (`id`);
ALTER TABLE `biz_transfusion_apply` ADD CONSTRAINT `fk_biz_transfusion_apply_cancel_doctor_id` FOREIGN KEY (`cancel_doctor_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_approve` ADD CONSTRAINT `fk_biz_transfusion_approve_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_transfusion_apply` (`id`);
ALTER TABLE `biz_transfusion_approve` ADD CONSTRAINT `fk_biz_transfusion_approve_approver_id` FOREIGN KEY (`approver_id`) REFERENCES `sys_employee` (`id`);
ALTER TABLE `biz_transfusion_bag` ADD CONSTRAINT `fk_biz_transfusion_bag_apply_id` FOREIGN KEY (`apply_id`) REFERENCES `biz_transfusion_apply` (`id`);
ALTER TABLE `biz_transfusion_bag` ADD CONSTRAINT `fk_biz_transfusion_bag_admission_id` FOREIGN KEY (`admission_id`) REFERENCES `biz_admission` (`admission_id`);
ALTER TABLE `biz_transfusion_bag` ADD CONSTRAINT `fk_biz_transfusion_bag_patient_id` FOREIGN KEY (`patient_id`) REFERENCES `biz_patient` (`id`);
ALTER TABLE `biz_transfusion_bag` ADD CONSTRAINT `fk_biz_transfusion_bag_crossmatch_doctor_id` FOREIGN KEY (`crossmatch_doctor_id`) REFERENCES `sys_employee` (`id`);
